/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "yarn_server_resourcemanager_service_protos.pb-c.h"
void   hadoop__yarn__refresh_queues_request_proto__init
                     (Hadoop__Yarn__RefreshQueuesRequestProto         *message)
{
  static Hadoop__Yarn__RefreshQueuesRequestProto init_value = HADOOP__YARN__REFRESH_QUEUES_REQUEST_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__yarn__refresh_queues_request_proto__get_packed_size
                     (const Hadoop__Yarn__RefreshQueuesRequestProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_queues_request_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__yarn__refresh_queues_request_proto__pack
                     (const Hadoop__Yarn__RefreshQueuesRequestProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_queues_request_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__yarn__refresh_queues_request_proto__pack_to_buffer
                     (const Hadoop__Yarn__RefreshQueuesRequestProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_queues_request_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Yarn__RefreshQueuesRequestProto *
       hadoop__yarn__refresh_queues_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Yarn__RefreshQueuesRequestProto *)
     protobuf_c_message_unpack (&hadoop__yarn__refresh_queues_request_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__yarn__refresh_queues_request_proto__free_unpacked
                     (Hadoop__Yarn__RefreshQueuesRequestProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_queues_request_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__yarn__refresh_queues_response_proto__init
                     (Hadoop__Yarn__RefreshQueuesResponseProto         *message)
{
  static Hadoop__Yarn__RefreshQueuesResponseProto init_value = HADOOP__YARN__REFRESH_QUEUES_RESPONSE_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__yarn__refresh_queues_response_proto__get_packed_size
                     (const Hadoop__Yarn__RefreshQueuesResponseProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_queues_response_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__yarn__refresh_queues_response_proto__pack
                     (const Hadoop__Yarn__RefreshQueuesResponseProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_queues_response_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__yarn__refresh_queues_response_proto__pack_to_buffer
                     (const Hadoop__Yarn__RefreshQueuesResponseProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_queues_response_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Yarn__RefreshQueuesResponseProto *
       hadoop__yarn__refresh_queues_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Yarn__RefreshQueuesResponseProto *)
     protobuf_c_message_unpack (&hadoop__yarn__refresh_queues_response_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__yarn__refresh_queues_response_proto__free_unpacked
                     (Hadoop__Yarn__RefreshQueuesResponseProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_queues_response_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__yarn__refresh_nodes_request_proto__init
                     (Hadoop__Yarn__RefreshNodesRequestProto         *message)
{
  static Hadoop__Yarn__RefreshNodesRequestProto init_value = HADOOP__YARN__REFRESH_NODES_REQUEST_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__yarn__refresh_nodes_request_proto__get_packed_size
                     (const Hadoop__Yarn__RefreshNodesRequestProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_nodes_request_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__yarn__refresh_nodes_request_proto__pack
                     (const Hadoop__Yarn__RefreshNodesRequestProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_nodes_request_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__yarn__refresh_nodes_request_proto__pack_to_buffer
                     (const Hadoop__Yarn__RefreshNodesRequestProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_nodes_request_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Yarn__RefreshNodesRequestProto *
       hadoop__yarn__refresh_nodes_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Yarn__RefreshNodesRequestProto *)
     protobuf_c_message_unpack (&hadoop__yarn__refresh_nodes_request_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__yarn__refresh_nodes_request_proto__free_unpacked
                     (Hadoop__Yarn__RefreshNodesRequestProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_nodes_request_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__yarn__refresh_nodes_response_proto__init
                     (Hadoop__Yarn__RefreshNodesResponseProto         *message)
{
  static Hadoop__Yarn__RefreshNodesResponseProto init_value = HADOOP__YARN__REFRESH_NODES_RESPONSE_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__yarn__refresh_nodes_response_proto__get_packed_size
                     (const Hadoop__Yarn__RefreshNodesResponseProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_nodes_response_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__yarn__refresh_nodes_response_proto__pack
                     (const Hadoop__Yarn__RefreshNodesResponseProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_nodes_response_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__yarn__refresh_nodes_response_proto__pack_to_buffer
                     (const Hadoop__Yarn__RefreshNodesResponseProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_nodes_response_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Yarn__RefreshNodesResponseProto *
       hadoop__yarn__refresh_nodes_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Yarn__RefreshNodesResponseProto *)
     protobuf_c_message_unpack (&hadoop__yarn__refresh_nodes_response_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__yarn__refresh_nodes_response_proto__free_unpacked
                     (Hadoop__Yarn__RefreshNodesResponseProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_nodes_response_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__yarn__refresh_super_user_groups_configuration_request_proto__init
                     (Hadoop__Yarn__RefreshSuperUserGroupsConfigurationRequestProto         *message)
{
  static Hadoop__Yarn__RefreshSuperUserGroupsConfigurationRequestProto init_value = HADOOP__YARN__REFRESH_SUPER_USER_GROUPS_CONFIGURATION_REQUEST_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__yarn__refresh_super_user_groups_configuration_request_proto__get_packed_size
                     (const Hadoop__Yarn__RefreshSuperUserGroupsConfigurationRequestProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_super_user_groups_configuration_request_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__yarn__refresh_super_user_groups_configuration_request_proto__pack
                     (const Hadoop__Yarn__RefreshSuperUserGroupsConfigurationRequestProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_super_user_groups_configuration_request_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__yarn__refresh_super_user_groups_configuration_request_proto__pack_to_buffer
                     (const Hadoop__Yarn__RefreshSuperUserGroupsConfigurationRequestProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_super_user_groups_configuration_request_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Yarn__RefreshSuperUserGroupsConfigurationRequestProto *
       hadoop__yarn__refresh_super_user_groups_configuration_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Yarn__RefreshSuperUserGroupsConfigurationRequestProto *)
     protobuf_c_message_unpack (&hadoop__yarn__refresh_super_user_groups_configuration_request_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__yarn__refresh_super_user_groups_configuration_request_proto__free_unpacked
                     (Hadoop__Yarn__RefreshSuperUserGroupsConfigurationRequestProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_super_user_groups_configuration_request_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__yarn__refresh_super_user_groups_configuration_response_proto__init
                     (Hadoop__Yarn__RefreshSuperUserGroupsConfigurationResponseProto         *message)
{
  static Hadoop__Yarn__RefreshSuperUserGroupsConfigurationResponseProto init_value = HADOOP__YARN__REFRESH_SUPER_USER_GROUPS_CONFIGURATION_RESPONSE_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__yarn__refresh_super_user_groups_configuration_response_proto__get_packed_size
                     (const Hadoop__Yarn__RefreshSuperUserGroupsConfigurationResponseProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_super_user_groups_configuration_response_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__yarn__refresh_super_user_groups_configuration_response_proto__pack
                     (const Hadoop__Yarn__RefreshSuperUserGroupsConfigurationResponseProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_super_user_groups_configuration_response_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__yarn__refresh_super_user_groups_configuration_response_proto__pack_to_buffer
                     (const Hadoop__Yarn__RefreshSuperUserGroupsConfigurationResponseProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_super_user_groups_configuration_response_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Yarn__RefreshSuperUserGroupsConfigurationResponseProto *
       hadoop__yarn__refresh_super_user_groups_configuration_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Yarn__RefreshSuperUserGroupsConfigurationResponseProto *)
     protobuf_c_message_unpack (&hadoop__yarn__refresh_super_user_groups_configuration_response_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__yarn__refresh_super_user_groups_configuration_response_proto__free_unpacked
                     (Hadoop__Yarn__RefreshSuperUserGroupsConfigurationResponseProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_super_user_groups_configuration_response_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__yarn__refresh_user_to_groups_mappings_request_proto__init
                     (Hadoop__Yarn__RefreshUserToGroupsMappingsRequestProto         *message)
{
  static Hadoop__Yarn__RefreshUserToGroupsMappingsRequestProto init_value = HADOOP__YARN__REFRESH_USER_TO_GROUPS_MAPPINGS_REQUEST_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__yarn__refresh_user_to_groups_mappings_request_proto__get_packed_size
                     (const Hadoop__Yarn__RefreshUserToGroupsMappingsRequestProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_user_to_groups_mappings_request_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__yarn__refresh_user_to_groups_mappings_request_proto__pack
                     (const Hadoop__Yarn__RefreshUserToGroupsMappingsRequestProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_user_to_groups_mappings_request_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__yarn__refresh_user_to_groups_mappings_request_proto__pack_to_buffer
                     (const Hadoop__Yarn__RefreshUserToGroupsMappingsRequestProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_user_to_groups_mappings_request_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Yarn__RefreshUserToGroupsMappingsRequestProto *
       hadoop__yarn__refresh_user_to_groups_mappings_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Yarn__RefreshUserToGroupsMappingsRequestProto *)
     protobuf_c_message_unpack (&hadoop__yarn__refresh_user_to_groups_mappings_request_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__yarn__refresh_user_to_groups_mappings_request_proto__free_unpacked
                     (Hadoop__Yarn__RefreshUserToGroupsMappingsRequestProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_user_to_groups_mappings_request_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__yarn__refresh_user_to_groups_mappings_response_proto__init
                     (Hadoop__Yarn__RefreshUserToGroupsMappingsResponseProto         *message)
{
  static Hadoop__Yarn__RefreshUserToGroupsMappingsResponseProto init_value = HADOOP__YARN__REFRESH_USER_TO_GROUPS_MAPPINGS_RESPONSE_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__yarn__refresh_user_to_groups_mappings_response_proto__get_packed_size
                     (const Hadoop__Yarn__RefreshUserToGroupsMappingsResponseProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_user_to_groups_mappings_response_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__yarn__refresh_user_to_groups_mappings_response_proto__pack
                     (const Hadoop__Yarn__RefreshUserToGroupsMappingsResponseProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_user_to_groups_mappings_response_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__yarn__refresh_user_to_groups_mappings_response_proto__pack_to_buffer
                     (const Hadoop__Yarn__RefreshUserToGroupsMappingsResponseProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_user_to_groups_mappings_response_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Yarn__RefreshUserToGroupsMappingsResponseProto *
       hadoop__yarn__refresh_user_to_groups_mappings_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Yarn__RefreshUserToGroupsMappingsResponseProto *)
     protobuf_c_message_unpack (&hadoop__yarn__refresh_user_to_groups_mappings_response_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__yarn__refresh_user_to_groups_mappings_response_proto__free_unpacked
                     (Hadoop__Yarn__RefreshUserToGroupsMappingsResponseProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_user_to_groups_mappings_response_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__yarn__refresh_admin_acls_request_proto__init
                     (Hadoop__Yarn__RefreshAdminAclsRequestProto         *message)
{
  static Hadoop__Yarn__RefreshAdminAclsRequestProto init_value = HADOOP__YARN__REFRESH_ADMIN_ACLS_REQUEST_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__yarn__refresh_admin_acls_request_proto__get_packed_size
                     (const Hadoop__Yarn__RefreshAdminAclsRequestProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_admin_acls_request_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__yarn__refresh_admin_acls_request_proto__pack
                     (const Hadoop__Yarn__RefreshAdminAclsRequestProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_admin_acls_request_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__yarn__refresh_admin_acls_request_proto__pack_to_buffer
                     (const Hadoop__Yarn__RefreshAdminAclsRequestProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_admin_acls_request_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Yarn__RefreshAdminAclsRequestProto *
       hadoop__yarn__refresh_admin_acls_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Yarn__RefreshAdminAclsRequestProto *)
     protobuf_c_message_unpack (&hadoop__yarn__refresh_admin_acls_request_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__yarn__refresh_admin_acls_request_proto__free_unpacked
                     (Hadoop__Yarn__RefreshAdminAclsRequestProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_admin_acls_request_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__yarn__refresh_admin_acls_response_proto__init
                     (Hadoop__Yarn__RefreshAdminAclsResponseProto         *message)
{
  static Hadoop__Yarn__RefreshAdminAclsResponseProto init_value = HADOOP__YARN__REFRESH_ADMIN_ACLS_RESPONSE_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__yarn__refresh_admin_acls_response_proto__get_packed_size
                     (const Hadoop__Yarn__RefreshAdminAclsResponseProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_admin_acls_response_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__yarn__refresh_admin_acls_response_proto__pack
                     (const Hadoop__Yarn__RefreshAdminAclsResponseProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_admin_acls_response_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__yarn__refresh_admin_acls_response_proto__pack_to_buffer
                     (const Hadoop__Yarn__RefreshAdminAclsResponseProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_admin_acls_response_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Yarn__RefreshAdminAclsResponseProto *
       hadoop__yarn__refresh_admin_acls_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Yarn__RefreshAdminAclsResponseProto *)
     protobuf_c_message_unpack (&hadoop__yarn__refresh_admin_acls_response_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__yarn__refresh_admin_acls_response_proto__free_unpacked
                     (Hadoop__Yarn__RefreshAdminAclsResponseProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_admin_acls_response_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__yarn__refresh_service_acls_request_proto__init
                     (Hadoop__Yarn__RefreshServiceAclsRequestProto         *message)
{
  static Hadoop__Yarn__RefreshServiceAclsRequestProto init_value = HADOOP__YARN__REFRESH_SERVICE_ACLS_REQUEST_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__yarn__refresh_service_acls_request_proto__get_packed_size
                     (const Hadoop__Yarn__RefreshServiceAclsRequestProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_service_acls_request_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__yarn__refresh_service_acls_request_proto__pack
                     (const Hadoop__Yarn__RefreshServiceAclsRequestProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_service_acls_request_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__yarn__refresh_service_acls_request_proto__pack_to_buffer
                     (const Hadoop__Yarn__RefreshServiceAclsRequestProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_service_acls_request_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Yarn__RefreshServiceAclsRequestProto *
       hadoop__yarn__refresh_service_acls_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Yarn__RefreshServiceAclsRequestProto *)
     protobuf_c_message_unpack (&hadoop__yarn__refresh_service_acls_request_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__yarn__refresh_service_acls_request_proto__free_unpacked
                     (Hadoop__Yarn__RefreshServiceAclsRequestProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_service_acls_request_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__yarn__refresh_service_acls_response_proto__init
                     (Hadoop__Yarn__RefreshServiceAclsResponseProto         *message)
{
  static Hadoop__Yarn__RefreshServiceAclsResponseProto init_value = HADOOP__YARN__REFRESH_SERVICE_ACLS_RESPONSE_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__yarn__refresh_service_acls_response_proto__get_packed_size
                     (const Hadoop__Yarn__RefreshServiceAclsResponseProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_service_acls_response_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__yarn__refresh_service_acls_response_proto__pack
                     (const Hadoop__Yarn__RefreshServiceAclsResponseProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_service_acls_response_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__yarn__refresh_service_acls_response_proto__pack_to_buffer
                     (const Hadoop__Yarn__RefreshServiceAclsResponseProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_service_acls_response_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Yarn__RefreshServiceAclsResponseProto *
       hadoop__yarn__refresh_service_acls_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Yarn__RefreshServiceAclsResponseProto *)
     protobuf_c_message_unpack (&hadoop__yarn__refresh_service_acls_response_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__yarn__refresh_service_acls_response_proto__free_unpacked
                     (Hadoop__Yarn__RefreshServiceAclsResponseProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__refresh_service_acls_response_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__yarn__get_groups_for_user_request_proto__init
                     (Hadoop__Yarn__GetGroupsForUserRequestProto         *message)
{
  static Hadoop__Yarn__GetGroupsForUserRequestProto init_value = HADOOP__YARN__GET_GROUPS_FOR_USER_REQUEST_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__yarn__get_groups_for_user_request_proto__get_packed_size
                     (const Hadoop__Yarn__GetGroupsForUserRequestProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__get_groups_for_user_request_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__yarn__get_groups_for_user_request_proto__pack
                     (const Hadoop__Yarn__GetGroupsForUserRequestProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__get_groups_for_user_request_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__yarn__get_groups_for_user_request_proto__pack_to_buffer
                     (const Hadoop__Yarn__GetGroupsForUserRequestProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__get_groups_for_user_request_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Yarn__GetGroupsForUserRequestProto *
       hadoop__yarn__get_groups_for_user_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Yarn__GetGroupsForUserRequestProto *)
     protobuf_c_message_unpack (&hadoop__yarn__get_groups_for_user_request_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__yarn__get_groups_for_user_request_proto__free_unpacked
                     (Hadoop__Yarn__GetGroupsForUserRequestProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__get_groups_for_user_request_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__yarn__get_groups_for_user_response_proto__init
                     (Hadoop__Yarn__GetGroupsForUserResponseProto         *message)
{
  static Hadoop__Yarn__GetGroupsForUserResponseProto init_value = HADOOP__YARN__GET_GROUPS_FOR_USER_RESPONSE_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__yarn__get_groups_for_user_response_proto__get_packed_size
                     (const Hadoop__Yarn__GetGroupsForUserResponseProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__get_groups_for_user_response_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__yarn__get_groups_for_user_response_proto__pack
                     (const Hadoop__Yarn__GetGroupsForUserResponseProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__get_groups_for_user_response_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__yarn__get_groups_for_user_response_proto__pack_to_buffer
                     (const Hadoop__Yarn__GetGroupsForUserResponseProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__get_groups_for_user_response_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Yarn__GetGroupsForUserResponseProto *
       hadoop__yarn__get_groups_for_user_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Yarn__GetGroupsForUserResponseProto *)
     protobuf_c_message_unpack (&hadoop__yarn__get_groups_for_user_response_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__yarn__get_groups_for_user_response_proto__free_unpacked
                     (Hadoop__Yarn__GetGroupsForUserResponseProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__get_groups_for_user_response_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__yarn__application_state_data_proto__init
                     (Hadoop__Yarn__ApplicationStateDataProto         *message)
{
  static Hadoop__Yarn__ApplicationStateDataProto init_value = HADOOP__YARN__APPLICATION_STATE_DATA_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__yarn__application_state_data_proto__get_packed_size
                     (const Hadoop__Yarn__ApplicationStateDataProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__application_state_data_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__yarn__application_state_data_proto__pack
                     (const Hadoop__Yarn__ApplicationStateDataProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__application_state_data_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__yarn__application_state_data_proto__pack_to_buffer
                     (const Hadoop__Yarn__ApplicationStateDataProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__application_state_data_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Yarn__ApplicationStateDataProto *
       hadoop__yarn__application_state_data_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Yarn__ApplicationStateDataProto *)
     protobuf_c_message_unpack (&hadoop__yarn__application_state_data_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__yarn__application_state_data_proto__free_unpacked
                     (Hadoop__Yarn__ApplicationStateDataProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__application_state_data_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__yarn__application_attempt_state_data_proto__init
                     (Hadoop__Yarn__ApplicationAttemptStateDataProto         *message)
{
  static Hadoop__Yarn__ApplicationAttemptStateDataProto init_value = HADOOP__YARN__APPLICATION_ATTEMPT_STATE_DATA_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__yarn__application_attempt_state_data_proto__get_packed_size
                     (const Hadoop__Yarn__ApplicationAttemptStateDataProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__application_attempt_state_data_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__yarn__application_attempt_state_data_proto__pack
                     (const Hadoop__Yarn__ApplicationAttemptStateDataProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__application_attempt_state_data_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__yarn__application_attempt_state_data_proto__pack_to_buffer
                     (const Hadoop__Yarn__ApplicationAttemptStateDataProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__application_attempt_state_data_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Yarn__ApplicationAttemptStateDataProto *
       hadoop__yarn__application_attempt_state_data_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Yarn__ApplicationAttemptStateDataProto *)
     protobuf_c_message_unpack (&hadoop__yarn__application_attempt_state_data_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__yarn__application_attempt_state_data_proto__free_unpacked
                     (Hadoop__Yarn__ApplicationAttemptStateDataProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__application_attempt_state_data_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
#define hadoop__yarn__refresh_queues_request_proto__field_descriptors NULL
#define hadoop__yarn__refresh_queues_request_proto__field_indices_by_name NULL
#define hadoop__yarn__refresh_queues_request_proto__number_ranges NULL
const ProtobufCMessageDescriptor hadoop__yarn__refresh_queues_request_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.yarn.RefreshQueuesRequestProto",
  "RefreshQueuesRequestProto",
  "Hadoop__Yarn__RefreshQueuesRequestProto",
  "hadoop.yarn",
  sizeof(Hadoop__Yarn__RefreshQueuesRequestProto),
  0,
  hadoop__yarn__refresh_queues_request_proto__field_descriptors,
  hadoop__yarn__refresh_queues_request_proto__field_indices_by_name,
  0,  hadoop__yarn__refresh_queues_request_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__yarn__refresh_queues_request_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define hadoop__yarn__refresh_queues_response_proto__field_descriptors NULL
#define hadoop__yarn__refresh_queues_response_proto__field_indices_by_name NULL
#define hadoop__yarn__refresh_queues_response_proto__number_ranges NULL
const ProtobufCMessageDescriptor hadoop__yarn__refresh_queues_response_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.yarn.RefreshQueuesResponseProto",
  "RefreshQueuesResponseProto",
  "Hadoop__Yarn__RefreshQueuesResponseProto",
  "hadoop.yarn",
  sizeof(Hadoop__Yarn__RefreshQueuesResponseProto),
  0,
  hadoop__yarn__refresh_queues_response_proto__field_descriptors,
  hadoop__yarn__refresh_queues_response_proto__field_indices_by_name,
  0,  hadoop__yarn__refresh_queues_response_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__yarn__refresh_queues_response_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define hadoop__yarn__refresh_nodes_request_proto__field_descriptors NULL
#define hadoop__yarn__refresh_nodes_request_proto__field_indices_by_name NULL
#define hadoop__yarn__refresh_nodes_request_proto__number_ranges NULL
const ProtobufCMessageDescriptor hadoop__yarn__refresh_nodes_request_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.yarn.RefreshNodesRequestProto",
  "RefreshNodesRequestProto",
  "Hadoop__Yarn__RefreshNodesRequestProto",
  "hadoop.yarn",
  sizeof(Hadoop__Yarn__RefreshNodesRequestProto),
  0,
  hadoop__yarn__refresh_nodes_request_proto__field_descriptors,
  hadoop__yarn__refresh_nodes_request_proto__field_indices_by_name,
  0,  hadoop__yarn__refresh_nodes_request_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__yarn__refresh_nodes_request_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define hadoop__yarn__refresh_nodes_response_proto__field_descriptors NULL
#define hadoop__yarn__refresh_nodes_response_proto__field_indices_by_name NULL
#define hadoop__yarn__refresh_nodes_response_proto__number_ranges NULL
const ProtobufCMessageDescriptor hadoop__yarn__refresh_nodes_response_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.yarn.RefreshNodesResponseProto",
  "RefreshNodesResponseProto",
  "Hadoop__Yarn__RefreshNodesResponseProto",
  "hadoop.yarn",
  sizeof(Hadoop__Yarn__RefreshNodesResponseProto),
  0,
  hadoop__yarn__refresh_nodes_response_proto__field_descriptors,
  hadoop__yarn__refresh_nodes_response_proto__field_indices_by_name,
  0,  hadoop__yarn__refresh_nodes_response_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__yarn__refresh_nodes_response_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define hadoop__yarn__refresh_super_user_groups_configuration_request_proto__field_descriptors NULL
#define hadoop__yarn__refresh_super_user_groups_configuration_request_proto__field_indices_by_name NULL
#define hadoop__yarn__refresh_super_user_groups_configuration_request_proto__number_ranges NULL
const ProtobufCMessageDescriptor hadoop__yarn__refresh_super_user_groups_configuration_request_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.yarn.RefreshSuperUserGroupsConfigurationRequestProto",
  "RefreshSuperUserGroupsConfigurationRequestProto",
  "Hadoop__Yarn__RefreshSuperUserGroupsConfigurationRequestProto",
  "hadoop.yarn",
  sizeof(Hadoop__Yarn__RefreshSuperUserGroupsConfigurationRequestProto),
  0,
  hadoop__yarn__refresh_super_user_groups_configuration_request_proto__field_descriptors,
  hadoop__yarn__refresh_super_user_groups_configuration_request_proto__field_indices_by_name,
  0,  hadoop__yarn__refresh_super_user_groups_configuration_request_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__yarn__refresh_super_user_groups_configuration_request_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define hadoop__yarn__refresh_super_user_groups_configuration_response_proto__field_descriptors NULL
#define hadoop__yarn__refresh_super_user_groups_configuration_response_proto__field_indices_by_name NULL
#define hadoop__yarn__refresh_super_user_groups_configuration_response_proto__number_ranges NULL
const ProtobufCMessageDescriptor hadoop__yarn__refresh_super_user_groups_configuration_response_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.yarn.RefreshSuperUserGroupsConfigurationResponseProto",
  "RefreshSuperUserGroupsConfigurationResponseProto",
  "Hadoop__Yarn__RefreshSuperUserGroupsConfigurationResponseProto",
  "hadoop.yarn",
  sizeof(Hadoop__Yarn__RefreshSuperUserGroupsConfigurationResponseProto),
  0,
  hadoop__yarn__refresh_super_user_groups_configuration_response_proto__field_descriptors,
  hadoop__yarn__refresh_super_user_groups_configuration_response_proto__field_indices_by_name,
  0,  hadoop__yarn__refresh_super_user_groups_configuration_response_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__yarn__refresh_super_user_groups_configuration_response_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define hadoop__yarn__refresh_user_to_groups_mappings_request_proto__field_descriptors NULL
#define hadoop__yarn__refresh_user_to_groups_mappings_request_proto__field_indices_by_name NULL
#define hadoop__yarn__refresh_user_to_groups_mappings_request_proto__number_ranges NULL
const ProtobufCMessageDescriptor hadoop__yarn__refresh_user_to_groups_mappings_request_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.yarn.RefreshUserToGroupsMappingsRequestProto",
  "RefreshUserToGroupsMappingsRequestProto",
  "Hadoop__Yarn__RefreshUserToGroupsMappingsRequestProto",
  "hadoop.yarn",
  sizeof(Hadoop__Yarn__RefreshUserToGroupsMappingsRequestProto),
  0,
  hadoop__yarn__refresh_user_to_groups_mappings_request_proto__field_descriptors,
  hadoop__yarn__refresh_user_to_groups_mappings_request_proto__field_indices_by_name,
  0,  hadoop__yarn__refresh_user_to_groups_mappings_request_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__yarn__refresh_user_to_groups_mappings_request_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define hadoop__yarn__refresh_user_to_groups_mappings_response_proto__field_descriptors NULL
#define hadoop__yarn__refresh_user_to_groups_mappings_response_proto__field_indices_by_name NULL
#define hadoop__yarn__refresh_user_to_groups_mappings_response_proto__number_ranges NULL
const ProtobufCMessageDescriptor hadoop__yarn__refresh_user_to_groups_mappings_response_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.yarn.RefreshUserToGroupsMappingsResponseProto",
  "RefreshUserToGroupsMappingsResponseProto",
  "Hadoop__Yarn__RefreshUserToGroupsMappingsResponseProto",
  "hadoop.yarn",
  sizeof(Hadoop__Yarn__RefreshUserToGroupsMappingsResponseProto),
  0,
  hadoop__yarn__refresh_user_to_groups_mappings_response_proto__field_descriptors,
  hadoop__yarn__refresh_user_to_groups_mappings_response_proto__field_indices_by_name,
  0,  hadoop__yarn__refresh_user_to_groups_mappings_response_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__yarn__refresh_user_to_groups_mappings_response_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define hadoop__yarn__refresh_admin_acls_request_proto__field_descriptors NULL
#define hadoop__yarn__refresh_admin_acls_request_proto__field_indices_by_name NULL
#define hadoop__yarn__refresh_admin_acls_request_proto__number_ranges NULL
const ProtobufCMessageDescriptor hadoop__yarn__refresh_admin_acls_request_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.yarn.RefreshAdminAclsRequestProto",
  "RefreshAdminAclsRequestProto",
  "Hadoop__Yarn__RefreshAdminAclsRequestProto",
  "hadoop.yarn",
  sizeof(Hadoop__Yarn__RefreshAdminAclsRequestProto),
  0,
  hadoop__yarn__refresh_admin_acls_request_proto__field_descriptors,
  hadoop__yarn__refresh_admin_acls_request_proto__field_indices_by_name,
  0,  hadoop__yarn__refresh_admin_acls_request_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__yarn__refresh_admin_acls_request_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define hadoop__yarn__refresh_admin_acls_response_proto__field_descriptors NULL
#define hadoop__yarn__refresh_admin_acls_response_proto__field_indices_by_name NULL
#define hadoop__yarn__refresh_admin_acls_response_proto__number_ranges NULL
const ProtobufCMessageDescriptor hadoop__yarn__refresh_admin_acls_response_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.yarn.RefreshAdminAclsResponseProto",
  "RefreshAdminAclsResponseProto",
  "Hadoop__Yarn__RefreshAdminAclsResponseProto",
  "hadoop.yarn",
  sizeof(Hadoop__Yarn__RefreshAdminAclsResponseProto),
  0,
  hadoop__yarn__refresh_admin_acls_response_proto__field_descriptors,
  hadoop__yarn__refresh_admin_acls_response_proto__field_indices_by_name,
  0,  hadoop__yarn__refresh_admin_acls_response_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__yarn__refresh_admin_acls_response_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define hadoop__yarn__refresh_service_acls_request_proto__field_descriptors NULL
#define hadoop__yarn__refresh_service_acls_request_proto__field_indices_by_name NULL
#define hadoop__yarn__refresh_service_acls_request_proto__number_ranges NULL
const ProtobufCMessageDescriptor hadoop__yarn__refresh_service_acls_request_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.yarn.RefreshServiceAclsRequestProto",
  "RefreshServiceAclsRequestProto",
  "Hadoop__Yarn__RefreshServiceAclsRequestProto",
  "hadoop.yarn",
  sizeof(Hadoop__Yarn__RefreshServiceAclsRequestProto),
  0,
  hadoop__yarn__refresh_service_acls_request_proto__field_descriptors,
  hadoop__yarn__refresh_service_acls_request_proto__field_indices_by_name,
  0,  hadoop__yarn__refresh_service_acls_request_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__yarn__refresh_service_acls_request_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define hadoop__yarn__refresh_service_acls_response_proto__field_descriptors NULL
#define hadoop__yarn__refresh_service_acls_response_proto__field_indices_by_name NULL
#define hadoop__yarn__refresh_service_acls_response_proto__number_ranges NULL
const ProtobufCMessageDescriptor hadoop__yarn__refresh_service_acls_response_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.yarn.RefreshServiceAclsResponseProto",
  "RefreshServiceAclsResponseProto",
  "Hadoop__Yarn__RefreshServiceAclsResponseProto",
  "hadoop.yarn",
  sizeof(Hadoop__Yarn__RefreshServiceAclsResponseProto),
  0,
  hadoop__yarn__refresh_service_acls_response_proto__field_descriptors,
  hadoop__yarn__refresh_service_acls_response_proto__field_indices_by_name,
  0,  hadoop__yarn__refresh_service_acls_response_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__yarn__refresh_service_acls_response_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hadoop__yarn__get_groups_for_user_request_proto__field_descriptors[1] =
{
  {
    "user",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Yarn__GetGroupsForUserRequestProto, user),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__yarn__get_groups_for_user_request_proto__field_indices_by_name[] = {
  0,   /* field[0] = user */
};
static const ProtobufCIntRange hadoop__yarn__get_groups_for_user_request_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor hadoop__yarn__get_groups_for_user_request_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.yarn.GetGroupsForUserRequestProto",
  "GetGroupsForUserRequestProto",
  "Hadoop__Yarn__GetGroupsForUserRequestProto",
  "hadoop.yarn",
  sizeof(Hadoop__Yarn__GetGroupsForUserRequestProto),
  1,
  hadoop__yarn__get_groups_for_user_request_proto__field_descriptors,
  hadoop__yarn__get_groups_for_user_request_proto__field_indices_by_name,
  1,  hadoop__yarn__get_groups_for_user_request_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__yarn__get_groups_for_user_request_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hadoop__yarn__get_groups_for_user_response_proto__field_descriptors[1] =
{
  {
    "groups",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    PROTOBUF_C_OFFSETOF(Hadoop__Yarn__GetGroupsForUserResponseProto, n_groups),
    PROTOBUF_C_OFFSETOF(Hadoop__Yarn__GetGroupsForUserResponseProto, groups),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__yarn__get_groups_for_user_response_proto__field_indices_by_name[] = {
  0,   /* field[0] = groups */
};
static const ProtobufCIntRange hadoop__yarn__get_groups_for_user_response_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor hadoop__yarn__get_groups_for_user_response_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.yarn.GetGroupsForUserResponseProto",
  "GetGroupsForUserResponseProto",
  "Hadoop__Yarn__GetGroupsForUserResponseProto",
  "hadoop.yarn",
  sizeof(Hadoop__Yarn__GetGroupsForUserResponseProto),
  1,
  hadoop__yarn__get_groups_for_user_response_proto__field_descriptors,
  hadoop__yarn__get_groups_for_user_response_proto__field_indices_by_name,
  1,  hadoop__yarn__get_groups_for_user_response_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__yarn__get_groups_for_user_response_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hadoop__yarn__application_state_data_proto__field_descriptors[3] =
{
  {
    "submit_time",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    PROTOBUF_C_OFFSETOF(Hadoop__Yarn__ApplicationStateDataProto, has_submit_time),
    PROTOBUF_C_OFFSETOF(Hadoop__Yarn__ApplicationStateDataProto, submit_time),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "application_submission_context",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Yarn__ApplicationStateDataProto, application_submission_context),
    &hadoop__yarn__application_submission_context_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Yarn__ApplicationStateDataProto, user),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__yarn__application_state_data_proto__field_indices_by_name[] = {
  1,   /* field[1] = application_submission_context */
  0,   /* field[0] = submit_time */
  2,   /* field[2] = user */
};
static const ProtobufCIntRange hadoop__yarn__application_state_data_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor hadoop__yarn__application_state_data_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.yarn.ApplicationStateDataProto",
  "ApplicationStateDataProto",
  "Hadoop__Yarn__ApplicationStateDataProto",
  "hadoop.yarn",
  sizeof(Hadoop__Yarn__ApplicationStateDataProto),
  3,
  hadoop__yarn__application_state_data_proto__field_descriptors,
  hadoop__yarn__application_state_data_proto__field_indices_by_name,
  1,  hadoop__yarn__application_state_data_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__yarn__application_state_data_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hadoop__yarn__application_attempt_state_data_proto__field_descriptors[3] =
{
  {
    "attemptId",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Yarn__ApplicationAttemptStateDataProto, attemptid),
    &hadoop__yarn__application_attempt_id_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "master_container",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Yarn__ApplicationAttemptStateDataProto, master_container),
    &hadoop__yarn__container_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "app_attempt_tokens",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Hadoop__Yarn__ApplicationAttemptStateDataProto, has_app_attempt_tokens),
    PROTOBUF_C_OFFSETOF(Hadoop__Yarn__ApplicationAttemptStateDataProto, app_attempt_tokens),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__yarn__application_attempt_state_data_proto__field_indices_by_name[] = {
  2,   /* field[2] = app_attempt_tokens */
  0,   /* field[0] = attemptId */
  1,   /* field[1] = master_container */
};
static const ProtobufCIntRange hadoop__yarn__application_attempt_state_data_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor hadoop__yarn__application_attempt_state_data_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.yarn.ApplicationAttemptStateDataProto",
  "ApplicationAttemptStateDataProto",
  "Hadoop__Yarn__ApplicationAttemptStateDataProto",
  "hadoop.yarn",
  sizeof(Hadoop__Yarn__ApplicationAttemptStateDataProto),
  3,
  hadoop__yarn__application_attempt_state_data_proto__field_descriptors,
  hadoop__yarn__application_attempt_state_data_proto__field_indices_by_name,
  1,  hadoop__yarn__application_attempt_state_data_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__yarn__application_attempt_state_data_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
