/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "applicationmaster_protocol.pb-c.h"
static const ProtobufCMethodDescriptor application_master_protocol_service__method_descriptors[3] =
{
  { "registerApplicationMaster", &register_application_master_request_proto__descriptor, &register_application_master_response_proto__descriptor },
  { "finishApplicationMaster", &finish_application_master_request_proto__descriptor, &finish_application_master_response_proto__descriptor },
  { "allocate", &allocate_request_proto__descriptor, &allocate_response_proto__descriptor },
};
const unsigned application_master_protocol_service__method_indices_by_name[] = {
  2,        /* allocate */
  1,        /* finishApplicationMaster */
  0         /* registerApplicationMaster */
};
const ProtobufCServiceDescriptor application_master_protocol_service__descriptor =
{
  PROTOBUF_C_SERVICE_DESCRIPTOR_MAGIC,
  "ApplicationMasterProtocolService",
  "registerApplicationMaster",
  "ApplicationMasterProtocolService",
  "",
  3,
  application_master_protocol_service__method_descriptors,
  application_master_protocol_service__method_indices_by_name
};
void application_master_protocol_service__register_application_master(ProtobufCService *service,
                                                                      const RegisterApplicationMasterRequestProto *input,
                                                                      RegisterApplicationMasterResponseProto_Closure closure,
                                                                      void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &application_master_protocol_service__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void application_master_protocol_service__finish_application_master(ProtobufCService *service,
                                                                    const FinishApplicationMasterRequestProto *input,
                                                                    FinishApplicationMasterResponseProto_Closure closure,
                                                                    void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &application_master_protocol_service__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void application_master_protocol_service__allocate(ProtobufCService *service,
                                                   const AllocateRequestProto *input,
                                                   AllocateResponseProto_Closure closure,
                                                   void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &application_master_protocol_service__descriptor);
  service->invoke(service, 2, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void application_master_protocol_service__init (ApplicationMasterProtocolService_Service *service,
                                                ApplicationMasterProtocolService_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &application_master_protocol_service__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
