/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "ClientDatanodeProtocol.pb-c.h"
void   hadoop__hdfs__get_replica_visible_length_request_proto__init
                     (Hadoop__Hdfs__GetReplicaVisibleLengthRequestProto         *message)
{
  static Hadoop__Hdfs__GetReplicaVisibleLengthRequestProto init_value = HADOOP__HDFS__GET_REPLICA_VISIBLE_LENGTH_REQUEST_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__hdfs__get_replica_visible_length_request_proto__get_packed_size
                     (const Hadoop__Hdfs__GetReplicaVisibleLengthRequestProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_replica_visible_length_request_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__hdfs__get_replica_visible_length_request_proto__pack
                     (const Hadoop__Hdfs__GetReplicaVisibleLengthRequestProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_replica_visible_length_request_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__hdfs__get_replica_visible_length_request_proto__pack_to_buffer
                     (const Hadoop__Hdfs__GetReplicaVisibleLengthRequestProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_replica_visible_length_request_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Hdfs__GetReplicaVisibleLengthRequestProto *
       hadoop__hdfs__get_replica_visible_length_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Hdfs__GetReplicaVisibleLengthRequestProto *)
     protobuf_c_message_unpack (&hadoop__hdfs__get_replica_visible_length_request_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__hdfs__get_replica_visible_length_request_proto__free_unpacked
                     (Hadoop__Hdfs__GetReplicaVisibleLengthRequestProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_replica_visible_length_request_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__hdfs__get_replica_visible_length_response_proto__init
                     (Hadoop__Hdfs__GetReplicaVisibleLengthResponseProto         *message)
{
  static Hadoop__Hdfs__GetReplicaVisibleLengthResponseProto init_value = HADOOP__HDFS__GET_REPLICA_VISIBLE_LENGTH_RESPONSE_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__hdfs__get_replica_visible_length_response_proto__get_packed_size
                     (const Hadoop__Hdfs__GetReplicaVisibleLengthResponseProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_replica_visible_length_response_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__hdfs__get_replica_visible_length_response_proto__pack
                     (const Hadoop__Hdfs__GetReplicaVisibleLengthResponseProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_replica_visible_length_response_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__hdfs__get_replica_visible_length_response_proto__pack_to_buffer
                     (const Hadoop__Hdfs__GetReplicaVisibleLengthResponseProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_replica_visible_length_response_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Hdfs__GetReplicaVisibleLengthResponseProto *
       hadoop__hdfs__get_replica_visible_length_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Hdfs__GetReplicaVisibleLengthResponseProto *)
     protobuf_c_message_unpack (&hadoop__hdfs__get_replica_visible_length_response_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__hdfs__get_replica_visible_length_response_proto__free_unpacked
                     (Hadoop__Hdfs__GetReplicaVisibleLengthResponseProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_replica_visible_length_response_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__hdfs__refresh_namenodes_request_proto__init
                     (Hadoop__Hdfs__RefreshNamenodesRequestProto         *message)
{
  static Hadoop__Hdfs__RefreshNamenodesRequestProto init_value = HADOOP__HDFS__REFRESH_NAMENODES_REQUEST_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__hdfs__refresh_namenodes_request_proto__get_packed_size
                     (const Hadoop__Hdfs__RefreshNamenodesRequestProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__refresh_namenodes_request_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__hdfs__refresh_namenodes_request_proto__pack
                     (const Hadoop__Hdfs__RefreshNamenodesRequestProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__refresh_namenodes_request_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__hdfs__refresh_namenodes_request_proto__pack_to_buffer
                     (const Hadoop__Hdfs__RefreshNamenodesRequestProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__refresh_namenodes_request_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Hdfs__RefreshNamenodesRequestProto *
       hadoop__hdfs__refresh_namenodes_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Hdfs__RefreshNamenodesRequestProto *)
     protobuf_c_message_unpack (&hadoop__hdfs__refresh_namenodes_request_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__hdfs__refresh_namenodes_request_proto__free_unpacked
                     (Hadoop__Hdfs__RefreshNamenodesRequestProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__refresh_namenodes_request_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__hdfs__refresh_namenodes_response_proto__init
                     (Hadoop__Hdfs__RefreshNamenodesResponseProto         *message)
{
  static Hadoop__Hdfs__RefreshNamenodesResponseProto init_value = HADOOP__HDFS__REFRESH_NAMENODES_RESPONSE_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__hdfs__refresh_namenodes_response_proto__get_packed_size
                     (const Hadoop__Hdfs__RefreshNamenodesResponseProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__refresh_namenodes_response_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__hdfs__refresh_namenodes_response_proto__pack
                     (const Hadoop__Hdfs__RefreshNamenodesResponseProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__refresh_namenodes_response_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__hdfs__refresh_namenodes_response_proto__pack_to_buffer
                     (const Hadoop__Hdfs__RefreshNamenodesResponseProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__refresh_namenodes_response_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Hdfs__RefreshNamenodesResponseProto *
       hadoop__hdfs__refresh_namenodes_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Hdfs__RefreshNamenodesResponseProto *)
     protobuf_c_message_unpack (&hadoop__hdfs__refresh_namenodes_response_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__hdfs__refresh_namenodes_response_proto__free_unpacked
                     (Hadoop__Hdfs__RefreshNamenodesResponseProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__refresh_namenodes_response_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__hdfs__delete_block_pool_request_proto__init
                     (Hadoop__Hdfs__DeleteBlockPoolRequestProto         *message)
{
  static Hadoop__Hdfs__DeleteBlockPoolRequestProto init_value = HADOOP__HDFS__DELETE_BLOCK_POOL_REQUEST_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__hdfs__delete_block_pool_request_proto__get_packed_size
                     (const Hadoop__Hdfs__DeleteBlockPoolRequestProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__delete_block_pool_request_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__hdfs__delete_block_pool_request_proto__pack
                     (const Hadoop__Hdfs__DeleteBlockPoolRequestProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__delete_block_pool_request_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__hdfs__delete_block_pool_request_proto__pack_to_buffer
                     (const Hadoop__Hdfs__DeleteBlockPoolRequestProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__delete_block_pool_request_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Hdfs__DeleteBlockPoolRequestProto *
       hadoop__hdfs__delete_block_pool_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Hdfs__DeleteBlockPoolRequestProto *)
     protobuf_c_message_unpack (&hadoop__hdfs__delete_block_pool_request_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__hdfs__delete_block_pool_request_proto__free_unpacked
                     (Hadoop__Hdfs__DeleteBlockPoolRequestProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__delete_block_pool_request_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__hdfs__delete_block_pool_response_proto__init
                     (Hadoop__Hdfs__DeleteBlockPoolResponseProto         *message)
{
  static Hadoop__Hdfs__DeleteBlockPoolResponseProto init_value = HADOOP__HDFS__DELETE_BLOCK_POOL_RESPONSE_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__hdfs__delete_block_pool_response_proto__get_packed_size
                     (const Hadoop__Hdfs__DeleteBlockPoolResponseProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__delete_block_pool_response_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__hdfs__delete_block_pool_response_proto__pack
                     (const Hadoop__Hdfs__DeleteBlockPoolResponseProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__delete_block_pool_response_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__hdfs__delete_block_pool_response_proto__pack_to_buffer
                     (const Hadoop__Hdfs__DeleteBlockPoolResponseProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__delete_block_pool_response_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Hdfs__DeleteBlockPoolResponseProto *
       hadoop__hdfs__delete_block_pool_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Hdfs__DeleteBlockPoolResponseProto *)
     protobuf_c_message_unpack (&hadoop__hdfs__delete_block_pool_response_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__hdfs__delete_block_pool_response_proto__free_unpacked
                     (Hadoop__Hdfs__DeleteBlockPoolResponseProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__delete_block_pool_response_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__hdfs__get_block_local_path_info_request_proto__init
                     (Hadoop__Hdfs__GetBlockLocalPathInfoRequestProto         *message)
{
  static Hadoop__Hdfs__GetBlockLocalPathInfoRequestProto init_value = HADOOP__HDFS__GET_BLOCK_LOCAL_PATH_INFO_REQUEST_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__hdfs__get_block_local_path_info_request_proto__get_packed_size
                     (const Hadoop__Hdfs__GetBlockLocalPathInfoRequestProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_block_local_path_info_request_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__hdfs__get_block_local_path_info_request_proto__pack
                     (const Hadoop__Hdfs__GetBlockLocalPathInfoRequestProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_block_local_path_info_request_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__hdfs__get_block_local_path_info_request_proto__pack_to_buffer
                     (const Hadoop__Hdfs__GetBlockLocalPathInfoRequestProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_block_local_path_info_request_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Hdfs__GetBlockLocalPathInfoRequestProto *
       hadoop__hdfs__get_block_local_path_info_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Hdfs__GetBlockLocalPathInfoRequestProto *)
     protobuf_c_message_unpack (&hadoop__hdfs__get_block_local_path_info_request_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__hdfs__get_block_local_path_info_request_proto__free_unpacked
                     (Hadoop__Hdfs__GetBlockLocalPathInfoRequestProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_block_local_path_info_request_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__hdfs__get_block_local_path_info_response_proto__init
                     (Hadoop__Hdfs__GetBlockLocalPathInfoResponseProto         *message)
{
  static Hadoop__Hdfs__GetBlockLocalPathInfoResponseProto init_value = HADOOP__HDFS__GET_BLOCK_LOCAL_PATH_INFO_RESPONSE_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__hdfs__get_block_local_path_info_response_proto__get_packed_size
                     (const Hadoop__Hdfs__GetBlockLocalPathInfoResponseProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_block_local_path_info_response_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__hdfs__get_block_local_path_info_response_proto__pack
                     (const Hadoop__Hdfs__GetBlockLocalPathInfoResponseProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_block_local_path_info_response_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__hdfs__get_block_local_path_info_response_proto__pack_to_buffer
                     (const Hadoop__Hdfs__GetBlockLocalPathInfoResponseProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_block_local_path_info_response_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Hdfs__GetBlockLocalPathInfoResponseProto *
       hadoop__hdfs__get_block_local_path_info_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Hdfs__GetBlockLocalPathInfoResponseProto *)
     protobuf_c_message_unpack (&hadoop__hdfs__get_block_local_path_info_response_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__hdfs__get_block_local_path_info_response_proto__free_unpacked
                     (Hadoop__Hdfs__GetBlockLocalPathInfoResponseProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_block_local_path_info_response_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__hdfs__get_hdfs_block_locations_request_proto__init
                     (Hadoop__Hdfs__GetHdfsBlockLocationsRequestProto         *message)
{
  static Hadoop__Hdfs__GetHdfsBlockLocationsRequestProto init_value = HADOOP__HDFS__GET_HDFS_BLOCK_LOCATIONS_REQUEST_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__hdfs__get_hdfs_block_locations_request_proto__get_packed_size
                     (const Hadoop__Hdfs__GetHdfsBlockLocationsRequestProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_hdfs_block_locations_request_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__hdfs__get_hdfs_block_locations_request_proto__pack
                     (const Hadoop__Hdfs__GetHdfsBlockLocationsRequestProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_hdfs_block_locations_request_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__hdfs__get_hdfs_block_locations_request_proto__pack_to_buffer
                     (const Hadoop__Hdfs__GetHdfsBlockLocationsRequestProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_hdfs_block_locations_request_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Hdfs__GetHdfsBlockLocationsRequestProto *
       hadoop__hdfs__get_hdfs_block_locations_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Hdfs__GetHdfsBlockLocationsRequestProto *)
     protobuf_c_message_unpack (&hadoop__hdfs__get_hdfs_block_locations_request_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__hdfs__get_hdfs_block_locations_request_proto__free_unpacked
                     (Hadoop__Hdfs__GetHdfsBlockLocationsRequestProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_hdfs_block_locations_request_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__hdfs__get_hdfs_block_locations_response_proto__init
                     (Hadoop__Hdfs__GetHdfsBlockLocationsResponseProto         *message)
{
  static Hadoop__Hdfs__GetHdfsBlockLocationsResponseProto init_value = HADOOP__HDFS__GET_HDFS_BLOCK_LOCATIONS_RESPONSE_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__hdfs__get_hdfs_block_locations_response_proto__get_packed_size
                     (const Hadoop__Hdfs__GetHdfsBlockLocationsResponseProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_hdfs_block_locations_response_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__hdfs__get_hdfs_block_locations_response_proto__pack
                     (const Hadoop__Hdfs__GetHdfsBlockLocationsResponseProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_hdfs_block_locations_response_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__hdfs__get_hdfs_block_locations_response_proto__pack_to_buffer
                     (const Hadoop__Hdfs__GetHdfsBlockLocationsResponseProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_hdfs_block_locations_response_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Hdfs__GetHdfsBlockLocationsResponseProto *
       hadoop__hdfs__get_hdfs_block_locations_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Hdfs__GetHdfsBlockLocationsResponseProto *)
     protobuf_c_message_unpack (&hadoop__hdfs__get_hdfs_block_locations_response_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__hdfs__get_hdfs_block_locations_response_proto__free_unpacked
                     (Hadoop__Hdfs__GetHdfsBlockLocationsResponseProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_hdfs_block_locations_response_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor hadoop__hdfs__get_replica_visible_length_request_proto__field_descriptors[1] =
{
  {
    "block",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__GetReplicaVisibleLengthRequestProto, block),
    &hadoop__hdfs__extended_block_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__hdfs__get_replica_visible_length_request_proto__field_indices_by_name[] = {
  0,   /* field[0] = block */
};
static const ProtobufCIntRange hadoop__hdfs__get_replica_visible_length_request_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor hadoop__hdfs__get_replica_visible_length_request_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.hdfs.GetReplicaVisibleLengthRequestProto",
  "GetReplicaVisibleLengthRequestProto",
  "Hadoop__Hdfs__GetReplicaVisibleLengthRequestProto",
  "hadoop.hdfs",
  sizeof(Hadoop__Hdfs__GetReplicaVisibleLengthRequestProto),
  1,
  hadoop__hdfs__get_replica_visible_length_request_proto__field_descriptors,
  hadoop__hdfs__get_replica_visible_length_request_proto__field_indices_by_name,
  1,  hadoop__hdfs__get_replica_visible_length_request_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__hdfs__get_replica_visible_length_request_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hadoop__hdfs__get_replica_visible_length_response_proto__field_descriptors[1] =
{
  {
    "length",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__GetReplicaVisibleLengthResponseProto, length),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__hdfs__get_replica_visible_length_response_proto__field_indices_by_name[] = {
  0,   /* field[0] = length */
};
static const ProtobufCIntRange hadoop__hdfs__get_replica_visible_length_response_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor hadoop__hdfs__get_replica_visible_length_response_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.hdfs.GetReplicaVisibleLengthResponseProto",
  "GetReplicaVisibleLengthResponseProto",
  "Hadoop__Hdfs__GetReplicaVisibleLengthResponseProto",
  "hadoop.hdfs",
  sizeof(Hadoop__Hdfs__GetReplicaVisibleLengthResponseProto),
  1,
  hadoop__hdfs__get_replica_visible_length_response_proto__field_descriptors,
  hadoop__hdfs__get_replica_visible_length_response_proto__field_indices_by_name,
  1,  hadoop__hdfs__get_replica_visible_length_response_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__hdfs__get_replica_visible_length_response_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define hadoop__hdfs__refresh_namenodes_request_proto__field_descriptors NULL
#define hadoop__hdfs__refresh_namenodes_request_proto__field_indices_by_name NULL
#define hadoop__hdfs__refresh_namenodes_request_proto__number_ranges NULL
const ProtobufCMessageDescriptor hadoop__hdfs__refresh_namenodes_request_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.hdfs.RefreshNamenodesRequestProto",
  "RefreshNamenodesRequestProto",
  "Hadoop__Hdfs__RefreshNamenodesRequestProto",
  "hadoop.hdfs",
  sizeof(Hadoop__Hdfs__RefreshNamenodesRequestProto),
  0,
  hadoop__hdfs__refresh_namenodes_request_proto__field_descriptors,
  hadoop__hdfs__refresh_namenodes_request_proto__field_indices_by_name,
  0,  hadoop__hdfs__refresh_namenodes_request_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__hdfs__refresh_namenodes_request_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define hadoop__hdfs__refresh_namenodes_response_proto__field_descriptors NULL
#define hadoop__hdfs__refresh_namenodes_response_proto__field_indices_by_name NULL
#define hadoop__hdfs__refresh_namenodes_response_proto__number_ranges NULL
const ProtobufCMessageDescriptor hadoop__hdfs__refresh_namenodes_response_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.hdfs.RefreshNamenodesResponseProto",
  "RefreshNamenodesResponseProto",
  "Hadoop__Hdfs__RefreshNamenodesResponseProto",
  "hadoop.hdfs",
  sizeof(Hadoop__Hdfs__RefreshNamenodesResponseProto),
  0,
  hadoop__hdfs__refresh_namenodes_response_proto__field_descriptors,
  hadoop__hdfs__refresh_namenodes_response_proto__field_indices_by_name,
  0,  hadoop__hdfs__refresh_namenodes_response_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__hdfs__refresh_namenodes_response_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hadoop__hdfs__delete_block_pool_request_proto__field_descriptors[2] =
{
  {
    "blockPool",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__DeleteBlockPoolRequestProto, blockpool),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "force",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__DeleteBlockPoolRequestProto, force),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__hdfs__delete_block_pool_request_proto__field_indices_by_name[] = {
  0,   /* field[0] = blockPool */
  1,   /* field[1] = force */
};
static const ProtobufCIntRange hadoop__hdfs__delete_block_pool_request_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor hadoop__hdfs__delete_block_pool_request_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.hdfs.DeleteBlockPoolRequestProto",
  "DeleteBlockPoolRequestProto",
  "Hadoop__Hdfs__DeleteBlockPoolRequestProto",
  "hadoop.hdfs",
  sizeof(Hadoop__Hdfs__DeleteBlockPoolRequestProto),
  2,
  hadoop__hdfs__delete_block_pool_request_proto__field_descriptors,
  hadoop__hdfs__delete_block_pool_request_proto__field_indices_by_name,
  1,  hadoop__hdfs__delete_block_pool_request_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__hdfs__delete_block_pool_request_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define hadoop__hdfs__delete_block_pool_response_proto__field_descriptors NULL
#define hadoop__hdfs__delete_block_pool_response_proto__field_indices_by_name NULL
#define hadoop__hdfs__delete_block_pool_response_proto__number_ranges NULL
const ProtobufCMessageDescriptor hadoop__hdfs__delete_block_pool_response_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.hdfs.DeleteBlockPoolResponseProto",
  "DeleteBlockPoolResponseProto",
  "Hadoop__Hdfs__DeleteBlockPoolResponseProto",
  "hadoop.hdfs",
  sizeof(Hadoop__Hdfs__DeleteBlockPoolResponseProto),
  0,
  hadoop__hdfs__delete_block_pool_response_proto__field_descriptors,
  hadoop__hdfs__delete_block_pool_response_proto__field_indices_by_name,
  0,  hadoop__hdfs__delete_block_pool_response_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__hdfs__delete_block_pool_response_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hadoop__hdfs__get_block_local_path_info_request_proto__field_descriptors[2] =
{
  {
    "block",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__GetBlockLocalPathInfoRequestProto, block),
    &hadoop__hdfs__extended_block_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "token",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__GetBlockLocalPathInfoRequestProto, token),
    &hadoop__common__token_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__hdfs__get_block_local_path_info_request_proto__field_indices_by_name[] = {
  0,   /* field[0] = block */
  1,   /* field[1] = token */
};
static const ProtobufCIntRange hadoop__hdfs__get_block_local_path_info_request_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor hadoop__hdfs__get_block_local_path_info_request_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.hdfs.GetBlockLocalPathInfoRequestProto",
  "GetBlockLocalPathInfoRequestProto",
  "Hadoop__Hdfs__GetBlockLocalPathInfoRequestProto",
  "hadoop.hdfs",
  sizeof(Hadoop__Hdfs__GetBlockLocalPathInfoRequestProto),
  2,
  hadoop__hdfs__get_block_local_path_info_request_proto__field_descriptors,
  hadoop__hdfs__get_block_local_path_info_request_proto__field_indices_by_name,
  1,  hadoop__hdfs__get_block_local_path_info_request_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__hdfs__get_block_local_path_info_request_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hadoop__hdfs__get_block_local_path_info_response_proto__field_descriptors[3] =
{
  {
    "block",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__GetBlockLocalPathInfoResponseProto, block),
    &hadoop__hdfs__extended_block_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "localPath",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__GetBlockLocalPathInfoResponseProto, localpath),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "localMetaPath",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__GetBlockLocalPathInfoResponseProto, localmetapath),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__hdfs__get_block_local_path_info_response_proto__field_indices_by_name[] = {
  0,   /* field[0] = block */
  2,   /* field[2] = localMetaPath */
  1,   /* field[1] = localPath */
};
static const ProtobufCIntRange hadoop__hdfs__get_block_local_path_info_response_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor hadoop__hdfs__get_block_local_path_info_response_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.hdfs.GetBlockLocalPathInfoResponseProto",
  "GetBlockLocalPathInfoResponseProto",
  "Hadoop__Hdfs__GetBlockLocalPathInfoResponseProto",
  "hadoop.hdfs",
  sizeof(Hadoop__Hdfs__GetBlockLocalPathInfoResponseProto),
  3,
  hadoop__hdfs__get_block_local_path_info_response_proto__field_descriptors,
  hadoop__hdfs__get_block_local_path_info_response_proto__field_indices_by_name,
  1,  hadoop__hdfs__get_block_local_path_info_response_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__hdfs__get_block_local_path_info_response_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hadoop__hdfs__get_hdfs_block_locations_request_proto__field_descriptors[2] =
{
  {
    "blocks",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__GetHdfsBlockLocationsRequestProto, n_blocks),
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__GetHdfsBlockLocationsRequestProto, blocks),
    &hadoop__hdfs__extended_block_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tokens",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__GetHdfsBlockLocationsRequestProto, n_tokens),
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__GetHdfsBlockLocationsRequestProto, tokens),
    &hadoop__common__token_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__hdfs__get_hdfs_block_locations_request_proto__field_indices_by_name[] = {
  0,   /* field[0] = blocks */
  1,   /* field[1] = tokens */
};
static const ProtobufCIntRange hadoop__hdfs__get_hdfs_block_locations_request_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor hadoop__hdfs__get_hdfs_block_locations_request_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.hdfs.GetHdfsBlockLocationsRequestProto",
  "GetHdfsBlockLocationsRequestProto",
  "Hadoop__Hdfs__GetHdfsBlockLocationsRequestProto",
  "hadoop.hdfs",
  sizeof(Hadoop__Hdfs__GetHdfsBlockLocationsRequestProto),
  2,
  hadoop__hdfs__get_hdfs_block_locations_request_proto__field_descriptors,
  hadoop__hdfs__get_hdfs_block_locations_request_proto__field_indices_by_name,
  1,  hadoop__hdfs__get_hdfs_block_locations_request_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__hdfs__get_hdfs_block_locations_request_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hadoop__hdfs__get_hdfs_block_locations_response_proto__field_descriptors[2] =
{
  {
    "volumeIds",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__GetHdfsBlockLocationsResponseProto, n_volumeids),
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__GetHdfsBlockLocationsResponseProto, volumeids),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "volumeIndexes",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__GetHdfsBlockLocationsResponseProto, n_volumeindexes),
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__GetHdfsBlockLocationsResponseProto, volumeindexes),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__hdfs__get_hdfs_block_locations_response_proto__field_indices_by_name[] = {
  0,   /* field[0] = volumeIds */
  1,   /* field[1] = volumeIndexes */
};
static const ProtobufCIntRange hadoop__hdfs__get_hdfs_block_locations_response_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor hadoop__hdfs__get_hdfs_block_locations_response_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.hdfs.GetHdfsBlockLocationsResponseProto",
  "GetHdfsBlockLocationsResponseProto",
  "Hadoop__Hdfs__GetHdfsBlockLocationsResponseProto",
  "hadoop.hdfs",
  sizeof(Hadoop__Hdfs__GetHdfsBlockLocationsResponseProto),
  2,
  hadoop__hdfs__get_hdfs_block_locations_response_proto__field_descriptors,
  hadoop__hdfs__get_hdfs_block_locations_response_proto__field_indices_by_name,
  1,  hadoop__hdfs__get_hdfs_block_locations_response_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__hdfs__get_hdfs_block_locations_response_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor hadoop__hdfs__client_datanode_protocol_service__method_descriptors[5] =
{
  { "getReplicaVisibleLength", &hadoop__hdfs__get_replica_visible_length_request_proto__descriptor, &hadoop__hdfs__get_replica_visible_length_response_proto__descriptor },
  { "refreshNamenodes", &hadoop__hdfs__refresh_namenodes_request_proto__descriptor, &hadoop__hdfs__refresh_namenodes_response_proto__descriptor },
  { "deleteBlockPool", &hadoop__hdfs__delete_block_pool_request_proto__descriptor, &hadoop__hdfs__delete_block_pool_response_proto__descriptor },
  { "getBlockLocalPathInfo", &hadoop__hdfs__get_block_local_path_info_request_proto__descriptor, &hadoop__hdfs__get_block_local_path_info_response_proto__descriptor },
  { "getHdfsBlockLocations", &hadoop__hdfs__get_hdfs_block_locations_request_proto__descriptor, &hadoop__hdfs__get_hdfs_block_locations_response_proto__descriptor },
};
const unsigned hadoop__hdfs__client_datanode_protocol_service__method_indices_by_name[] = {
  2,        /* deleteBlockPool */
  3,        /* getBlockLocalPathInfo */
  4,        /* getHdfsBlockLocations */
  0,        /* getReplicaVisibleLength */
  1         /* refreshNamenodes */
};
const ProtobufCServiceDescriptor hadoop__hdfs__client_datanode_protocol_service__descriptor =
{
  PROTOBUF_C_SERVICE_DESCRIPTOR_MAGIC,
  "hadoop.hdfs.ClientDatanodeProtocolService",
  "refreshNamenodes",
  "Hadoop__Hdfs__ClientDatanodeProtocolService",
  "hadoop.hdfs",
  5,
  hadoop__hdfs__client_datanode_protocol_service__method_descriptors,
  hadoop__hdfs__client_datanode_protocol_service__method_indices_by_name
};
void hadoop__hdfs__client_datanode_protocol_service__get_replica_visible_length(ProtobufCService *service,
                                                                                const Hadoop__Hdfs__GetReplicaVisibleLengthRequestProto *input,
                                                                                Hadoop__Hdfs__GetReplicaVisibleLengthResponseProto_Closure closure,
                                                                                void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__hdfs__client_datanode_protocol_service__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__hdfs__client_datanode_protocol_service__refresh_namenodes(ProtobufCService *service,
                                                                       const Hadoop__Hdfs__RefreshNamenodesRequestProto *input,
                                                                       Hadoop__Hdfs__RefreshNamenodesResponseProto_Closure closure,
                                                                       void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__hdfs__client_datanode_protocol_service__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__hdfs__client_datanode_protocol_service__delete_block_pool(ProtobufCService *service,
                                                                       const Hadoop__Hdfs__DeleteBlockPoolRequestProto *input,
                                                                       Hadoop__Hdfs__DeleteBlockPoolResponseProto_Closure closure,
                                                                       void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__hdfs__client_datanode_protocol_service__descriptor);
  service->invoke(service, 2, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__hdfs__client_datanode_protocol_service__get_block_local_path_info(ProtobufCService *service,
                                                                               const Hadoop__Hdfs__GetBlockLocalPathInfoRequestProto *input,
                                                                               Hadoop__Hdfs__GetBlockLocalPathInfoResponseProto_Closure closure,
                                                                               void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__hdfs__client_datanode_protocol_service__descriptor);
  service->invoke(service, 3, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__hdfs__client_datanode_protocol_service__get_hdfs_block_locations(ProtobufCService *service,
                                                                              const Hadoop__Hdfs__GetHdfsBlockLocationsRequestProto *input,
                                                                              Hadoop__Hdfs__GetHdfsBlockLocationsResponseProto_Closure closure,
                                                                              void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__hdfs__client_datanode_protocol_service__descriptor);
  service->invoke(service, 4, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__hdfs__client_datanode_protocol_service__init (Hadoop__Hdfs__ClientDatanodeProtocolService_Service *service,
                                                           Hadoop__Hdfs__ClientDatanodeProtocolService_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &hadoop__hdfs__client_datanode_protocol_service__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
