/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "HAServiceProtocol.pb-c.h"
void   hadoop__common__hastate_change_request_info_proto__init
                     (Hadoop__Common__HAStateChangeRequestInfoProto         *message)
{
  static Hadoop__Common__HAStateChangeRequestInfoProto init_value = HADOOP__COMMON__HASTATE_CHANGE_REQUEST_INFO_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__common__hastate_change_request_info_proto__get_packed_size
                     (const Hadoop__Common__HAStateChangeRequestInfoProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__hastate_change_request_info_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__common__hastate_change_request_info_proto__pack
                     (const Hadoop__Common__HAStateChangeRequestInfoProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__hastate_change_request_info_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__common__hastate_change_request_info_proto__pack_to_buffer
                     (const Hadoop__Common__HAStateChangeRequestInfoProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__hastate_change_request_info_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Common__HAStateChangeRequestInfoProto *
       hadoop__common__hastate_change_request_info_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Common__HAStateChangeRequestInfoProto *)
     protobuf_c_message_unpack (&hadoop__common__hastate_change_request_info_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__common__hastate_change_request_info_proto__free_unpacked
                     (Hadoop__Common__HAStateChangeRequestInfoProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__hastate_change_request_info_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__common__monitor_health_request_proto__init
                     (Hadoop__Common__MonitorHealthRequestProto         *message)
{
  static Hadoop__Common__MonitorHealthRequestProto init_value = HADOOP__COMMON__MONITOR_HEALTH_REQUEST_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__common__monitor_health_request_proto__get_packed_size
                     (const Hadoop__Common__MonitorHealthRequestProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__monitor_health_request_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__common__monitor_health_request_proto__pack
                     (const Hadoop__Common__MonitorHealthRequestProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__monitor_health_request_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__common__monitor_health_request_proto__pack_to_buffer
                     (const Hadoop__Common__MonitorHealthRequestProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__monitor_health_request_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Common__MonitorHealthRequestProto *
       hadoop__common__monitor_health_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Common__MonitorHealthRequestProto *)
     protobuf_c_message_unpack (&hadoop__common__monitor_health_request_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__common__monitor_health_request_proto__free_unpacked
                     (Hadoop__Common__MonitorHealthRequestProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__monitor_health_request_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__common__monitor_health_response_proto__init
                     (Hadoop__Common__MonitorHealthResponseProto         *message)
{
  static Hadoop__Common__MonitorHealthResponseProto init_value = HADOOP__COMMON__MONITOR_HEALTH_RESPONSE_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__common__monitor_health_response_proto__get_packed_size
                     (const Hadoop__Common__MonitorHealthResponseProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__monitor_health_response_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__common__monitor_health_response_proto__pack
                     (const Hadoop__Common__MonitorHealthResponseProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__monitor_health_response_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__common__monitor_health_response_proto__pack_to_buffer
                     (const Hadoop__Common__MonitorHealthResponseProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__monitor_health_response_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Common__MonitorHealthResponseProto *
       hadoop__common__monitor_health_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Common__MonitorHealthResponseProto *)
     protobuf_c_message_unpack (&hadoop__common__monitor_health_response_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__common__monitor_health_response_proto__free_unpacked
                     (Hadoop__Common__MonitorHealthResponseProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__monitor_health_response_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__common__transition_to_active_request_proto__init
                     (Hadoop__Common__TransitionToActiveRequestProto         *message)
{
  static Hadoop__Common__TransitionToActiveRequestProto init_value = HADOOP__COMMON__TRANSITION_TO_ACTIVE_REQUEST_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__common__transition_to_active_request_proto__get_packed_size
                     (const Hadoop__Common__TransitionToActiveRequestProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__transition_to_active_request_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__common__transition_to_active_request_proto__pack
                     (const Hadoop__Common__TransitionToActiveRequestProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__transition_to_active_request_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__common__transition_to_active_request_proto__pack_to_buffer
                     (const Hadoop__Common__TransitionToActiveRequestProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__transition_to_active_request_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Common__TransitionToActiveRequestProto *
       hadoop__common__transition_to_active_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Common__TransitionToActiveRequestProto *)
     protobuf_c_message_unpack (&hadoop__common__transition_to_active_request_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__common__transition_to_active_request_proto__free_unpacked
                     (Hadoop__Common__TransitionToActiveRequestProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__transition_to_active_request_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__common__transition_to_active_response_proto__init
                     (Hadoop__Common__TransitionToActiveResponseProto         *message)
{
  static Hadoop__Common__TransitionToActiveResponseProto init_value = HADOOP__COMMON__TRANSITION_TO_ACTIVE_RESPONSE_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__common__transition_to_active_response_proto__get_packed_size
                     (const Hadoop__Common__TransitionToActiveResponseProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__transition_to_active_response_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__common__transition_to_active_response_proto__pack
                     (const Hadoop__Common__TransitionToActiveResponseProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__transition_to_active_response_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__common__transition_to_active_response_proto__pack_to_buffer
                     (const Hadoop__Common__TransitionToActiveResponseProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__transition_to_active_response_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Common__TransitionToActiveResponseProto *
       hadoop__common__transition_to_active_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Common__TransitionToActiveResponseProto *)
     protobuf_c_message_unpack (&hadoop__common__transition_to_active_response_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__common__transition_to_active_response_proto__free_unpacked
                     (Hadoop__Common__TransitionToActiveResponseProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__transition_to_active_response_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__common__transition_to_standby_request_proto__init
                     (Hadoop__Common__TransitionToStandbyRequestProto         *message)
{
  static Hadoop__Common__TransitionToStandbyRequestProto init_value = HADOOP__COMMON__TRANSITION_TO_STANDBY_REQUEST_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__common__transition_to_standby_request_proto__get_packed_size
                     (const Hadoop__Common__TransitionToStandbyRequestProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__transition_to_standby_request_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__common__transition_to_standby_request_proto__pack
                     (const Hadoop__Common__TransitionToStandbyRequestProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__transition_to_standby_request_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__common__transition_to_standby_request_proto__pack_to_buffer
                     (const Hadoop__Common__TransitionToStandbyRequestProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__transition_to_standby_request_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Common__TransitionToStandbyRequestProto *
       hadoop__common__transition_to_standby_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Common__TransitionToStandbyRequestProto *)
     protobuf_c_message_unpack (&hadoop__common__transition_to_standby_request_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__common__transition_to_standby_request_proto__free_unpacked
                     (Hadoop__Common__TransitionToStandbyRequestProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__transition_to_standby_request_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__common__transition_to_standby_response_proto__init
                     (Hadoop__Common__TransitionToStandbyResponseProto         *message)
{
  static Hadoop__Common__TransitionToStandbyResponseProto init_value = HADOOP__COMMON__TRANSITION_TO_STANDBY_RESPONSE_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__common__transition_to_standby_response_proto__get_packed_size
                     (const Hadoop__Common__TransitionToStandbyResponseProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__transition_to_standby_response_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__common__transition_to_standby_response_proto__pack
                     (const Hadoop__Common__TransitionToStandbyResponseProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__transition_to_standby_response_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__common__transition_to_standby_response_proto__pack_to_buffer
                     (const Hadoop__Common__TransitionToStandbyResponseProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__transition_to_standby_response_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Common__TransitionToStandbyResponseProto *
       hadoop__common__transition_to_standby_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Common__TransitionToStandbyResponseProto *)
     protobuf_c_message_unpack (&hadoop__common__transition_to_standby_response_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__common__transition_to_standby_response_proto__free_unpacked
                     (Hadoop__Common__TransitionToStandbyResponseProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__transition_to_standby_response_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__common__get_service_status_request_proto__init
                     (Hadoop__Common__GetServiceStatusRequestProto         *message)
{
  static Hadoop__Common__GetServiceStatusRequestProto init_value = HADOOP__COMMON__GET_SERVICE_STATUS_REQUEST_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__common__get_service_status_request_proto__get_packed_size
                     (const Hadoop__Common__GetServiceStatusRequestProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__get_service_status_request_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__common__get_service_status_request_proto__pack
                     (const Hadoop__Common__GetServiceStatusRequestProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__get_service_status_request_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__common__get_service_status_request_proto__pack_to_buffer
                     (const Hadoop__Common__GetServiceStatusRequestProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__get_service_status_request_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Common__GetServiceStatusRequestProto *
       hadoop__common__get_service_status_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Common__GetServiceStatusRequestProto *)
     protobuf_c_message_unpack (&hadoop__common__get_service_status_request_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__common__get_service_status_request_proto__free_unpacked
                     (Hadoop__Common__GetServiceStatusRequestProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__get_service_status_request_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__common__get_service_status_response_proto__init
                     (Hadoop__Common__GetServiceStatusResponseProto         *message)
{
  static Hadoop__Common__GetServiceStatusResponseProto init_value = HADOOP__COMMON__GET_SERVICE_STATUS_RESPONSE_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__common__get_service_status_response_proto__get_packed_size
                     (const Hadoop__Common__GetServiceStatusResponseProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__get_service_status_response_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__common__get_service_status_response_proto__pack
                     (const Hadoop__Common__GetServiceStatusResponseProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__get_service_status_response_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__common__get_service_status_response_proto__pack_to_buffer
                     (const Hadoop__Common__GetServiceStatusResponseProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__get_service_status_response_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Common__GetServiceStatusResponseProto *
       hadoop__common__get_service_status_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Common__GetServiceStatusResponseProto *)
     protobuf_c_message_unpack (&hadoop__common__get_service_status_response_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__common__get_service_status_response_proto__free_unpacked
                     (Hadoop__Common__GetServiceStatusResponseProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__get_service_status_response_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor hadoop__common__hastate_change_request_info_proto__field_descriptors[1] =
{
  {
    "reqSource",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Common__HAStateChangeRequestInfoProto, reqsource),
    &hadoop__common__harequest_source__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__common__hastate_change_request_info_proto__field_indices_by_name[] = {
  0,   /* field[0] = reqSource */
};
static const ProtobufCIntRange hadoop__common__hastate_change_request_info_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor hadoop__common__hastate_change_request_info_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.common.HAStateChangeRequestInfoProto",
  "HAStateChangeRequestInfoProto",
  "Hadoop__Common__HAStateChangeRequestInfoProto",
  "hadoop.common",
  sizeof(Hadoop__Common__HAStateChangeRequestInfoProto),
  1,
  hadoop__common__hastate_change_request_info_proto__field_descriptors,
  hadoop__common__hastate_change_request_info_proto__field_indices_by_name,
  1,  hadoop__common__hastate_change_request_info_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__common__hastate_change_request_info_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define hadoop__common__monitor_health_request_proto__field_descriptors NULL
#define hadoop__common__monitor_health_request_proto__field_indices_by_name NULL
#define hadoop__common__monitor_health_request_proto__number_ranges NULL
const ProtobufCMessageDescriptor hadoop__common__monitor_health_request_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.common.MonitorHealthRequestProto",
  "MonitorHealthRequestProto",
  "Hadoop__Common__MonitorHealthRequestProto",
  "hadoop.common",
  sizeof(Hadoop__Common__MonitorHealthRequestProto),
  0,
  hadoop__common__monitor_health_request_proto__field_descriptors,
  hadoop__common__monitor_health_request_proto__field_indices_by_name,
  0,  hadoop__common__monitor_health_request_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__common__monitor_health_request_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define hadoop__common__monitor_health_response_proto__field_descriptors NULL
#define hadoop__common__monitor_health_response_proto__field_indices_by_name NULL
#define hadoop__common__monitor_health_response_proto__number_ranges NULL
const ProtobufCMessageDescriptor hadoop__common__monitor_health_response_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.common.MonitorHealthResponseProto",
  "MonitorHealthResponseProto",
  "Hadoop__Common__MonitorHealthResponseProto",
  "hadoop.common",
  sizeof(Hadoop__Common__MonitorHealthResponseProto),
  0,
  hadoop__common__monitor_health_response_proto__field_descriptors,
  hadoop__common__monitor_health_response_proto__field_indices_by_name,
  0,  hadoop__common__monitor_health_response_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__common__monitor_health_response_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hadoop__common__transition_to_active_request_proto__field_descriptors[1] =
{
  {
    "reqInfo",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Common__TransitionToActiveRequestProto, reqinfo),
    &hadoop__common__hastate_change_request_info_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__common__transition_to_active_request_proto__field_indices_by_name[] = {
  0,   /* field[0] = reqInfo */
};
static const ProtobufCIntRange hadoop__common__transition_to_active_request_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor hadoop__common__transition_to_active_request_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.common.TransitionToActiveRequestProto",
  "TransitionToActiveRequestProto",
  "Hadoop__Common__TransitionToActiveRequestProto",
  "hadoop.common",
  sizeof(Hadoop__Common__TransitionToActiveRequestProto),
  1,
  hadoop__common__transition_to_active_request_proto__field_descriptors,
  hadoop__common__transition_to_active_request_proto__field_indices_by_name,
  1,  hadoop__common__transition_to_active_request_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__common__transition_to_active_request_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define hadoop__common__transition_to_active_response_proto__field_descriptors NULL
#define hadoop__common__transition_to_active_response_proto__field_indices_by_name NULL
#define hadoop__common__transition_to_active_response_proto__number_ranges NULL
const ProtobufCMessageDescriptor hadoop__common__transition_to_active_response_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.common.TransitionToActiveResponseProto",
  "TransitionToActiveResponseProto",
  "Hadoop__Common__TransitionToActiveResponseProto",
  "hadoop.common",
  sizeof(Hadoop__Common__TransitionToActiveResponseProto),
  0,
  hadoop__common__transition_to_active_response_proto__field_descriptors,
  hadoop__common__transition_to_active_response_proto__field_indices_by_name,
  0,  hadoop__common__transition_to_active_response_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__common__transition_to_active_response_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hadoop__common__transition_to_standby_request_proto__field_descriptors[1] =
{
  {
    "reqInfo",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Common__TransitionToStandbyRequestProto, reqinfo),
    &hadoop__common__hastate_change_request_info_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__common__transition_to_standby_request_proto__field_indices_by_name[] = {
  0,   /* field[0] = reqInfo */
};
static const ProtobufCIntRange hadoop__common__transition_to_standby_request_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor hadoop__common__transition_to_standby_request_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.common.TransitionToStandbyRequestProto",
  "TransitionToStandbyRequestProto",
  "Hadoop__Common__TransitionToStandbyRequestProto",
  "hadoop.common",
  sizeof(Hadoop__Common__TransitionToStandbyRequestProto),
  1,
  hadoop__common__transition_to_standby_request_proto__field_descriptors,
  hadoop__common__transition_to_standby_request_proto__field_indices_by_name,
  1,  hadoop__common__transition_to_standby_request_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__common__transition_to_standby_request_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define hadoop__common__transition_to_standby_response_proto__field_descriptors NULL
#define hadoop__common__transition_to_standby_response_proto__field_indices_by_name NULL
#define hadoop__common__transition_to_standby_response_proto__number_ranges NULL
const ProtobufCMessageDescriptor hadoop__common__transition_to_standby_response_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.common.TransitionToStandbyResponseProto",
  "TransitionToStandbyResponseProto",
  "Hadoop__Common__TransitionToStandbyResponseProto",
  "hadoop.common",
  sizeof(Hadoop__Common__TransitionToStandbyResponseProto),
  0,
  hadoop__common__transition_to_standby_response_proto__field_descriptors,
  hadoop__common__transition_to_standby_response_proto__field_indices_by_name,
  0,  hadoop__common__transition_to_standby_response_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__common__transition_to_standby_response_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define hadoop__common__get_service_status_request_proto__field_descriptors NULL
#define hadoop__common__get_service_status_request_proto__field_indices_by_name NULL
#define hadoop__common__get_service_status_request_proto__number_ranges NULL
const ProtobufCMessageDescriptor hadoop__common__get_service_status_request_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.common.GetServiceStatusRequestProto",
  "GetServiceStatusRequestProto",
  "Hadoop__Common__GetServiceStatusRequestProto",
  "hadoop.common",
  sizeof(Hadoop__Common__GetServiceStatusRequestProto),
  0,
  hadoop__common__get_service_status_request_proto__field_descriptors,
  hadoop__common__get_service_status_request_proto__field_indices_by_name,
  0,  hadoop__common__get_service_status_request_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__common__get_service_status_request_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hadoop__common__get_service_status_response_proto__field_descriptors[3] =
{
  {
    "state",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Common__GetServiceStatusResponseProto, state),
    &hadoop__common__haservice_state_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "readyToBecomeActive",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(Hadoop__Common__GetServiceStatusResponseProto, has_readytobecomeactive),
    PROTOBUF_C_OFFSETOF(Hadoop__Common__GetServiceStatusResponseProto, readytobecomeactive),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "notReadyReason",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Common__GetServiceStatusResponseProto, notreadyreason),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__common__get_service_status_response_proto__field_indices_by_name[] = {
  2,   /* field[2] = notReadyReason */
  1,   /* field[1] = readyToBecomeActive */
  0,   /* field[0] = state */
};
static const ProtobufCIntRange hadoop__common__get_service_status_response_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor hadoop__common__get_service_status_response_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.common.GetServiceStatusResponseProto",
  "GetServiceStatusResponseProto",
  "Hadoop__Common__GetServiceStatusResponseProto",
  "hadoop.common",
  sizeof(Hadoop__Common__GetServiceStatusResponseProto),
  3,
  hadoop__common__get_service_status_response_proto__field_descriptors,
  hadoop__common__get_service_status_response_proto__field_indices_by_name,
  1,  hadoop__common__get_service_status_response_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__common__get_service_status_response_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue hadoop__common__haservice_state_proto__enum_values_by_number[3] =
{
  { "INITIALIZING", "HADOOP__COMMON__HASERVICE_STATE_PROTO__INITIALIZING", 0 },
  { "ACTIVE", "HADOOP__COMMON__HASERVICE_STATE_PROTO__ACTIVE", 1 },
  { "STANDBY", "HADOOP__COMMON__HASERVICE_STATE_PROTO__STANDBY", 2 },
};
static const ProtobufCIntRange hadoop__common__haservice_state_proto__value_ranges[] = {
{0, 0},{0, 3}
};
const ProtobufCEnumValueIndex hadoop__common__haservice_state_proto__enum_values_by_name[3] =
{
  { "ACTIVE", 1 },
  { "INITIALIZING", 0 },
  { "STANDBY", 2 },
};
const ProtobufCEnumDescriptor hadoop__common__haservice_state_proto__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "hadoop.common.HAServiceStateProto",
  "HAServiceStateProto",
  "Hadoop__Common__HAServiceStateProto",
  "hadoop.common",
  3,
  hadoop__common__haservice_state_proto__enum_values_by_number,
  3,
  hadoop__common__haservice_state_proto__enum_values_by_name,
  1,
  hadoop__common__haservice_state_proto__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
const ProtobufCEnumValue hadoop__common__harequest_source__enum_values_by_number[3] =
{
  { "REQUEST_BY_USER", "HADOOP__COMMON__HAREQUEST_SOURCE__REQUEST_BY_USER", 0 },
  { "REQUEST_BY_USER_FORCED", "HADOOP__COMMON__HAREQUEST_SOURCE__REQUEST_BY_USER_FORCED", 1 },
  { "REQUEST_BY_ZKFC", "HADOOP__COMMON__HAREQUEST_SOURCE__REQUEST_BY_ZKFC", 2 },
};
static const ProtobufCIntRange hadoop__common__harequest_source__value_ranges[] = {
{0, 0},{0, 3}
};
const ProtobufCEnumValueIndex hadoop__common__harequest_source__enum_values_by_name[3] =
{
  { "REQUEST_BY_USER", 0 },
  { "REQUEST_BY_USER_FORCED", 1 },
  { "REQUEST_BY_ZKFC", 2 },
};
const ProtobufCEnumDescriptor hadoop__common__harequest_source__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "hadoop.common.HARequestSource",
  "HARequestSource",
  "Hadoop__Common__HARequestSource",
  "hadoop.common",
  3,
  hadoop__common__harequest_source__enum_values_by_number,
  3,
  hadoop__common__harequest_source__enum_values_by_name,
  1,
  hadoop__common__harequest_source__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCMethodDescriptor hadoop__common__haservice_protocol_service__method_descriptors[4] =
{
  { "monitorHealth", &hadoop__common__monitor_health_request_proto__descriptor, &hadoop__common__monitor_health_response_proto__descriptor },
  { "transitionToActive", &hadoop__common__transition_to_active_request_proto__descriptor, &hadoop__common__transition_to_active_response_proto__descriptor },
  { "transitionToStandby", &hadoop__common__transition_to_standby_request_proto__descriptor, &hadoop__common__transition_to_standby_response_proto__descriptor },
  { "getServiceStatus", &hadoop__common__get_service_status_request_proto__descriptor, &hadoop__common__get_service_status_response_proto__descriptor },
};
const unsigned hadoop__common__haservice_protocol_service__method_indices_by_name[] = {
  3,        /* getServiceStatus */
  0,        /* monitorHealth */
  1,        /* transitionToActive */
  2         /* transitionToStandby */
};
const ProtobufCServiceDescriptor hadoop__common__haservice_protocol_service__descriptor =
{
  PROTOBUF_C_SERVICE_DESCRIPTOR_MAGIC,
  "hadoop.common.HAServiceProtocolService",
  "transitionToStandby",
  "Hadoop__Common__HAServiceProtocolService",
  "hadoop.common",
  4,
  hadoop__common__haservice_protocol_service__method_descriptors,
  hadoop__common__haservice_protocol_service__method_indices_by_name
};
void hadoop__common__haservice_protocol_service__monitor_health(ProtobufCService *service,
                                                                const Hadoop__Common__MonitorHealthRequestProto *input,
                                                                Hadoop__Common__MonitorHealthResponseProto_Closure closure,
                                                                void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__common__haservice_protocol_service__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__common__haservice_protocol_service__transition_to_active(ProtobufCService *service,
                                                                      const Hadoop__Common__TransitionToActiveRequestProto *input,
                                                                      Hadoop__Common__TransitionToActiveResponseProto_Closure closure,
                                                                      void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__common__haservice_protocol_service__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__common__haservice_protocol_service__transition_to_standby(ProtobufCService *service,
                                                                       const Hadoop__Common__TransitionToStandbyRequestProto *input,
                                                                       Hadoop__Common__TransitionToStandbyResponseProto_Closure closure,
                                                                       void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__common__haservice_protocol_service__descriptor);
  service->invoke(service, 2, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__common__haservice_protocol_service__get_service_status(ProtobufCService *service,
                                                                    const Hadoop__Common__GetServiceStatusRequestProto *input,
                                                                    Hadoop__Common__GetServiceStatusResponseProto_Closure closure,
                                                                    void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__common__haservice_protocol_service__descriptor);
  service->invoke(service, 3, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__common__haservice_protocol_service__init (Hadoop__Common__HAServiceProtocolService_Service *service,
                                                       Hadoop__Common__HAServiceProtocolService_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &hadoop__common__haservice_protocol_service__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
