/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "HAZKInfo.pb-c.h"
void   hadoop__hdfs__active_node_info__init
                     (Hadoop__Hdfs__ActiveNodeInfo         *message)
{
  static Hadoop__Hdfs__ActiveNodeInfo init_value = HADOOP__HDFS__ACTIVE_NODE_INFO__INIT;
  *message = init_value;
}
size_t hadoop__hdfs__active_node_info__get_packed_size
                     (const Hadoop__Hdfs__ActiveNodeInfo *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__active_node_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__hdfs__active_node_info__pack
                     (const Hadoop__Hdfs__ActiveNodeInfo *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__active_node_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__hdfs__active_node_info__pack_to_buffer
                     (const Hadoop__Hdfs__ActiveNodeInfo *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__active_node_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Hdfs__ActiveNodeInfo *
       hadoop__hdfs__active_node_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Hdfs__ActiveNodeInfo *)
     protobuf_c_message_unpack (&hadoop__hdfs__active_node_info__descriptor,
                                allocator, len, data);
}
void   hadoop__hdfs__active_node_info__free_unpacked
                     (Hadoop__Hdfs__ActiveNodeInfo *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__active_node_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor hadoop__hdfs__active_node_info__field_descriptors[5] =
{
  {
    "nameserviceId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__ActiveNodeInfo, nameserviceid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "namenodeId",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__ActiveNodeInfo, namenodeid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hostname",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__ActiveNodeInfo, hostname),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__ActiveNodeInfo, port),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "zkfcPort",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__ActiveNodeInfo, zkfcport),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__hdfs__active_node_info__field_indices_by_name[] = {
  2,   /* field[2] = hostname */
  1,   /* field[1] = namenodeId */
  0,   /* field[0] = nameserviceId */
  3,   /* field[3] = port */
  4,   /* field[4] = zkfcPort */
};
static const ProtobufCIntRange hadoop__hdfs__active_node_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor hadoop__hdfs__active_node_info__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.hdfs.ActiveNodeInfo",
  "ActiveNodeInfo",
  "Hadoop__Hdfs__ActiveNodeInfo",
  "hadoop.hdfs",
  sizeof(Hadoop__Hdfs__ActiveNodeInfo),
  5,
  hadoop__hdfs__active_node_info__field_descriptors,
  hadoop__hdfs__active_node_info__field_indices_by_name,
  1,  hadoop__hdfs__active_node_info__number_ranges,
  (ProtobufCMessageInit) hadoop__hdfs__active_node_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
