/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "InterDatanodeProtocol.pb-c.h"
void   hadoop__hdfs__init_replica_recovery_request_proto__init
                     (Hadoop__Hdfs__InitReplicaRecoveryRequestProto         *message)
{
  static Hadoop__Hdfs__InitReplicaRecoveryRequestProto init_value = HADOOP__HDFS__INIT_REPLICA_RECOVERY_REQUEST_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__hdfs__init_replica_recovery_request_proto__get_packed_size
                     (const Hadoop__Hdfs__InitReplicaRecoveryRequestProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__init_replica_recovery_request_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__hdfs__init_replica_recovery_request_proto__pack
                     (const Hadoop__Hdfs__InitReplicaRecoveryRequestProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__init_replica_recovery_request_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__hdfs__init_replica_recovery_request_proto__pack_to_buffer
                     (const Hadoop__Hdfs__InitReplicaRecoveryRequestProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__init_replica_recovery_request_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Hdfs__InitReplicaRecoveryRequestProto *
       hadoop__hdfs__init_replica_recovery_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Hdfs__InitReplicaRecoveryRequestProto *)
     protobuf_c_message_unpack (&hadoop__hdfs__init_replica_recovery_request_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__hdfs__init_replica_recovery_request_proto__free_unpacked
                     (Hadoop__Hdfs__InitReplicaRecoveryRequestProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__init_replica_recovery_request_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__hdfs__init_replica_recovery_response_proto__init
                     (Hadoop__Hdfs__InitReplicaRecoveryResponseProto         *message)
{
  static Hadoop__Hdfs__InitReplicaRecoveryResponseProto init_value = HADOOP__HDFS__INIT_REPLICA_RECOVERY_RESPONSE_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__hdfs__init_replica_recovery_response_proto__get_packed_size
                     (const Hadoop__Hdfs__InitReplicaRecoveryResponseProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__init_replica_recovery_response_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__hdfs__init_replica_recovery_response_proto__pack
                     (const Hadoop__Hdfs__InitReplicaRecoveryResponseProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__init_replica_recovery_response_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__hdfs__init_replica_recovery_response_proto__pack_to_buffer
                     (const Hadoop__Hdfs__InitReplicaRecoveryResponseProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__init_replica_recovery_response_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Hdfs__InitReplicaRecoveryResponseProto *
       hadoop__hdfs__init_replica_recovery_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Hdfs__InitReplicaRecoveryResponseProto *)
     protobuf_c_message_unpack (&hadoop__hdfs__init_replica_recovery_response_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__hdfs__init_replica_recovery_response_proto__free_unpacked
                     (Hadoop__Hdfs__InitReplicaRecoveryResponseProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__init_replica_recovery_response_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__hdfs__update_replica_under_recovery_request_proto__init
                     (Hadoop__Hdfs__UpdateReplicaUnderRecoveryRequestProto         *message)
{
  static Hadoop__Hdfs__UpdateReplicaUnderRecoveryRequestProto init_value = HADOOP__HDFS__UPDATE_REPLICA_UNDER_RECOVERY_REQUEST_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__hdfs__update_replica_under_recovery_request_proto__get_packed_size
                     (const Hadoop__Hdfs__UpdateReplicaUnderRecoveryRequestProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__update_replica_under_recovery_request_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__hdfs__update_replica_under_recovery_request_proto__pack
                     (const Hadoop__Hdfs__UpdateReplicaUnderRecoveryRequestProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__update_replica_under_recovery_request_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__hdfs__update_replica_under_recovery_request_proto__pack_to_buffer
                     (const Hadoop__Hdfs__UpdateReplicaUnderRecoveryRequestProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__update_replica_under_recovery_request_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Hdfs__UpdateReplicaUnderRecoveryRequestProto *
       hadoop__hdfs__update_replica_under_recovery_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Hdfs__UpdateReplicaUnderRecoveryRequestProto *)
     protobuf_c_message_unpack (&hadoop__hdfs__update_replica_under_recovery_request_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__hdfs__update_replica_under_recovery_request_proto__free_unpacked
                     (Hadoop__Hdfs__UpdateReplicaUnderRecoveryRequestProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__update_replica_under_recovery_request_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__hdfs__update_replica_under_recovery_response_proto__init
                     (Hadoop__Hdfs__UpdateReplicaUnderRecoveryResponseProto         *message)
{
  static Hadoop__Hdfs__UpdateReplicaUnderRecoveryResponseProto init_value = HADOOP__HDFS__UPDATE_REPLICA_UNDER_RECOVERY_RESPONSE_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__hdfs__update_replica_under_recovery_response_proto__get_packed_size
                     (const Hadoop__Hdfs__UpdateReplicaUnderRecoveryResponseProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__update_replica_under_recovery_response_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__hdfs__update_replica_under_recovery_response_proto__pack
                     (const Hadoop__Hdfs__UpdateReplicaUnderRecoveryResponseProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__update_replica_under_recovery_response_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__hdfs__update_replica_under_recovery_response_proto__pack_to_buffer
                     (const Hadoop__Hdfs__UpdateReplicaUnderRecoveryResponseProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__update_replica_under_recovery_response_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Hdfs__UpdateReplicaUnderRecoveryResponseProto *
       hadoop__hdfs__update_replica_under_recovery_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Hdfs__UpdateReplicaUnderRecoveryResponseProto *)
     protobuf_c_message_unpack (&hadoop__hdfs__update_replica_under_recovery_response_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__hdfs__update_replica_under_recovery_response_proto__free_unpacked
                     (Hadoop__Hdfs__UpdateReplicaUnderRecoveryResponseProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__update_replica_under_recovery_response_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor hadoop__hdfs__init_replica_recovery_request_proto__field_descriptors[1] =
{
  {
    "block",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__InitReplicaRecoveryRequestProto, block),
    &hadoop__hdfs__recovering_block_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__hdfs__init_replica_recovery_request_proto__field_indices_by_name[] = {
  0,   /* field[0] = block */
};
static const ProtobufCIntRange hadoop__hdfs__init_replica_recovery_request_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor hadoop__hdfs__init_replica_recovery_request_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.hdfs.InitReplicaRecoveryRequestProto",
  "InitReplicaRecoveryRequestProto",
  "Hadoop__Hdfs__InitReplicaRecoveryRequestProto",
  "hadoop.hdfs",
  sizeof(Hadoop__Hdfs__InitReplicaRecoveryRequestProto),
  1,
  hadoop__hdfs__init_replica_recovery_request_proto__field_descriptors,
  hadoop__hdfs__init_replica_recovery_request_proto__field_indices_by_name,
  1,  hadoop__hdfs__init_replica_recovery_request_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__hdfs__init_replica_recovery_request_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hadoop__hdfs__init_replica_recovery_response_proto__field_descriptors[3] =
{
  {
    "replicaFound",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__InitReplicaRecoveryResponseProto, replicafound),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__InitReplicaRecoveryResponseProto, has_state),
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__InitReplicaRecoveryResponseProto, state),
    &hadoop__hdfs__replica_state_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "block",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__InitReplicaRecoveryResponseProto, block),
    &hadoop__hdfs__block_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__hdfs__init_replica_recovery_response_proto__field_indices_by_name[] = {
  2,   /* field[2] = block */
  0,   /* field[0] = replicaFound */
  1,   /* field[1] = state */
};
static const ProtobufCIntRange hadoop__hdfs__init_replica_recovery_response_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor hadoop__hdfs__init_replica_recovery_response_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.hdfs.InitReplicaRecoveryResponseProto",
  "InitReplicaRecoveryResponseProto",
  "Hadoop__Hdfs__InitReplicaRecoveryResponseProto",
  "hadoop.hdfs",
  sizeof(Hadoop__Hdfs__InitReplicaRecoveryResponseProto),
  3,
  hadoop__hdfs__init_replica_recovery_response_proto__field_descriptors,
  hadoop__hdfs__init_replica_recovery_response_proto__field_indices_by_name,
  1,  hadoop__hdfs__init_replica_recovery_response_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__hdfs__init_replica_recovery_response_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hadoop__hdfs__update_replica_under_recovery_request_proto__field_descriptors[3] =
{
  {
    "block",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__UpdateReplicaUnderRecoveryRequestProto, block),
    &hadoop__hdfs__extended_block_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "recoveryId",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__UpdateReplicaUnderRecoveryRequestProto, recoveryid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "newLength",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__UpdateReplicaUnderRecoveryRequestProto, newlength),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__hdfs__update_replica_under_recovery_request_proto__field_indices_by_name[] = {
  0,   /* field[0] = block */
  2,   /* field[2] = newLength */
  1,   /* field[1] = recoveryId */
};
static const ProtobufCIntRange hadoop__hdfs__update_replica_under_recovery_request_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor hadoop__hdfs__update_replica_under_recovery_request_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.hdfs.UpdateReplicaUnderRecoveryRequestProto",
  "UpdateReplicaUnderRecoveryRequestProto",
  "Hadoop__Hdfs__UpdateReplicaUnderRecoveryRequestProto",
  "hadoop.hdfs",
  sizeof(Hadoop__Hdfs__UpdateReplicaUnderRecoveryRequestProto),
  3,
  hadoop__hdfs__update_replica_under_recovery_request_proto__field_descriptors,
  hadoop__hdfs__update_replica_under_recovery_request_proto__field_indices_by_name,
  1,  hadoop__hdfs__update_replica_under_recovery_request_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__hdfs__update_replica_under_recovery_request_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hadoop__hdfs__update_replica_under_recovery_response_proto__field_descriptors[1] =
{
  {
    "storageID",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__UpdateReplicaUnderRecoveryResponseProto, storageid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__hdfs__update_replica_under_recovery_response_proto__field_indices_by_name[] = {
  0,   /* field[0] = storageID */
};
static const ProtobufCIntRange hadoop__hdfs__update_replica_under_recovery_response_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor hadoop__hdfs__update_replica_under_recovery_response_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.hdfs.UpdateReplicaUnderRecoveryResponseProto",
  "UpdateReplicaUnderRecoveryResponseProto",
  "Hadoop__Hdfs__UpdateReplicaUnderRecoveryResponseProto",
  "hadoop.hdfs",
  sizeof(Hadoop__Hdfs__UpdateReplicaUnderRecoveryResponseProto),
  1,
  hadoop__hdfs__update_replica_under_recovery_response_proto__field_descriptors,
  hadoop__hdfs__update_replica_under_recovery_response_proto__field_indices_by_name,
  1,  hadoop__hdfs__update_replica_under_recovery_response_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__hdfs__update_replica_under_recovery_response_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor hadoop__hdfs__inter_datanode_protocol_service__method_descriptors[2] =
{
  { "initReplicaRecovery", &hadoop__hdfs__init_replica_recovery_request_proto__descriptor, &hadoop__hdfs__init_replica_recovery_response_proto__descriptor },
  { "updateReplicaUnderRecovery", &hadoop__hdfs__update_replica_under_recovery_request_proto__descriptor, &hadoop__hdfs__update_replica_under_recovery_response_proto__descriptor },
};
const unsigned hadoop__hdfs__inter_datanode_protocol_service__method_indices_by_name[] = {
  0,        /* initReplicaRecovery */
  1         /* updateReplicaUnderRecovery */
};
const ProtobufCServiceDescriptor hadoop__hdfs__inter_datanode_protocol_service__descriptor =
{
  PROTOBUF_C_SERVICE_DESCRIPTOR_MAGIC,
  "hadoop.hdfs.InterDatanodeProtocolService",
  "updateReplicaUnderRecovery",
  "Hadoop__Hdfs__InterDatanodeProtocolService",
  "hadoop.hdfs",
  2,
  hadoop__hdfs__inter_datanode_protocol_service__method_descriptors,
  hadoop__hdfs__inter_datanode_protocol_service__method_indices_by_name
};
void hadoop__hdfs__inter_datanode_protocol_service__init_replica_recovery(ProtobufCService *service,
                                                                          const Hadoop__Hdfs__InitReplicaRecoveryRequestProto *input,
                                                                          Hadoop__Hdfs__InitReplicaRecoveryResponseProto_Closure closure,
                                                                          void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__hdfs__inter_datanode_protocol_service__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__hdfs__inter_datanode_protocol_service__update_replica_under_recovery(ProtobufCService *service,
                                                                                  const Hadoop__Hdfs__UpdateReplicaUnderRecoveryRequestProto *input,
                                                                                  Hadoop__Hdfs__UpdateReplicaUnderRecoveryResponseProto_Closure closure,
                                                                                  void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__hdfs__inter_datanode_protocol_service__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__hdfs__inter_datanode_protocol_service__init (Hadoop__Hdfs__InterDatanodeProtocolService_Service *service,
                                                          Hadoop__Hdfs__InterDatanodeProtocolService_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &hadoop__hdfs__inter_datanode_protocol_service__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
