/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "MRClientProtocol.pb-c.h"
static const ProtobufCMethodDescriptor hadoop__mapreduce__mrclient_protocol_service__method_descriptors[14] =
{
  { "getJobReport", &hadoop__mapreduce__get_job_report_request_proto__descriptor, &hadoop__mapreduce__get_job_report_response_proto__descriptor },
  { "getTaskReport", &hadoop__mapreduce__get_task_report_request_proto__descriptor, &hadoop__mapreduce__get_task_report_response_proto__descriptor },
  { "getTaskAttemptReport", &hadoop__mapreduce__get_task_attempt_report_request_proto__descriptor, &hadoop__mapreduce__get_task_attempt_report_response_proto__descriptor },
  { "getCounters", &hadoop__mapreduce__get_counters_request_proto__descriptor, &hadoop__mapreduce__get_counters_response_proto__descriptor },
  { "getTaskAttemptCompletionEvents", &hadoop__mapreduce__get_task_attempt_completion_events_request_proto__descriptor, &hadoop__mapreduce__get_task_attempt_completion_events_response_proto__descriptor },
  { "getTaskReports", &hadoop__mapreduce__get_task_reports_request_proto__descriptor, &hadoop__mapreduce__get_task_reports_response_proto__descriptor },
  { "getDiagnostics", &hadoop__mapreduce__get_diagnostics_request_proto__descriptor, &hadoop__mapreduce__get_diagnostics_response_proto__descriptor },
  { "getDelegationToken", &hadoop__common__get_delegation_token_request_proto__descriptor, &hadoop__common__get_delegation_token_response_proto__descriptor },
  { "killJob", &hadoop__mapreduce__kill_job_request_proto__descriptor, &hadoop__mapreduce__kill_job_response_proto__descriptor },
  { "killTask", &hadoop__mapreduce__kill_task_request_proto__descriptor, &hadoop__mapreduce__kill_task_response_proto__descriptor },
  { "killTaskAttempt", &hadoop__mapreduce__kill_task_attempt_request_proto__descriptor, &hadoop__mapreduce__kill_task_attempt_response_proto__descriptor },
  { "failTaskAttempt", &hadoop__mapreduce__fail_task_attempt_request_proto__descriptor, &hadoop__mapreduce__fail_task_attempt_response_proto__descriptor },
  { "renewDelegationToken", &hadoop__common__renew_delegation_token_request_proto__descriptor, &hadoop__common__renew_delegation_token_response_proto__descriptor },
  { "cancelDelegationToken", &hadoop__common__cancel_delegation_token_request_proto__descriptor, &hadoop__common__cancel_delegation_token_response_proto__descriptor },
};
const unsigned hadoop__mapreduce__mrclient_protocol_service__method_indices_by_name[] = {
  13,        /* cancelDelegationToken */
  11,        /* failTaskAttempt */
  3,        /* getCounters */
  7,        /* getDelegationToken */
  6,        /* getDiagnostics */
  0,        /* getJobReport */
  4,        /* getTaskAttemptCompletionEvents */
  2,        /* getTaskAttemptReport */
  1,        /* getTaskReport */
  5,        /* getTaskReports */
  8,        /* killJob */
  9,        /* killTask */
  10,        /* killTaskAttempt */
  12         /* renewDelegationToken */
};
const ProtobufCServiceDescriptor hadoop__mapreduce__mrclient_protocol_service__descriptor =
{
  PROTOBUF_C_SERVICE_DESCRIPTOR_MAGIC,
  "hadoop.mapreduce.MRClientProtocolService",
  "renewDelegationToken",
  "Hadoop__Mapreduce__MRClientProtocolService",
  "hadoop.mapreduce",
  14,
  hadoop__mapreduce__mrclient_protocol_service__method_descriptors,
  hadoop__mapreduce__mrclient_protocol_service__method_indices_by_name
};
void hadoop__mapreduce__mrclient_protocol_service__get_job_report(ProtobufCService *service,
                                                                  const Hadoop__Mapreduce__GetJobReportRequestProto *input,
                                                                  Hadoop__Mapreduce__GetJobReportResponseProto_Closure closure,
                                                                  void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__mapreduce__mrclient_protocol_service__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__mapreduce__mrclient_protocol_service__get_task_report(ProtobufCService *service,
                                                                   const Hadoop__Mapreduce__GetTaskReportRequestProto *input,
                                                                   Hadoop__Mapreduce__GetTaskReportResponseProto_Closure closure,
                                                                   void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__mapreduce__mrclient_protocol_service__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__mapreduce__mrclient_protocol_service__get_task_attempt_report(ProtobufCService *service,
                                                                           const Hadoop__Mapreduce__GetTaskAttemptReportRequestProto *input,
                                                                           Hadoop__Mapreduce__GetTaskAttemptReportResponseProto_Closure closure,
                                                                           void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__mapreduce__mrclient_protocol_service__descriptor);
  service->invoke(service, 2, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__mapreduce__mrclient_protocol_service__get_counters(ProtobufCService *service,
                                                                const Hadoop__Mapreduce__GetCountersRequestProto *input,
                                                                Hadoop__Mapreduce__GetCountersResponseProto_Closure closure,
                                                                void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__mapreduce__mrclient_protocol_service__descriptor);
  service->invoke(service, 3, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__mapreduce__mrclient_protocol_service__get_task_attempt_completion_events(ProtobufCService *service,
                                                                                      const Hadoop__Mapreduce__GetTaskAttemptCompletionEventsRequestProto *input,
                                                                                      Hadoop__Mapreduce__GetTaskAttemptCompletionEventsResponseProto_Closure closure,
                                                                                      void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__mapreduce__mrclient_protocol_service__descriptor);
  service->invoke(service, 4, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__mapreduce__mrclient_protocol_service__get_task_reports(ProtobufCService *service,
                                                                    const Hadoop__Mapreduce__GetTaskReportsRequestProto *input,
                                                                    Hadoop__Mapreduce__GetTaskReportsResponseProto_Closure closure,
                                                                    void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__mapreduce__mrclient_protocol_service__descriptor);
  service->invoke(service, 5, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__mapreduce__mrclient_protocol_service__get_diagnostics(ProtobufCService *service,
                                                                   const Hadoop__Mapreduce__GetDiagnosticsRequestProto *input,
                                                                   Hadoop__Mapreduce__GetDiagnosticsResponseProto_Closure closure,
                                                                   void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__mapreduce__mrclient_protocol_service__descriptor);
  service->invoke(service, 6, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__mapreduce__mrclient_protocol_service__get_delegation_token(ProtobufCService *service,
                                                                        const Hadoop__Common__GetDelegationTokenRequestProto *input,
                                                                        Hadoop__Common__GetDelegationTokenResponseProto_Closure closure,
                                                                        void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__mapreduce__mrclient_protocol_service__descriptor);
  service->invoke(service, 7, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__mapreduce__mrclient_protocol_service__kill_job(ProtobufCService *service,
                                                            const Hadoop__Mapreduce__KillJobRequestProto *input,
                                                            Hadoop__Mapreduce__KillJobResponseProto_Closure closure,
                                                            void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__mapreduce__mrclient_protocol_service__descriptor);
  service->invoke(service, 8, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__mapreduce__mrclient_protocol_service__kill_task(ProtobufCService *service,
                                                             const Hadoop__Mapreduce__KillTaskRequestProto *input,
                                                             Hadoop__Mapreduce__KillTaskResponseProto_Closure closure,
                                                             void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__mapreduce__mrclient_protocol_service__descriptor);
  service->invoke(service, 9, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__mapreduce__mrclient_protocol_service__kill_task_attempt(ProtobufCService *service,
                                                                     const Hadoop__Mapreduce__KillTaskAttemptRequestProto *input,
                                                                     Hadoop__Mapreduce__KillTaskAttemptResponseProto_Closure closure,
                                                                     void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__mapreduce__mrclient_protocol_service__descriptor);
  service->invoke(service, 10, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__mapreduce__mrclient_protocol_service__fail_task_attempt(ProtobufCService *service,
                                                                     const Hadoop__Mapreduce__FailTaskAttemptRequestProto *input,
                                                                     Hadoop__Mapreduce__FailTaskAttemptResponseProto_Closure closure,
                                                                     void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__mapreduce__mrclient_protocol_service__descriptor);
  service->invoke(service, 11, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__mapreduce__mrclient_protocol_service__renew_delegation_token(ProtobufCService *service,
                                                                          const Hadoop__Common__RenewDelegationTokenRequestProto *input,
                                                                          Hadoop__Common__RenewDelegationTokenResponseProto_Closure closure,
                                                                          void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__mapreduce__mrclient_protocol_service__descriptor);
  service->invoke(service, 12, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__mapreduce__mrclient_protocol_service__cancel_delegation_token(ProtobufCService *service,
                                                                           const Hadoop__Common__CancelDelegationTokenRequestProto *input,
                                                                           Hadoop__Common__CancelDelegationTokenResponseProto_Closure closure,
                                                                           void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__mapreduce__mrclient_protocol_service__descriptor);
  service->invoke(service, 13, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__mapreduce__mrclient_protocol_service__init (Hadoop__Mapreduce__MRClientProtocolService_Service *service,
                                                         Hadoop__Mapreduce__MRClientProtocolService_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &hadoop__mapreduce__mrclient_protocol_service__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
