/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "NamenodeProtocol.pb-c.h"
void   hadoop__hdfs__get_blocks_request_proto__init
                     (Hadoop__Hdfs__GetBlocksRequestProto         *message)
{
  static Hadoop__Hdfs__GetBlocksRequestProto init_value = HADOOP__HDFS__GET_BLOCKS_REQUEST_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__hdfs__get_blocks_request_proto__get_packed_size
                     (const Hadoop__Hdfs__GetBlocksRequestProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_blocks_request_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__hdfs__get_blocks_request_proto__pack
                     (const Hadoop__Hdfs__GetBlocksRequestProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_blocks_request_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__hdfs__get_blocks_request_proto__pack_to_buffer
                     (const Hadoop__Hdfs__GetBlocksRequestProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_blocks_request_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Hdfs__GetBlocksRequestProto *
       hadoop__hdfs__get_blocks_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Hdfs__GetBlocksRequestProto *)
     protobuf_c_message_unpack (&hadoop__hdfs__get_blocks_request_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__hdfs__get_blocks_request_proto__free_unpacked
                     (Hadoop__Hdfs__GetBlocksRequestProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_blocks_request_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__hdfs__get_blocks_response_proto__init
                     (Hadoop__Hdfs__GetBlocksResponseProto         *message)
{
  static Hadoop__Hdfs__GetBlocksResponseProto init_value = HADOOP__HDFS__GET_BLOCKS_RESPONSE_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__hdfs__get_blocks_response_proto__get_packed_size
                     (const Hadoop__Hdfs__GetBlocksResponseProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_blocks_response_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__hdfs__get_blocks_response_proto__pack
                     (const Hadoop__Hdfs__GetBlocksResponseProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_blocks_response_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__hdfs__get_blocks_response_proto__pack_to_buffer
                     (const Hadoop__Hdfs__GetBlocksResponseProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_blocks_response_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Hdfs__GetBlocksResponseProto *
       hadoop__hdfs__get_blocks_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Hdfs__GetBlocksResponseProto *)
     protobuf_c_message_unpack (&hadoop__hdfs__get_blocks_response_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__hdfs__get_blocks_response_proto__free_unpacked
                     (Hadoop__Hdfs__GetBlocksResponseProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_blocks_response_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__hdfs__get_block_keys_request_proto__init
                     (Hadoop__Hdfs__GetBlockKeysRequestProto         *message)
{
  static Hadoop__Hdfs__GetBlockKeysRequestProto init_value = HADOOP__HDFS__GET_BLOCK_KEYS_REQUEST_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__hdfs__get_block_keys_request_proto__get_packed_size
                     (const Hadoop__Hdfs__GetBlockKeysRequestProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_block_keys_request_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__hdfs__get_block_keys_request_proto__pack
                     (const Hadoop__Hdfs__GetBlockKeysRequestProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_block_keys_request_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__hdfs__get_block_keys_request_proto__pack_to_buffer
                     (const Hadoop__Hdfs__GetBlockKeysRequestProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_block_keys_request_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Hdfs__GetBlockKeysRequestProto *
       hadoop__hdfs__get_block_keys_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Hdfs__GetBlockKeysRequestProto *)
     protobuf_c_message_unpack (&hadoop__hdfs__get_block_keys_request_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__hdfs__get_block_keys_request_proto__free_unpacked
                     (Hadoop__Hdfs__GetBlockKeysRequestProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_block_keys_request_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__hdfs__get_block_keys_response_proto__init
                     (Hadoop__Hdfs__GetBlockKeysResponseProto         *message)
{
  static Hadoop__Hdfs__GetBlockKeysResponseProto init_value = HADOOP__HDFS__GET_BLOCK_KEYS_RESPONSE_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__hdfs__get_block_keys_response_proto__get_packed_size
                     (const Hadoop__Hdfs__GetBlockKeysResponseProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_block_keys_response_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__hdfs__get_block_keys_response_proto__pack
                     (const Hadoop__Hdfs__GetBlockKeysResponseProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_block_keys_response_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__hdfs__get_block_keys_response_proto__pack_to_buffer
                     (const Hadoop__Hdfs__GetBlockKeysResponseProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_block_keys_response_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Hdfs__GetBlockKeysResponseProto *
       hadoop__hdfs__get_block_keys_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Hdfs__GetBlockKeysResponseProto *)
     protobuf_c_message_unpack (&hadoop__hdfs__get_block_keys_response_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__hdfs__get_block_keys_response_proto__free_unpacked
                     (Hadoop__Hdfs__GetBlockKeysResponseProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_block_keys_response_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__hdfs__get_transaction_id_request_proto__init
                     (Hadoop__Hdfs__GetTransactionIdRequestProto         *message)
{
  static Hadoop__Hdfs__GetTransactionIdRequestProto init_value = HADOOP__HDFS__GET_TRANSACTION_ID_REQUEST_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__hdfs__get_transaction_id_request_proto__get_packed_size
                     (const Hadoop__Hdfs__GetTransactionIdRequestProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_transaction_id_request_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__hdfs__get_transaction_id_request_proto__pack
                     (const Hadoop__Hdfs__GetTransactionIdRequestProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_transaction_id_request_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__hdfs__get_transaction_id_request_proto__pack_to_buffer
                     (const Hadoop__Hdfs__GetTransactionIdRequestProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_transaction_id_request_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Hdfs__GetTransactionIdRequestProto *
       hadoop__hdfs__get_transaction_id_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Hdfs__GetTransactionIdRequestProto *)
     protobuf_c_message_unpack (&hadoop__hdfs__get_transaction_id_request_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__hdfs__get_transaction_id_request_proto__free_unpacked
                     (Hadoop__Hdfs__GetTransactionIdRequestProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_transaction_id_request_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__hdfs__get_transaction_id_response_proto__init
                     (Hadoop__Hdfs__GetTransactionIdResponseProto         *message)
{
  static Hadoop__Hdfs__GetTransactionIdResponseProto init_value = HADOOP__HDFS__GET_TRANSACTION_ID_RESPONSE_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__hdfs__get_transaction_id_response_proto__get_packed_size
                     (const Hadoop__Hdfs__GetTransactionIdResponseProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_transaction_id_response_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__hdfs__get_transaction_id_response_proto__pack
                     (const Hadoop__Hdfs__GetTransactionIdResponseProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_transaction_id_response_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__hdfs__get_transaction_id_response_proto__pack_to_buffer
                     (const Hadoop__Hdfs__GetTransactionIdResponseProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_transaction_id_response_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Hdfs__GetTransactionIdResponseProto *
       hadoop__hdfs__get_transaction_id_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Hdfs__GetTransactionIdResponseProto *)
     protobuf_c_message_unpack (&hadoop__hdfs__get_transaction_id_response_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__hdfs__get_transaction_id_response_proto__free_unpacked
                     (Hadoop__Hdfs__GetTransactionIdResponseProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_transaction_id_response_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__hdfs__roll_edit_log_request_proto__init
                     (Hadoop__Hdfs__RollEditLogRequestProto         *message)
{
  static Hadoop__Hdfs__RollEditLogRequestProto init_value = HADOOP__HDFS__ROLL_EDIT_LOG_REQUEST_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__hdfs__roll_edit_log_request_proto__get_packed_size
                     (const Hadoop__Hdfs__RollEditLogRequestProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__roll_edit_log_request_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__hdfs__roll_edit_log_request_proto__pack
                     (const Hadoop__Hdfs__RollEditLogRequestProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__roll_edit_log_request_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__hdfs__roll_edit_log_request_proto__pack_to_buffer
                     (const Hadoop__Hdfs__RollEditLogRequestProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__roll_edit_log_request_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Hdfs__RollEditLogRequestProto *
       hadoop__hdfs__roll_edit_log_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Hdfs__RollEditLogRequestProto *)
     protobuf_c_message_unpack (&hadoop__hdfs__roll_edit_log_request_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__hdfs__roll_edit_log_request_proto__free_unpacked
                     (Hadoop__Hdfs__RollEditLogRequestProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__roll_edit_log_request_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__hdfs__roll_edit_log_response_proto__init
                     (Hadoop__Hdfs__RollEditLogResponseProto         *message)
{
  static Hadoop__Hdfs__RollEditLogResponseProto init_value = HADOOP__HDFS__ROLL_EDIT_LOG_RESPONSE_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__hdfs__roll_edit_log_response_proto__get_packed_size
                     (const Hadoop__Hdfs__RollEditLogResponseProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__roll_edit_log_response_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__hdfs__roll_edit_log_response_proto__pack
                     (const Hadoop__Hdfs__RollEditLogResponseProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__roll_edit_log_response_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__hdfs__roll_edit_log_response_proto__pack_to_buffer
                     (const Hadoop__Hdfs__RollEditLogResponseProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__roll_edit_log_response_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Hdfs__RollEditLogResponseProto *
       hadoop__hdfs__roll_edit_log_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Hdfs__RollEditLogResponseProto *)
     protobuf_c_message_unpack (&hadoop__hdfs__roll_edit_log_response_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__hdfs__roll_edit_log_response_proto__free_unpacked
                     (Hadoop__Hdfs__RollEditLogResponseProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__roll_edit_log_response_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__hdfs__get_most_recent_checkpoint_tx_id_request_proto__init
                     (Hadoop__Hdfs__GetMostRecentCheckpointTxIdRequestProto         *message)
{
  static Hadoop__Hdfs__GetMostRecentCheckpointTxIdRequestProto init_value = HADOOP__HDFS__GET_MOST_RECENT_CHECKPOINT_TX_ID_REQUEST_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__hdfs__get_most_recent_checkpoint_tx_id_request_proto__get_packed_size
                     (const Hadoop__Hdfs__GetMostRecentCheckpointTxIdRequestProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_most_recent_checkpoint_tx_id_request_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__hdfs__get_most_recent_checkpoint_tx_id_request_proto__pack
                     (const Hadoop__Hdfs__GetMostRecentCheckpointTxIdRequestProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_most_recent_checkpoint_tx_id_request_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__hdfs__get_most_recent_checkpoint_tx_id_request_proto__pack_to_buffer
                     (const Hadoop__Hdfs__GetMostRecentCheckpointTxIdRequestProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_most_recent_checkpoint_tx_id_request_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Hdfs__GetMostRecentCheckpointTxIdRequestProto *
       hadoop__hdfs__get_most_recent_checkpoint_tx_id_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Hdfs__GetMostRecentCheckpointTxIdRequestProto *)
     protobuf_c_message_unpack (&hadoop__hdfs__get_most_recent_checkpoint_tx_id_request_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__hdfs__get_most_recent_checkpoint_tx_id_request_proto__free_unpacked
                     (Hadoop__Hdfs__GetMostRecentCheckpointTxIdRequestProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_most_recent_checkpoint_tx_id_request_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__hdfs__get_most_recent_checkpoint_tx_id_response_proto__init
                     (Hadoop__Hdfs__GetMostRecentCheckpointTxIdResponseProto         *message)
{
  static Hadoop__Hdfs__GetMostRecentCheckpointTxIdResponseProto init_value = HADOOP__HDFS__GET_MOST_RECENT_CHECKPOINT_TX_ID_RESPONSE_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__hdfs__get_most_recent_checkpoint_tx_id_response_proto__get_packed_size
                     (const Hadoop__Hdfs__GetMostRecentCheckpointTxIdResponseProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_most_recent_checkpoint_tx_id_response_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__hdfs__get_most_recent_checkpoint_tx_id_response_proto__pack
                     (const Hadoop__Hdfs__GetMostRecentCheckpointTxIdResponseProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_most_recent_checkpoint_tx_id_response_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__hdfs__get_most_recent_checkpoint_tx_id_response_proto__pack_to_buffer
                     (const Hadoop__Hdfs__GetMostRecentCheckpointTxIdResponseProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_most_recent_checkpoint_tx_id_response_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Hdfs__GetMostRecentCheckpointTxIdResponseProto *
       hadoop__hdfs__get_most_recent_checkpoint_tx_id_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Hdfs__GetMostRecentCheckpointTxIdResponseProto *)
     protobuf_c_message_unpack (&hadoop__hdfs__get_most_recent_checkpoint_tx_id_response_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__hdfs__get_most_recent_checkpoint_tx_id_response_proto__free_unpacked
                     (Hadoop__Hdfs__GetMostRecentCheckpointTxIdResponseProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_most_recent_checkpoint_tx_id_response_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__hdfs__error_report_request_proto__init
                     (Hadoop__Hdfs__ErrorReportRequestProto         *message)
{
  static Hadoop__Hdfs__ErrorReportRequestProto init_value = HADOOP__HDFS__ERROR_REPORT_REQUEST_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__hdfs__error_report_request_proto__get_packed_size
                     (const Hadoop__Hdfs__ErrorReportRequestProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__error_report_request_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__hdfs__error_report_request_proto__pack
                     (const Hadoop__Hdfs__ErrorReportRequestProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__error_report_request_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__hdfs__error_report_request_proto__pack_to_buffer
                     (const Hadoop__Hdfs__ErrorReportRequestProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__error_report_request_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Hdfs__ErrorReportRequestProto *
       hadoop__hdfs__error_report_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Hdfs__ErrorReportRequestProto *)
     protobuf_c_message_unpack (&hadoop__hdfs__error_report_request_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__hdfs__error_report_request_proto__free_unpacked
                     (Hadoop__Hdfs__ErrorReportRequestProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__error_report_request_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__hdfs__error_report_response_proto__init
                     (Hadoop__Hdfs__ErrorReportResponseProto         *message)
{
  static Hadoop__Hdfs__ErrorReportResponseProto init_value = HADOOP__HDFS__ERROR_REPORT_RESPONSE_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__hdfs__error_report_response_proto__get_packed_size
                     (const Hadoop__Hdfs__ErrorReportResponseProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__error_report_response_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__hdfs__error_report_response_proto__pack
                     (const Hadoop__Hdfs__ErrorReportResponseProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__error_report_response_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__hdfs__error_report_response_proto__pack_to_buffer
                     (const Hadoop__Hdfs__ErrorReportResponseProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__error_report_response_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Hdfs__ErrorReportResponseProto *
       hadoop__hdfs__error_report_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Hdfs__ErrorReportResponseProto *)
     protobuf_c_message_unpack (&hadoop__hdfs__error_report_response_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__hdfs__error_report_response_proto__free_unpacked
                     (Hadoop__Hdfs__ErrorReportResponseProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__error_report_response_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__hdfs__register_request_proto__init
                     (Hadoop__Hdfs__RegisterRequestProto         *message)
{
  static Hadoop__Hdfs__RegisterRequestProto init_value = HADOOP__HDFS__REGISTER_REQUEST_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__hdfs__register_request_proto__get_packed_size
                     (const Hadoop__Hdfs__RegisterRequestProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__register_request_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__hdfs__register_request_proto__pack
                     (const Hadoop__Hdfs__RegisterRequestProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__register_request_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__hdfs__register_request_proto__pack_to_buffer
                     (const Hadoop__Hdfs__RegisterRequestProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__register_request_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Hdfs__RegisterRequestProto *
       hadoop__hdfs__register_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Hdfs__RegisterRequestProto *)
     protobuf_c_message_unpack (&hadoop__hdfs__register_request_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__hdfs__register_request_proto__free_unpacked
                     (Hadoop__Hdfs__RegisterRequestProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__register_request_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__hdfs__register_response_proto__init
                     (Hadoop__Hdfs__RegisterResponseProto         *message)
{
  static Hadoop__Hdfs__RegisterResponseProto init_value = HADOOP__HDFS__REGISTER_RESPONSE_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__hdfs__register_response_proto__get_packed_size
                     (const Hadoop__Hdfs__RegisterResponseProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__register_response_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__hdfs__register_response_proto__pack
                     (const Hadoop__Hdfs__RegisterResponseProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__register_response_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__hdfs__register_response_proto__pack_to_buffer
                     (const Hadoop__Hdfs__RegisterResponseProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__register_response_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Hdfs__RegisterResponseProto *
       hadoop__hdfs__register_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Hdfs__RegisterResponseProto *)
     protobuf_c_message_unpack (&hadoop__hdfs__register_response_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__hdfs__register_response_proto__free_unpacked
                     (Hadoop__Hdfs__RegisterResponseProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__register_response_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__hdfs__start_checkpoint_request_proto__init
                     (Hadoop__Hdfs__StartCheckpointRequestProto         *message)
{
  static Hadoop__Hdfs__StartCheckpointRequestProto init_value = HADOOP__HDFS__START_CHECKPOINT_REQUEST_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__hdfs__start_checkpoint_request_proto__get_packed_size
                     (const Hadoop__Hdfs__StartCheckpointRequestProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__start_checkpoint_request_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__hdfs__start_checkpoint_request_proto__pack
                     (const Hadoop__Hdfs__StartCheckpointRequestProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__start_checkpoint_request_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__hdfs__start_checkpoint_request_proto__pack_to_buffer
                     (const Hadoop__Hdfs__StartCheckpointRequestProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__start_checkpoint_request_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Hdfs__StartCheckpointRequestProto *
       hadoop__hdfs__start_checkpoint_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Hdfs__StartCheckpointRequestProto *)
     protobuf_c_message_unpack (&hadoop__hdfs__start_checkpoint_request_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__hdfs__start_checkpoint_request_proto__free_unpacked
                     (Hadoop__Hdfs__StartCheckpointRequestProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__start_checkpoint_request_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__hdfs__start_checkpoint_response_proto__init
                     (Hadoop__Hdfs__StartCheckpointResponseProto         *message)
{
  static Hadoop__Hdfs__StartCheckpointResponseProto init_value = HADOOP__HDFS__START_CHECKPOINT_RESPONSE_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__hdfs__start_checkpoint_response_proto__get_packed_size
                     (const Hadoop__Hdfs__StartCheckpointResponseProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__start_checkpoint_response_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__hdfs__start_checkpoint_response_proto__pack
                     (const Hadoop__Hdfs__StartCheckpointResponseProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__start_checkpoint_response_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__hdfs__start_checkpoint_response_proto__pack_to_buffer
                     (const Hadoop__Hdfs__StartCheckpointResponseProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__start_checkpoint_response_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Hdfs__StartCheckpointResponseProto *
       hadoop__hdfs__start_checkpoint_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Hdfs__StartCheckpointResponseProto *)
     protobuf_c_message_unpack (&hadoop__hdfs__start_checkpoint_response_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__hdfs__start_checkpoint_response_proto__free_unpacked
                     (Hadoop__Hdfs__StartCheckpointResponseProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__start_checkpoint_response_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__hdfs__end_checkpoint_request_proto__init
                     (Hadoop__Hdfs__EndCheckpointRequestProto         *message)
{
  static Hadoop__Hdfs__EndCheckpointRequestProto init_value = HADOOP__HDFS__END_CHECKPOINT_REQUEST_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__hdfs__end_checkpoint_request_proto__get_packed_size
                     (const Hadoop__Hdfs__EndCheckpointRequestProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__end_checkpoint_request_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__hdfs__end_checkpoint_request_proto__pack
                     (const Hadoop__Hdfs__EndCheckpointRequestProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__end_checkpoint_request_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__hdfs__end_checkpoint_request_proto__pack_to_buffer
                     (const Hadoop__Hdfs__EndCheckpointRequestProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__end_checkpoint_request_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Hdfs__EndCheckpointRequestProto *
       hadoop__hdfs__end_checkpoint_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Hdfs__EndCheckpointRequestProto *)
     protobuf_c_message_unpack (&hadoop__hdfs__end_checkpoint_request_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__hdfs__end_checkpoint_request_proto__free_unpacked
                     (Hadoop__Hdfs__EndCheckpointRequestProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__end_checkpoint_request_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__hdfs__end_checkpoint_response_proto__init
                     (Hadoop__Hdfs__EndCheckpointResponseProto         *message)
{
  static Hadoop__Hdfs__EndCheckpointResponseProto init_value = HADOOP__HDFS__END_CHECKPOINT_RESPONSE_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__hdfs__end_checkpoint_response_proto__get_packed_size
                     (const Hadoop__Hdfs__EndCheckpointResponseProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__end_checkpoint_response_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__hdfs__end_checkpoint_response_proto__pack
                     (const Hadoop__Hdfs__EndCheckpointResponseProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__end_checkpoint_response_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__hdfs__end_checkpoint_response_proto__pack_to_buffer
                     (const Hadoop__Hdfs__EndCheckpointResponseProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__end_checkpoint_response_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Hdfs__EndCheckpointResponseProto *
       hadoop__hdfs__end_checkpoint_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Hdfs__EndCheckpointResponseProto *)
     protobuf_c_message_unpack (&hadoop__hdfs__end_checkpoint_response_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__hdfs__end_checkpoint_response_proto__free_unpacked
                     (Hadoop__Hdfs__EndCheckpointResponseProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__end_checkpoint_response_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__hdfs__get_edit_log_manifest_request_proto__init
                     (Hadoop__Hdfs__GetEditLogManifestRequestProto         *message)
{
  static Hadoop__Hdfs__GetEditLogManifestRequestProto init_value = HADOOP__HDFS__GET_EDIT_LOG_MANIFEST_REQUEST_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__hdfs__get_edit_log_manifest_request_proto__get_packed_size
                     (const Hadoop__Hdfs__GetEditLogManifestRequestProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_edit_log_manifest_request_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__hdfs__get_edit_log_manifest_request_proto__pack
                     (const Hadoop__Hdfs__GetEditLogManifestRequestProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_edit_log_manifest_request_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__hdfs__get_edit_log_manifest_request_proto__pack_to_buffer
                     (const Hadoop__Hdfs__GetEditLogManifestRequestProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_edit_log_manifest_request_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Hdfs__GetEditLogManifestRequestProto *
       hadoop__hdfs__get_edit_log_manifest_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Hdfs__GetEditLogManifestRequestProto *)
     protobuf_c_message_unpack (&hadoop__hdfs__get_edit_log_manifest_request_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__hdfs__get_edit_log_manifest_request_proto__free_unpacked
                     (Hadoop__Hdfs__GetEditLogManifestRequestProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_edit_log_manifest_request_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__hdfs__get_edit_log_manifest_response_proto__init
                     (Hadoop__Hdfs__GetEditLogManifestResponseProto         *message)
{
  static Hadoop__Hdfs__GetEditLogManifestResponseProto init_value = HADOOP__HDFS__GET_EDIT_LOG_MANIFEST_RESPONSE_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__hdfs__get_edit_log_manifest_response_proto__get_packed_size
                     (const Hadoop__Hdfs__GetEditLogManifestResponseProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_edit_log_manifest_response_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__hdfs__get_edit_log_manifest_response_proto__pack
                     (const Hadoop__Hdfs__GetEditLogManifestResponseProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_edit_log_manifest_response_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__hdfs__get_edit_log_manifest_response_proto__pack_to_buffer
                     (const Hadoop__Hdfs__GetEditLogManifestResponseProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_edit_log_manifest_response_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Hdfs__GetEditLogManifestResponseProto *
       hadoop__hdfs__get_edit_log_manifest_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Hdfs__GetEditLogManifestResponseProto *)
     protobuf_c_message_unpack (&hadoop__hdfs__get_edit_log_manifest_response_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__hdfs__get_edit_log_manifest_response_proto__free_unpacked
                     (Hadoop__Hdfs__GetEditLogManifestResponseProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__hdfs__get_edit_log_manifest_response_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor hadoop__hdfs__get_blocks_request_proto__field_descriptors[2] =
{
  {
    "datanode",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__GetBlocksRequestProto, datanode),
    &hadoop__hdfs__datanode_idproto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__GetBlocksRequestProto, size),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__hdfs__get_blocks_request_proto__field_indices_by_name[] = {
  0,   /* field[0] = datanode */
  1,   /* field[1] = size */
};
static const ProtobufCIntRange hadoop__hdfs__get_blocks_request_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor hadoop__hdfs__get_blocks_request_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.hdfs.GetBlocksRequestProto",
  "GetBlocksRequestProto",
  "Hadoop__Hdfs__GetBlocksRequestProto",
  "hadoop.hdfs",
  sizeof(Hadoop__Hdfs__GetBlocksRequestProto),
  2,
  hadoop__hdfs__get_blocks_request_proto__field_descriptors,
  hadoop__hdfs__get_blocks_request_proto__field_indices_by_name,
  1,  hadoop__hdfs__get_blocks_request_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__hdfs__get_blocks_request_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hadoop__hdfs__get_blocks_response_proto__field_descriptors[1] =
{
  {
    "blocks",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__GetBlocksResponseProto, blocks),
    &hadoop__hdfs__blocks_with_locations_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__hdfs__get_blocks_response_proto__field_indices_by_name[] = {
  0,   /* field[0] = blocks */
};
static const ProtobufCIntRange hadoop__hdfs__get_blocks_response_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor hadoop__hdfs__get_blocks_response_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.hdfs.GetBlocksResponseProto",
  "GetBlocksResponseProto",
  "Hadoop__Hdfs__GetBlocksResponseProto",
  "hadoop.hdfs",
  sizeof(Hadoop__Hdfs__GetBlocksResponseProto),
  1,
  hadoop__hdfs__get_blocks_response_proto__field_descriptors,
  hadoop__hdfs__get_blocks_response_proto__field_indices_by_name,
  1,  hadoop__hdfs__get_blocks_response_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__hdfs__get_blocks_response_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define hadoop__hdfs__get_block_keys_request_proto__field_descriptors NULL
#define hadoop__hdfs__get_block_keys_request_proto__field_indices_by_name NULL
#define hadoop__hdfs__get_block_keys_request_proto__number_ranges NULL
const ProtobufCMessageDescriptor hadoop__hdfs__get_block_keys_request_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.hdfs.GetBlockKeysRequestProto",
  "GetBlockKeysRequestProto",
  "Hadoop__Hdfs__GetBlockKeysRequestProto",
  "hadoop.hdfs",
  sizeof(Hadoop__Hdfs__GetBlockKeysRequestProto),
  0,
  hadoop__hdfs__get_block_keys_request_proto__field_descriptors,
  hadoop__hdfs__get_block_keys_request_proto__field_indices_by_name,
  0,  hadoop__hdfs__get_block_keys_request_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__hdfs__get_block_keys_request_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hadoop__hdfs__get_block_keys_response_proto__field_descriptors[1] =
{
  {
    "keys",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__GetBlockKeysResponseProto, keys),
    &hadoop__hdfs__exported_block_keys_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__hdfs__get_block_keys_response_proto__field_indices_by_name[] = {
  0,   /* field[0] = keys */
};
static const ProtobufCIntRange hadoop__hdfs__get_block_keys_response_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor hadoop__hdfs__get_block_keys_response_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.hdfs.GetBlockKeysResponseProto",
  "GetBlockKeysResponseProto",
  "Hadoop__Hdfs__GetBlockKeysResponseProto",
  "hadoop.hdfs",
  sizeof(Hadoop__Hdfs__GetBlockKeysResponseProto),
  1,
  hadoop__hdfs__get_block_keys_response_proto__field_descriptors,
  hadoop__hdfs__get_block_keys_response_proto__field_indices_by_name,
  1,  hadoop__hdfs__get_block_keys_response_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__hdfs__get_block_keys_response_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define hadoop__hdfs__get_transaction_id_request_proto__field_descriptors NULL
#define hadoop__hdfs__get_transaction_id_request_proto__field_indices_by_name NULL
#define hadoop__hdfs__get_transaction_id_request_proto__number_ranges NULL
const ProtobufCMessageDescriptor hadoop__hdfs__get_transaction_id_request_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.hdfs.GetTransactionIdRequestProto",
  "GetTransactionIdRequestProto",
  "Hadoop__Hdfs__GetTransactionIdRequestProto",
  "hadoop.hdfs",
  sizeof(Hadoop__Hdfs__GetTransactionIdRequestProto),
  0,
  hadoop__hdfs__get_transaction_id_request_proto__field_descriptors,
  hadoop__hdfs__get_transaction_id_request_proto__field_indices_by_name,
  0,  hadoop__hdfs__get_transaction_id_request_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__hdfs__get_transaction_id_request_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hadoop__hdfs__get_transaction_id_response_proto__field_descriptors[1] =
{
  {
    "txId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__GetTransactionIdResponseProto, txid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__hdfs__get_transaction_id_response_proto__field_indices_by_name[] = {
  0,   /* field[0] = txId */
};
static const ProtobufCIntRange hadoop__hdfs__get_transaction_id_response_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor hadoop__hdfs__get_transaction_id_response_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.hdfs.GetTransactionIdResponseProto",
  "GetTransactionIdResponseProto",
  "Hadoop__Hdfs__GetTransactionIdResponseProto",
  "hadoop.hdfs",
  sizeof(Hadoop__Hdfs__GetTransactionIdResponseProto),
  1,
  hadoop__hdfs__get_transaction_id_response_proto__field_descriptors,
  hadoop__hdfs__get_transaction_id_response_proto__field_indices_by_name,
  1,  hadoop__hdfs__get_transaction_id_response_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__hdfs__get_transaction_id_response_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define hadoop__hdfs__roll_edit_log_request_proto__field_descriptors NULL
#define hadoop__hdfs__roll_edit_log_request_proto__field_indices_by_name NULL
#define hadoop__hdfs__roll_edit_log_request_proto__number_ranges NULL
const ProtobufCMessageDescriptor hadoop__hdfs__roll_edit_log_request_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.hdfs.RollEditLogRequestProto",
  "RollEditLogRequestProto",
  "Hadoop__Hdfs__RollEditLogRequestProto",
  "hadoop.hdfs",
  sizeof(Hadoop__Hdfs__RollEditLogRequestProto),
  0,
  hadoop__hdfs__roll_edit_log_request_proto__field_descriptors,
  hadoop__hdfs__roll_edit_log_request_proto__field_indices_by_name,
  0,  hadoop__hdfs__roll_edit_log_request_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__hdfs__roll_edit_log_request_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hadoop__hdfs__roll_edit_log_response_proto__field_descriptors[1] =
{
  {
    "signature",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__RollEditLogResponseProto, signature),
    &hadoop__hdfs__checkpoint_signature_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__hdfs__roll_edit_log_response_proto__field_indices_by_name[] = {
  0,   /* field[0] = signature */
};
static const ProtobufCIntRange hadoop__hdfs__roll_edit_log_response_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor hadoop__hdfs__roll_edit_log_response_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.hdfs.RollEditLogResponseProto",
  "RollEditLogResponseProto",
  "Hadoop__Hdfs__RollEditLogResponseProto",
  "hadoop.hdfs",
  sizeof(Hadoop__Hdfs__RollEditLogResponseProto),
  1,
  hadoop__hdfs__roll_edit_log_response_proto__field_descriptors,
  hadoop__hdfs__roll_edit_log_response_proto__field_indices_by_name,
  1,  hadoop__hdfs__roll_edit_log_response_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__hdfs__roll_edit_log_response_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define hadoop__hdfs__get_most_recent_checkpoint_tx_id_request_proto__field_descriptors NULL
#define hadoop__hdfs__get_most_recent_checkpoint_tx_id_request_proto__field_indices_by_name NULL
#define hadoop__hdfs__get_most_recent_checkpoint_tx_id_request_proto__number_ranges NULL
const ProtobufCMessageDescriptor hadoop__hdfs__get_most_recent_checkpoint_tx_id_request_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.hdfs.GetMostRecentCheckpointTxIdRequestProto",
  "GetMostRecentCheckpointTxIdRequestProto",
  "Hadoop__Hdfs__GetMostRecentCheckpointTxIdRequestProto",
  "hadoop.hdfs",
  sizeof(Hadoop__Hdfs__GetMostRecentCheckpointTxIdRequestProto),
  0,
  hadoop__hdfs__get_most_recent_checkpoint_tx_id_request_proto__field_descriptors,
  hadoop__hdfs__get_most_recent_checkpoint_tx_id_request_proto__field_indices_by_name,
  0,  hadoop__hdfs__get_most_recent_checkpoint_tx_id_request_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__hdfs__get_most_recent_checkpoint_tx_id_request_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hadoop__hdfs__get_most_recent_checkpoint_tx_id_response_proto__field_descriptors[1] =
{
  {
    "txId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__GetMostRecentCheckpointTxIdResponseProto, txid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__hdfs__get_most_recent_checkpoint_tx_id_response_proto__field_indices_by_name[] = {
  0,   /* field[0] = txId */
};
static const ProtobufCIntRange hadoop__hdfs__get_most_recent_checkpoint_tx_id_response_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor hadoop__hdfs__get_most_recent_checkpoint_tx_id_response_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.hdfs.GetMostRecentCheckpointTxIdResponseProto",
  "GetMostRecentCheckpointTxIdResponseProto",
  "Hadoop__Hdfs__GetMostRecentCheckpointTxIdResponseProto",
  "hadoop.hdfs",
  sizeof(Hadoop__Hdfs__GetMostRecentCheckpointTxIdResponseProto),
  1,
  hadoop__hdfs__get_most_recent_checkpoint_tx_id_response_proto__field_descriptors,
  hadoop__hdfs__get_most_recent_checkpoint_tx_id_response_proto__field_indices_by_name,
  1,  hadoop__hdfs__get_most_recent_checkpoint_tx_id_response_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__hdfs__get_most_recent_checkpoint_tx_id_response_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hadoop__hdfs__error_report_request_proto__field_descriptors[3] =
{
  {
    "registration",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__ErrorReportRequestProto, registration),
    &hadoop__hdfs__namenode_registration_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errorCode",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__ErrorReportRequestProto, errorcode),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__ErrorReportRequestProto, msg),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__hdfs__error_report_request_proto__field_indices_by_name[] = {
  1,   /* field[1] = errorCode */
  2,   /* field[2] = msg */
  0,   /* field[0] = registration */
};
static const ProtobufCIntRange hadoop__hdfs__error_report_request_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor hadoop__hdfs__error_report_request_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.hdfs.ErrorReportRequestProto",
  "ErrorReportRequestProto",
  "Hadoop__Hdfs__ErrorReportRequestProto",
  "hadoop.hdfs",
  sizeof(Hadoop__Hdfs__ErrorReportRequestProto),
  3,
  hadoop__hdfs__error_report_request_proto__field_descriptors,
  hadoop__hdfs__error_report_request_proto__field_indices_by_name,
  1,  hadoop__hdfs__error_report_request_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__hdfs__error_report_request_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define hadoop__hdfs__error_report_response_proto__field_descriptors NULL
#define hadoop__hdfs__error_report_response_proto__field_indices_by_name NULL
#define hadoop__hdfs__error_report_response_proto__number_ranges NULL
const ProtobufCMessageDescriptor hadoop__hdfs__error_report_response_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.hdfs.ErrorReportResponseProto",
  "ErrorReportResponseProto",
  "Hadoop__Hdfs__ErrorReportResponseProto",
  "hadoop.hdfs",
  sizeof(Hadoop__Hdfs__ErrorReportResponseProto),
  0,
  hadoop__hdfs__error_report_response_proto__field_descriptors,
  hadoop__hdfs__error_report_response_proto__field_indices_by_name,
  0,  hadoop__hdfs__error_report_response_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__hdfs__error_report_response_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hadoop__hdfs__register_request_proto__field_descriptors[1] =
{
  {
    "registration",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__RegisterRequestProto, registration),
    &hadoop__hdfs__namenode_registration_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__hdfs__register_request_proto__field_indices_by_name[] = {
  0,   /* field[0] = registration */
};
static const ProtobufCIntRange hadoop__hdfs__register_request_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor hadoop__hdfs__register_request_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.hdfs.RegisterRequestProto",
  "RegisterRequestProto",
  "Hadoop__Hdfs__RegisterRequestProto",
  "hadoop.hdfs",
  sizeof(Hadoop__Hdfs__RegisterRequestProto),
  1,
  hadoop__hdfs__register_request_proto__field_descriptors,
  hadoop__hdfs__register_request_proto__field_indices_by_name,
  1,  hadoop__hdfs__register_request_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__hdfs__register_request_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hadoop__hdfs__register_response_proto__field_descriptors[1] =
{
  {
    "registration",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__RegisterResponseProto, registration),
    &hadoop__hdfs__namenode_registration_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__hdfs__register_response_proto__field_indices_by_name[] = {
  0,   /* field[0] = registration */
};
static const ProtobufCIntRange hadoop__hdfs__register_response_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor hadoop__hdfs__register_response_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.hdfs.RegisterResponseProto",
  "RegisterResponseProto",
  "Hadoop__Hdfs__RegisterResponseProto",
  "hadoop.hdfs",
  sizeof(Hadoop__Hdfs__RegisterResponseProto),
  1,
  hadoop__hdfs__register_response_proto__field_descriptors,
  hadoop__hdfs__register_response_proto__field_indices_by_name,
  1,  hadoop__hdfs__register_response_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__hdfs__register_response_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hadoop__hdfs__start_checkpoint_request_proto__field_descriptors[1] =
{
  {
    "registration",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__StartCheckpointRequestProto, registration),
    &hadoop__hdfs__namenode_registration_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__hdfs__start_checkpoint_request_proto__field_indices_by_name[] = {
  0,   /* field[0] = registration */
};
static const ProtobufCIntRange hadoop__hdfs__start_checkpoint_request_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor hadoop__hdfs__start_checkpoint_request_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.hdfs.StartCheckpointRequestProto",
  "StartCheckpointRequestProto",
  "Hadoop__Hdfs__StartCheckpointRequestProto",
  "hadoop.hdfs",
  sizeof(Hadoop__Hdfs__StartCheckpointRequestProto),
  1,
  hadoop__hdfs__start_checkpoint_request_proto__field_descriptors,
  hadoop__hdfs__start_checkpoint_request_proto__field_indices_by_name,
  1,  hadoop__hdfs__start_checkpoint_request_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__hdfs__start_checkpoint_request_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hadoop__hdfs__start_checkpoint_response_proto__field_descriptors[1] =
{
  {
    "command",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__StartCheckpointResponseProto, command),
    &hadoop__hdfs__namenode_command_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__hdfs__start_checkpoint_response_proto__field_indices_by_name[] = {
  0,   /* field[0] = command */
};
static const ProtobufCIntRange hadoop__hdfs__start_checkpoint_response_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor hadoop__hdfs__start_checkpoint_response_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.hdfs.StartCheckpointResponseProto",
  "StartCheckpointResponseProto",
  "Hadoop__Hdfs__StartCheckpointResponseProto",
  "hadoop.hdfs",
  sizeof(Hadoop__Hdfs__StartCheckpointResponseProto),
  1,
  hadoop__hdfs__start_checkpoint_response_proto__field_descriptors,
  hadoop__hdfs__start_checkpoint_response_proto__field_indices_by_name,
  1,  hadoop__hdfs__start_checkpoint_response_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__hdfs__start_checkpoint_response_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hadoop__hdfs__end_checkpoint_request_proto__field_descriptors[2] =
{
  {
    "registration",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__EndCheckpointRequestProto, registration),
    &hadoop__hdfs__namenode_registration_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signature",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__EndCheckpointRequestProto, signature),
    &hadoop__hdfs__checkpoint_signature_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__hdfs__end_checkpoint_request_proto__field_indices_by_name[] = {
  0,   /* field[0] = registration */
  1,   /* field[1] = signature */
};
static const ProtobufCIntRange hadoop__hdfs__end_checkpoint_request_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor hadoop__hdfs__end_checkpoint_request_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.hdfs.EndCheckpointRequestProto",
  "EndCheckpointRequestProto",
  "Hadoop__Hdfs__EndCheckpointRequestProto",
  "hadoop.hdfs",
  sizeof(Hadoop__Hdfs__EndCheckpointRequestProto),
  2,
  hadoop__hdfs__end_checkpoint_request_proto__field_descriptors,
  hadoop__hdfs__end_checkpoint_request_proto__field_indices_by_name,
  1,  hadoop__hdfs__end_checkpoint_request_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__hdfs__end_checkpoint_request_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define hadoop__hdfs__end_checkpoint_response_proto__field_descriptors NULL
#define hadoop__hdfs__end_checkpoint_response_proto__field_indices_by_name NULL
#define hadoop__hdfs__end_checkpoint_response_proto__number_ranges NULL
const ProtobufCMessageDescriptor hadoop__hdfs__end_checkpoint_response_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.hdfs.EndCheckpointResponseProto",
  "EndCheckpointResponseProto",
  "Hadoop__Hdfs__EndCheckpointResponseProto",
  "hadoop.hdfs",
  sizeof(Hadoop__Hdfs__EndCheckpointResponseProto),
  0,
  hadoop__hdfs__end_checkpoint_response_proto__field_descriptors,
  hadoop__hdfs__end_checkpoint_response_proto__field_indices_by_name,
  0,  hadoop__hdfs__end_checkpoint_response_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__hdfs__end_checkpoint_response_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hadoop__hdfs__get_edit_log_manifest_request_proto__field_descriptors[1] =
{
  {
    "sinceTxId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__GetEditLogManifestRequestProto, sincetxid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__hdfs__get_edit_log_manifest_request_proto__field_indices_by_name[] = {
  0,   /* field[0] = sinceTxId */
};
static const ProtobufCIntRange hadoop__hdfs__get_edit_log_manifest_request_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor hadoop__hdfs__get_edit_log_manifest_request_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.hdfs.GetEditLogManifestRequestProto",
  "GetEditLogManifestRequestProto",
  "Hadoop__Hdfs__GetEditLogManifestRequestProto",
  "hadoop.hdfs",
  sizeof(Hadoop__Hdfs__GetEditLogManifestRequestProto),
  1,
  hadoop__hdfs__get_edit_log_manifest_request_proto__field_descriptors,
  hadoop__hdfs__get_edit_log_manifest_request_proto__field_indices_by_name,
  1,  hadoop__hdfs__get_edit_log_manifest_request_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__hdfs__get_edit_log_manifest_request_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hadoop__hdfs__get_edit_log_manifest_response_proto__field_descriptors[1] =
{
  {
    "manifest",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Hdfs__GetEditLogManifestResponseProto, manifest),
    &hadoop__hdfs__remote_edit_log_manifest_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__hdfs__get_edit_log_manifest_response_proto__field_indices_by_name[] = {
  0,   /* field[0] = manifest */
};
static const ProtobufCIntRange hadoop__hdfs__get_edit_log_manifest_response_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor hadoop__hdfs__get_edit_log_manifest_response_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.hdfs.GetEditLogManifestResponseProto",
  "GetEditLogManifestResponseProto",
  "Hadoop__Hdfs__GetEditLogManifestResponseProto",
  "hadoop.hdfs",
  sizeof(Hadoop__Hdfs__GetEditLogManifestResponseProto),
  1,
  hadoop__hdfs__get_edit_log_manifest_response_proto__field_descriptors,
  hadoop__hdfs__get_edit_log_manifest_response_proto__field_indices_by_name,
  1,  hadoop__hdfs__get_edit_log_manifest_response_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__hdfs__get_edit_log_manifest_response_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor hadoop__hdfs__namenode_protocol_service__method_descriptors[11] =
{
  { "getBlocks", &hadoop__hdfs__get_blocks_request_proto__descriptor, &hadoop__hdfs__get_blocks_response_proto__descriptor },
  { "getBlockKeys", &hadoop__hdfs__get_block_keys_request_proto__descriptor, &hadoop__hdfs__get_block_keys_response_proto__descriptor },
  { "getTransactionId", &hadoop__hdfs__get_transaction_id_request_proto__descriptor, &hadoop__hdfs__get_transaction_id_response_proto__descriptor },
  { "getMostRecentCheckpointTxId", &hadoop__hdfs__get_most_recent_checkpoint_tx_id_request_proto__descriptor, &hadoop__hdfs__get_most_recent_checkpoint_tx_id_response_proto__descriptor },
  { "rollEditLog", &hadoop__hdfs__roll_edit_log_request_proto__descriptor, &hadoop__hdfs__roll_edit_log_response_proto__descriptor },
  { "versionRequest", &hadoop__hdfs__version_request_proto__descriptor, &hadoop__hdfs__version_response_proto__descriptor },
  { "errorReport", &hadoop__hdfs__error_report_request_proto__descriptor, &hadoop__hdfs__error_report_response_proto__descriptor },
  { "registerSubordinateNamenode", &hadoop__hdfs__register_request_proto__descriptor, &hadoop__hdfs__register_response_proto__descriptor },
  { "startCheckpoint", &hadoop__hdfs__start_checkpoint_request_proto__descriptor, &hadoop__hdfs__start_checkpoint_response_proto__descriptor },
  { "endCheckpoint", &hadoop__hdfs__end_checkpoint_request_proto__descriptor, &hadoop__hdfs__end_checkpoint_response_proto__descriptor },
  { "getEditLogManifest", &hadoop__hdfs__get_edit_log_manifest_request_proto__descriptor, &hadoop__hdfs__get_edit_log_manifest_response_proto__descriptor },
};
const unsigned hadoop__hdfs__namenode_protocol_service__method_indices_by_name[] = {
  9,        /* endCheckpoint */
  6,        /* errorReport */
  1,        /* getBlockKeys */
  0,        /* getBlocks */
  10,        /* getEditLogManifest */
  3,        /* getMostRecentCheckpointTxId */
  2,        /* getTransactionId */
  7,        /* registerSubordinateNamenode */
  4,        /* rollEditLog */
  8,        /* startCheckpoint */
  5         /* versionRequest */
};
const ProtobufCServiceDescriptor hadoop__hdfs__namenode_protocol_service__descriptor =
{
  PROTOBUF_C_SERVICE_DESCRIPTOR_MAGIC,
  "hadoop.hdfs.NamenodeProtocolService",
  "versionRequest",
  "Hadoop__Hdfs__NamenodeProtocolService",
  "hadoop.hdfs",
  11,
  hadoop__hdfs__namenode_protocol_service__method_descriptors,
  hadoop__hdfs__namenode_protocol_service__method_indices_by_name
};
void hadoop__hdfs__namenode_protocol_service__get_blocks(ProtobufCService *service,
                                                         const Hadoop__Hdfs__GetBlocksRequestProto *input,
                                                         Hadoop__Hdfs__GetBlocksResponseProto_Closure closure,
                                                         void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__hdfs__namenode_protocol_service__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__hdfs__namenode_protocol_service__get_block_keys(ProtobufCService *service,
                                                             const Hadoop__Hdfs__GetBlockKeysRequestProto *input,
                                                             Hadoop__Hdfs__GetBlockKeysResponseProto_Closure closure,
                                                             void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__hdfs__namenode_protocol_service__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__hdfs__namenode_protocol_service__get_transaction_id(ProtobufCService *service,
                                                                 const Hadoop__Hdfs__GetTransactionIdRequestProto *input,
                                                                 Hadoop__Hdfs__GetTransactionIdResponseProto_Closure closure,
                                                                 void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__hdfs__namenode_protocol_service__descriptor);
  service->invoke(service, 2, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__hdfs__namenode_protocol_service__get_most_recent_checkpoint_tx_id(ProtobufCService *service,
                                                                               const Hadoop__Hdfs__GetMostRecentCheckpointTxIdRequestProto *input,
                                                                               Hadoop__Hdfs__GetMostRecentCheckpointTxIdResponseProto_Closure closure,
                                                                               void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__hdfs__namenode_protocol_service__descriptor);
  service->invoke(service, 3, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__hdfs__namenode_protocol_service__roll_edit_log(ProtobufCService *service,
                                                            const Hadoop__Hdfs__RollEditLogRequestProto *input,
                                                            Hadoop__Hdfs__RollEditLogResponseProto_Closure closure,
                                                            void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__hdfs__namenode_protocol_service__descriptor);
  service->invoke(service, 4, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__hdfs__namenode_protocol_service__version_request(ProtobufCService *service,
                                                              const Hadoop__Hdfs__VersionRequestProto *input,
                                                              Hadoop__Hdfs__VersionResponseProto_Closure closure,
                                                              void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__hdfs__namenode_protocol_service__descriptor);
  service->invoke(service, 5, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__hdfs__namenode_protocol_service__error_report(ProtobufCService *service,
                                                           const Hadoop__Hdfs__ErrorReportRequestProto *input,
                                                           Hadoop__Hdfs__ErrorReportResponseProto_Closure closure,
                                                           void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__hdfs__namenode_protocol_service__descriptor);
  service->invoke(service, 6, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__hdfs__namenode_protocol_service__register_subordinate_namenode(ProtobufCService *service,
                                                                            const Hadoop__Hdfs__RegisterRequestProto *input,
                                                                            Hadoop__Hdfs__RegisterResponseProto_Closure closure,
                                                                            void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__hdfs__namenode_protocol_service__descriptor);
  service->invoke(service, 7, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__hdfs__namenode_protocol_service__start_checkpoint(ProtobufCService *service,
                                                               const Hadoop__Hdfs__StartCheckpointRequestProto *input,
                                                               Hadoop__Hdfs__StartCheckpointResponseProto_Closure closure,
                                                               void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__hdfs__namenode_protocol_service__descriptor);
  service->invoke(service, 8, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__hdfs__namenode_protocol_service__end_checkpoint(ProtobufCService *service,
                                                             const Hadoop__Hdfs__EndCheckpointRequestProto *input,
                                                             Hadoop__Hdfs__EndCheckpointResponseProto_Closure closure,
                                                             void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__hdfs__namenode_protocol_service__descriptor);
  service->invoke(service, 9, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__hdfs__namenode_protocol_service__get_edit_log_manifest(ProtobufCService *service,
                                                                    const Hadoop__Hdfs__GetEditLogManifestRequestProto *input,
                                                                    Hadoop__Hdfs__GetEditLogManifestResponseProto_Closure closure,
                                                                    void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__hdfs__namenode_protocol_service__descriptor);
  service->invoke(service, 10, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__hdfs__namenode_protocol_service__init (Hadoop__Hdfs__NamenodeProtocolService_Service *service,
                                                    Hadoop__Hdfs__NamenodeProtocolService_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &hadoop__hdfs__namenode_protocol_service__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
