/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "ProtocolInfo.pb-c.h"
void   hadoop__common__get_protocol_versions_request_proto__init
                     (Hadoop__Common__GetProtocolVersionsRequestProto         *message)
{
  static Hadoop__Common__GetProtocolVersionsRequestProto init_value = HADOOP__COMMON__GET_PROTOCOL_VERSIONS_REQUEST_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__common__get_protocol_versions_request_proto__get_packed_size
                     (const Hadoop__Common__GetProtocolVersionsRequestProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__get_protocol_versions_request_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__common__get_protocol_versions_request_proto__pack
                     (const Hadoop__Common__GetProtocolVersionsRequestProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__get_protocol_versions_request_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__common__get_protocol_versions_request_proto__pack_to_buffer
                     (const Hadoop__Common__GetProtocolVersionsRequestProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__get_protocol_versions_request_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Common__GetProtocolVersionsRequestProto *
       hadoop__common__get_protocol_versions_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Common__GetProtocolVersionsRequestProto *)
     protobuf_c_message_unpack (&hadoop__common__get_protocol_versions_request_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__common__get_protocol_versions_request_proto__free_unpacked
                     (Hadoop__Common__GetProtocolVersionsRequestProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__get_protocol_versions_request_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__common__protocol_version_proto__init
                     (Hadoop__Common__ProtocolVersionProto         *message)
{
  static Hadoop__Common__ProtocolVersionProto init_value = HADOOP__COMMON__PROTOCOL_VERSION_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__common__protocol_version_proto__get_packed_size
                     (const Hadoop__Common__ProtocolVersionProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__protocol_version_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__common__protocol_version_proto__pack
                     (const Hadoop__Common__ProtocolVersionProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__protocol_version_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__common__protocol_version_proto__pack_to_buffer
                     (const Hadoop__Common__ProtocolVersionProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__protocol_version_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Common__ProtocolVersionProto *
       hadoop__common__protocol_version_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Common__ProtocolVersionProto *)
     protobuf_c_message_unpack (&hadoop__common__protocol_version_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__common__protocol_version_proto__free_unpacked
                     (Hadoop__Common__ProtocolVersionProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__protocol_version_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__common__get_protocol_versions_response_proto__init
                     (Hadoop__Common__GetProtocolVersionsResponseProto         *message)
{
  static Hadoop__Common__GetProtocolVersionsResponseProto init_value = HADOOP__COMMON__GET_PROTOCOL_VERSIONS_RESPONSE_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__common__get_protocol_versions_response_proto__get_packed_size
                     (const Hadoop__Common__GetProtocolVersionsResponseProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__get_protocol_versions_response_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__common__get_protocol_versions_response_proto__pack
                     (const Hadoop__Common__GetProtocolVersionsResponseProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__get_protocol_versions_response_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__common__get_protocol_versions_response_proto__pack_to_buffer
                     (const Hadoop__Common__GetProtocolVersionsResponseProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__get_protocol_versions_response_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Common__GetProtocolVersionsResponseProto *
       hadoop__common__get_protocol_versions_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Common__GetProtocolVersionsResponseProto *)
     protobuf_c_message_unpack (&hadoop__common__get_protocol_versions_response_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__common__get_protocol_versions_response_proto__free_unpacked
                     (Hadoop__Common__GetProtocolVersionsResponseProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__get_protocol_versions_response_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__common__get_protocol_signature_request_proto__init
                     (Hadoop__Common__GetProtocolSignatureRequestProto         *message)
{
  static Hadoop__Common__GetProtocolSignatureRequestProto init_value = HADOOP__COMMON__GET_PROTOCOL_SIGNATURE_REQUEST_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__common__get_protocol_signature_request_proto__get_packed_size
                     (const Hadoop__Common__GetProtocolSignatureRequestProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__get_protocol_signature_request_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__common__get_protocol_signature_request_proto__pack
                     (const Hadoop__Common__GetProtocolSignatureRequestProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__get_protocol_signature_request_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__common__get_protocol_signature_request_proto__pack_to_buffer
                     (const Hadoop__Common__GetProtocolSignatureRequestProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__get_protocol_signature_request_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Common__GetProtocolSignatureRequestProto *
       hadoop__common__get_protocol_signature_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Common__GetProtocolSignatureRequestProto *)
     protobuf_c_message_unpack (&hadoop__common__get_protocol_signature_request_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__common__get_protocol_signature_request_proto__free_unpacked
                     (Hadoop__Common__GetProtocolSignatureRequestProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__get_protocol_signature_request_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__common__get_protocol_signature_response_proto__init
                     (Hadoop__Common__GetProtocolSignatureResponseProto         *message)
{
  static Hadoop__Common__GetProtocolSignatureResponseProto init_value = HADOOP__COMMON__GET_PROTOCOL_SIGNATURE_RESPONSE_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__common__get_protocol_signature_response_proto__get_packed_size
                     (const Hadoop__Common__GetProtocolSignatureResponseProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__get_protocol_signature_response_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__common__get_protocol_signature_response_proto__pack
                     (const Hadoop__Common__GetProtocolSignatureResponseProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__get_protocol_signature_response_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__common__get_protocol_signature_response_proto__pack_to_buffer
                     (const Hadoop__Common__GetProtocolSignatureResponseProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__get_protocol_signature_response_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Common__GetProtocolSignatureResponseProto *
       hadoop__common__get_protocol_signature_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Common__GetProtocolSignatureResponseProto *)
     protobuf_c_message_unpack (&hadoop__common__get_protocol_signature_response_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__common__get_protocol_signature_response_proto__free_unpacked
                     (Hadoop__Common__GetProtocolSignatureResponseProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__get_protocol_signature_response_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__common__protocol_signature_proto__init
                     (Hadoop__Common__ProtocolSignatureProto         *message)
{
  static Hadoop__Common__ProtocolSignatureProto init_value = HADOOP__COMMON__PROTOCOL_SIGNATURE_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__common__protocol_signature_proto__get_packed_size
                     (const Hadoop__Common__ProtocolSignatureProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__protocol_signature_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__common__protocol_signature_proto__pack
                     (const Hadoop__Common__ProtocolSignatureProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__protocol_signature_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__common__protocol_signature_proto__pack_to_buffer
                     (const Hadoop__Common__ProtocolSignatureProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__protocol_signature_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Common__ProtocolSignatureProto *
       hadoop__common__protocol_signature_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Common__ProtocolSignatureProto *)
     protobuf_c_message_unpack (&hadoop__common__protocol_signature_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__common__protocol_signature_proto__free_unpacked
                     (Hadoop__Common__ProtocolSignatureProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__protocol_signature_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor hadoop__common__get_protocol_versions_request_proto__field_descriptors[1] =
{
  {
    "protocol",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Common__GetProtocolVersionsRequestProto, protocol),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__common__get_protocol_versions_request_proto__field_indices_by_name[] = {
  0,   /* field[0] = protocol */
};
static const ProtobufCIntRange hadoop__common__get_protocol_versions_request_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor hadoop__common__get_protocol_versions_request_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.common.GetProtocolVersionsRequestProto",
  "GetProtocolVersionsRequestProto",
  "Hadoop__Common__GetProtocolVersionsRequestProto",
  "hadoop.common",
  sizeof(Hadoop__Common__GetProtocolVersionsRequestProto),
  1,
  hadoop__common__get_protocol_versions_request_proto__field_descriptors,
  hadoop__common__get_protocol_versions_request_proto__field_indices_by_name,
  1,  hadoop__common__get_protocol_versions_request_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__common__get_protocol_versions_request_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hadoop__common__protocol_version_proto__field_descriptors[2] =
{
  {
    "rpcKind",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Common__ProtocolVersionProto, rpckind),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "versions",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(Hadoop__Common__ProtocolVersionProto, n_versions),
    PROTOBUF_C_OFFSETOF(Hadoop__Common__ProtocolVersionProto, versions),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__common__protocol_version_proto__field_indices_by_name[] = {
  0,   /* field[0] = rpcKind */
  1,   /* field[1] = versions */
};
static const ProtobufCIntRange hadoop__common__protocol_version_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor hadoop__common__protocol_version_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.common.ProtocolVersionProto",
  "ProtocolVersionProto",
  "Hadoop__Common__ProtocolVersionProto",
  "hadoop.common",
  sizeof(Hadoop__Common__ProtocolVersionProto),
  2,
  hadoop__common__protocol_version_proto__field_descriptors,
  hadoop__common__protocol_version_proto__field_indices_by_name,
  1,  hadoop__common__protocol_version_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__common__protocol_version_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hadoop__common__get_protocol_versions_response_proto__field_descriptors[1] =
{
  {
    "protocolVersions",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Hadoop__Common__GetProtocolVersionsResponseProto, n_protocolversions),
    PROTOBUF_C_OFFSETOF(Hadoop__Common__GetProtocolVersionsResponseProto, protocolversions),
    &hadoop__common__protocol_version_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__common__get_protocol_versions_response_proto__field_indices_by_name[] = {
  0,   /* field[0] = protocolVersions */
};
static const ProtobufCIntRange hadoop__common__get_protocol_versions_response_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor hadoop__common__get_protocol_versions_response_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.common.GetProtocolVersionsResponseProto",
  "GetProtocolVersionsResponseProto",
  "Hadoop__Common__GetProtocolVersionsResponseProto",
  "hadoop.common",
  sizeof(Hadoop__Common__GetProtocolVersionsResponseProto),
  1,
  hadoop__common__get_protocol_versions_response_proto__field_descriptors,
  hadoop__common__get_protocol_versions_response_proto__field_indices_by_name,
  1,  hadoop__common__get_protocol_versions_response_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__common__get_protocol_versions_response_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hadoop__common__get_protocol_signature_request_proto__field_descriptors[2] =
{
  {
    "protocol",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Common__GetProtocolSignatureRequestProto, protocol),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rpcKind",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Common__GetProtocolSignatureRequestProto, rpckind),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__common__get_protocol_signature_request_proto__field_indices_by_name[] = {
  0,   /* field[0] = protocol */
  1,   /* field[1] = rpcKind */
};
static const ProtobufCIntRange hadoop__common__get_protocol_signature_request_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor hadoop__common__get_protocol_signature_request_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.common.GetProtocolSignatureRequestProto",
  "GetProtocolSignatureRequestProto",
  "Hadoop__Common__GetProtocolSignatureRequestProto",
  "hadoop.common",
  sizeof(Hadoop__Common__GetProtocolSignatureRequestProto),
  2,
  hadoop__common__get_protocol_signature_request_proto__field_descriptors,
  hadoop__common__get_protocol_signature_request_proto__field_indices_by_name,
  1,  hadoop__common__get_protocol_signature_request_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__common__get_protocol_signature_request_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hadoop__common__get_protocol_signature_response_proto__field_descriptors[1] =
{
  {
    "protocolSignature",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Hadoop__Common__GetProtocolSignatureResponseProto, n_protocolsignature),
    PROTOBUF_C_OFFSETOF(Hadoop__Common__GetProtocolSignatureResponseProto, protocolsignature),
    &hadoop__common__protocol_signature_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__common__get_protocol_signature_response_proto__field_indices_by_name[] = {
  0,   /* field[0] = protocolSignature */
};
static const ProtobufCIntRange hadoop__common__get_protocol_signature_response_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor hadoop__common__get_protocol_signature_response_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.common.GetProtocolSignatureResponseProto",
  "GetProtocolSignatureResponseProto",
  "Hadoop__Common__GetProtocolSignatureResponseProto",
  "hadoop.common",
  sizeof(Hadoop__Common__GetProtocolSignatureResponseProto),
  1,
  hadoop__common__get_protocol_signature_response_proto__field_descriptors,
  hadoop__common__get_protocol_signature_response_proto__field_indices_by_name,
  1,  hadoop__common__get_protocol_signature_response_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__common__get_protocol_signature_response_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hadoop__common__protocol_signature_proto__field_descriptors[2] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Common__ProtocolSignatureProto, version),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "methods",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Hadoop__Common__ProtocolSignatureProto, n_methods),
    PROTOBUF_C_OFFSETOF(Hadoop__Common__ProtocolSignatureProto, methods),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__common__protocol_signature_proto__field_indices_by_name[] = {
  1,   /* field[1] = methods */
  0,   /* field[0] = version */
};
static const ProtobufCIntRange hadoop__common__protocol_signature_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor hadoop__common__protocol_signature_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.common.ProtocolSignatureProto",
  "ProtocolSignatureProto",
  "Hadoop__Common__ProtocolSignatureProto",
  "hadoop.common",
  sizeof(Hadoop__Common__ProtocolSignatureProto),
  2,
  hadoop__common__protocol_signature_proto__field_descriptors,
  hadoop__common__protocol_signature_proto__field_indices_by_name,
  1,  hadoop__common__protocol_signature_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__common__protocol_signature_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor hadoop__common__protocol_info_service__method_descriptors[2] =
{
  { "getProtocolVersions", &hadoop__common__get_protocol_versions_request_proto__descriptor, &hadoop__common__get_protocol_versions_response_proto__descriptor },
  { "getProtocolSignature", &hadoop__common__get_protocol_signature_request_proto__descriptor, &hadoop__common__get_protocol_signature_response_proto__descriptor },
};
const unsigned hadoop__common__protocol_info_service__method_indices_by_name[] = {
  1,        /* getProtocolSignature */
  0         /* getProtocolVersions */
};
const ProtobufCServiceDescriptor hadoop__common__protocol_info_service__descriptor =
{
  PROTOBUF_C_SERVICE_DESCRIPTOR_MAGIC,
  "hadoop.common.ProtocolInfoService",
  "getProtocolVersions",
  "Hadoop__Common__ProtocolInfoService",
  "hadoop.common",
  2,
  hadoop__common__protocol_info_service__method_descriptors,
  hadoop__common__protocol_info_service__method_indices_by_name
};
void hadoop__common__protocol_info_service__get_protocol_versions(ProtobufCService *service,
                                                                  const Hadoop__Common__GetProtocolVersionsRequestProto *input,
                                                                  Hadoop__Common__GetProtocolVersionsResponseProto_Closure closure,
                                                                  void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__common__protocol_info_service__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__common__protocol_info_service__get_protocol_signature(ProtobufCService *service,
                                                                   const Hadoop__Common__GetProtocolSignatureRequestProto *input,
                                                                   Hadoop__Common__GetProtocolSignatureResponseProto_Closure closure,
                                                                   void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__common__protocol_info_service__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__common__protocol_info_service__init (Hadoop__Common__ProtocolInfoService_Service *service,
                                                  Hadoop__Common__ProtocolInfoService_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &hadoop__common__protocol_info_service__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
