/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "RefreshAuthorizationPolicyProtocol.pb-c.h"
void   hadoop__common__refresh_service_acl_request_proto__init
                     (Hadoop__Common__RefreshServiceAclRequestProto         *message)
{
  static Hadoop__Common__RefreshServiceAclRequestProto init_value = HADOOP__COMMON__REFRESH_SERVICE_ACL_REQUEST_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__common__refresh_service_acl_request_proto__get_packed_size
                     (const Hadoop__Common__RefreshServiceAclRequestProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__refresh_service_acl_request_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__common__refresh_service_acl_request_proto__pack
                     (const Hadoop__Common__RefreshServiceAclRequestProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__refresh_service_acl_request_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__common__refresh_service_acl_request_proto__pack_to_buffer
                     (const Hadoop__Common__RefreshServiceAclRequestProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__refresh_service_acl_request_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Common__RefreshServiceAclRequestProto *
       hadoop__common__refresh_service_acl_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Common__RefreshServiceAclRequestProto *)
     protobuf_c_message_unpack (&hadoop__common__refresh_service_acl_request_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__common__refresh_service_acl_request_proto__free_unpacked
                     (Hadoop__Common__RefreshServiceAclRequestProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__refresh_service_acl_request_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__common__refresh_service_acl_response_proto__init
                     (Hadoop__Common__RefreshServiceAclResponseProto         *message)
{
  static Hadoop__Common__RefreshServiceAclResponseProto init_value = HADOOP__COMMON__REFRESH_SERVICE_ACL_RESPONSE_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__common__refresh_service_acl_response_proto__get_packed_size
                     (const Hadoop__Common__RefreshServiceAclResponseProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__refresh_service_acl_response_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__common__refresh_service_acl_response_proto__pack
                     (const Hadoop__Common__RefreshServiceAclResponseProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__refresh_service_acl_response_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__common__refresh_service_acl_response_proto__pack_to_buffer
                     (const Hadoop__Common__RefreshServiceAclResponseProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__refresh_service_acl_response_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Common__RefreshServiceAclResponseProto *
       hadoop__common__refresh_service_acl_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Common__RefreshServiceAclResponseProto *)
     protobuf_c_message_unpack (&hadoop__common__refresh_service_acl_response_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__common__refresh_service_acl_response_proto__free_unpacked
                     (Hadoop__Common__RefreshServiceAclResponseProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__refresh_service_acl_response_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
#define hadoop__common__refresh_service_acl_request_proto__field_descriptors NULL
#define hadoop__common__refresh_service_acl_request_proto__field_indices_by_name NULL
#define hadoop__common__refresh_service_acl_request_proto__number_ranges NULL
const ProtobufCMessageDescriptor hadoop__common__refresh_service_acl_request_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.common.RefreshServiceAclRequestProto",
  "RefreshServiceAclRequestProto",
  "Hadoop__Common__RefreshServiceAclRequestProto",
  "hadoop.common",
  sizeof(Hadoop__Common__RefreshServiceAclRequestProto),
  0,
  hadoop__common__refresh_service_acl_request_proto__field_descriptors,
  hadoop__common__refresh_service_acl_request_proto__field_indices_by_name,
  0,  hadoop__common__refresh_service_acl_request_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__common__refresh_service_acl_request_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define hadoop__common__refresh_service_acl_response_proto__field_descriptors NULL
#define hadoop__common__refresh_service_acl_response_proto__field_indices_by_name NULL
#define hadoop__common__refresh_service_acl_response_proto__number_ranges NULL
const ProtobufCMessageDescriptor hadoop__common__refresh_service_acl_response_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.common.RefreshServiceAclResponseProto",
  "RefreshServiceAclResponseProto",
  "Hadoop__Common__RefreshServiceAclResponseProto",
  "hadoop.common",
  sizeof(Hadoop__Common__RefreshServiceAclResponseProto),
  0,
  hadoop__common__refresh_service_acl_response_proto__field_descriptors,
  hadoop__common__refresh_service_acl_response_proto__field_indices_by_name,
  0,  hadoop__common__refresh_service_acl_response_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__common__refresh_service_acl_response_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor hadoop__common__refresh_authorization_policy_protocol_service__method_descriptors[1] =
{
  { "refreshServiceAcl", &hadoop__common__refresh_service_acl_request_proto__descriptor, &hadoop__common__refresh_service_acl_response_proto__descriptor },
};
const unsigned hadoop__common__refresh_authorization_policy_protocol_service__method_indices_by_name[] = {
  0         /* refreshServiceAcl */
};
const ProtobufCServiceDescriptor hadoop__common__refresh_authorization_policy_protocol_service__descriptor =
{
  PROTOBUF_C_SERVICE_DESCRIPTOR_MAGIC,
  "hadoop.common.RefreshAuthorizationPolicyProtocolService",
  "refreshServiceAcl",
  "Hadoop__Common__RefreshAuthorizationPolicyProtocolService",
  "hadoop.common",
  1,
  hadoop__common__refresh_authorization_policy_protocol_service__method_descriptors,
  hadoop__common__refresh_authorization_policy_protocol_service__method_indices_by_name
};
void hadoop__common__refresh_authorization_policy_protocol_service__refresh_service_acl(ProtobufCService *service,
                                                                                        const Hadoop__Common__RefreshServiceAclRequestProto *input,
                                                                                        Hadoop__Common__RefreshServiceAclResponseProto_Closure closure,
                                                                                        void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__common__refresh_authorization_policy_protocol_service__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__common__refresh_authorization_policy_protocol_service__init (Hadoop__Common__RefreshAuthorizationPolicyProtocolService_Service *service,
                                                                          Hadoop__Common__RefreshAuthorizationPolicyProtocolService_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &hadoop__common__refresh_authorization_policy_protocol_service__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
