/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "resourcemanager_administration_protocol.pb-c.h"
static const ProtobufCMethodDescriptor hadoop__yarn__resource_manager_administration_protocol_service__method_descriptors[7] =
{
  { "refreshQueues", &hadoop__yarn__refresh_queues_request_proto__descriptor, &hadoop__yarn__refresh_queues_response_proto__descriptor },
  { "refreshNodes", &hadoop__yarn__refresh_nodes_request_proto__descriptor, &hadoop__yarn__refresh_nodes_response_proto__descriptor },
  { "refreshSuperUserGroupsConfiguration", &hadoop__yarn__refresh_super_user_groups_configuration_request_proto__descriptor, &hadoop__yarn__refresh_super_user_groups_configuration_response_proto__descriptor },
  { "refreshUserToGroupsMappings", &hadoop__yarn__refresh_user_to_groups_mappings_request_proto__descriptor, &hadoop__yarn__refresh_user_to_groups_mappings_response_proto__descriptor },
  { "refreshAdminAcls", &hadoop__yarn__refresh_admin_acls_request_proto__descriptor, &hadoop__yarn__refresh_admin_acls_response_proto__descriptor },
  { "refreshServiceAcls", &hadoop__yarn__refresh_service_acls_request_proto__descriptor, &hadoop__yarn__refresh_service_acls_response_proto__descriptor },
  { "getGroupsForUser", &hadoop__yarn__get_groups_for_user_request_proto__descriptor, &hadoop__yarn__get_groups_for_user_response_proto__descriptor },
};
const unsigned hadoop__yarn__resource_manager_administration_protocol_service__method_indices_by_name[] = {
  6,        /* getGroupsForUser */
  4,        /* refreshAdminAcls */
  1,        /* refreshNodes */
  0,        /* refreshQueues */
  5,        /* refreshServiceAcls */
  2,        /* refreshSuperUserGroupsConfiguration */
  3         /* refreshUserToGroupsMappings */
};
const ProtobufCServiceDescriptor hadoop__yarn__resource_manager_administration_protocol_service__descriptor =
{
  PROTOBUF_C_SERVICE_DESCRIPTOR_MAGIC,
  "hadoop.yarn.ResourceManagerAdministrationProtocolService",
  "refreshUserToGroupsMappings",
  "Hadoop__Yarn__ResourceManagerAdministrationProtocolService",
  "hadoop.yarn",
  7,
  hadoop__yarn__resource_manager_administration_protocol_service__method_descriptors,
  hadoop__yarn__resource_manager_administration_protocol_service__method_indices_by_name
};
void hadoop__yarn__resource_manager_administration_protocol_service__refresh_queues(ProtobufCService *service,
                                                                                    const Hadoop__Yarn__RefreshQueuesRequestProto *input,
                                                                                    Hadoop__Yarn__RefreshQueuesResponseProto_Closure closure,
                                                                                    void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__yarn__resource_manager_administration_protocol_service__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__yarn__resource_manager_administration_protocol_service__refresh_nodes(ProtobufCService *service,
                                                                                   const Hadoop__Yarn__RefreshNodesRequestProto *input,
                                                                                   Hadoop__Yarn__RefreshNodesResponseProto_Closure closure,
                                                                                   void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__yarn__resource_manager_administration_protocol_service__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__yarn__resource_manager_administration_protocol_service__refresh_super_user_groups_configuration(ProtobufCService *service,
                                                                                                             const Hadoop__Yarn__RefreshSuperUserGroupsConfigurationRequestProto *input,
                                                                                                             Hadoop__Yarn__RefreshSuperUserGroupsConfigurationResponseProto_Closure closure,
                                                                                                             void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__yarn__resource_manager_administration_protocol_service__descriptor);
  service->invoke(service, 2, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__yarn__resource_manager_administration_protocol_service__refresh_user_to_groups_mappings(ProtobufCService *service,
                                                                                                     const Hadoop__Yarn__RefreshUserToGroupsMappingsRequestProto *input,
                                                                                                     Hadoop__Yarn__RefreshUserToGroupsMappingsResponseProto_Closure closure,
                                                                                                     void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__yarn__resource_manager_administration_protocol_service__descriptor);
  service->invoke(service, 3, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__yarn__resource_manager_administration_protocol_service__refresh_admin_acls(ProtobufCService *service,
                                                                                        const Hadoop__Yarn__RefreshAdminAclsRequestProto *input,
                                                                                        Hadoop__Yarn__RefreshAdminAclsResponseProto_Closure closure,
                                                                                        void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__yarn__resource_manager_administration_protocol_service__descriptor);
  service->invoke(service, 4, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__yarn__resource_manager_administration_protocol_service__refresh_service_acls(ProtobufCService *service,
                                                                                          const Hadoop__Yarn__RefreshServiceAclsRequestProto *input,
                                                                                          Hadoop__Yarn__RefreshServiceAclsResponseProto_Closure closure,
                                                                                          void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__yarn__resource_manager_administration_protocol_service__descriptor);
  service->invoke(service, 5, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__yarn__resource_manager_administration_protocol_service__get_groups_for_user(ProtobufCService *service,
                                                                                         const Hadoop__Yarn__GetGroupsForUserRequestProto *input,
                                                                                         Hadoop__Yarn__GetGroupsForUserResponseProto_Closure closure,
                                                                                         void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__yarn__resource_manager_administration_protocol_service__descriptor);
  service->invoke(service, 6, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__yarn__resource_manager_administration_protocol_service__init (Hadoop__Yarn__ResourceManagerAdministrationProtocolService_Service *service,
                                                                           Hadoop__Yarn__ResourceManagerAdministrationProtocolService_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &hadoop__yarn__resource_manager_administration_protocol_service__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
