/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "ResourceTracker.pb-c.h"
static const ProtobufCMethodDescriptor hadoop__yarn__resource_tracker_service__method_descriptors[2] =
{
  { "registerNodeManager", &hadoop__yarn__register_node_manager_request_proto__descriptor, &hadoop__yarn__register_node_manager_response_proto__descriptor },
  { "nodeHeartbeat", &hadoop__yarn__node_heartbeat_request_proto__descriptor, &hadoop__yarn__node_heartbeat_response_proto__descriptor },
};
const unsigned hadoop__yarn__resource_tracker_service__method_indices_by_name[] = {
  1,        /* nodeHeartbeat */
  0         /* registerNodeManager */
};
const ProtobufCServiceDescriptor hadoop__yarn__resource_tracker_service__descriptor =
{
  PROTOBUF_C_SERVICE_DESCRIPTOR_MAGIC,
  "hadoop.yarn.ResourceTrackerService",
  "registerNodeManager",
  "Hadoop__Yarn__ResourceTrackerService",
  "hadoop.yarn",
  2,
  hadoop__yarn__resource_tracker_service__method_descriptors,
  hadoop__yarn__resource_tracker_service__method_indices_by_name
};
void hadoop__yarn__resource_tracker_service__register_node_manager(ProtobufCService *service,
                                                                   const Hadoop__Yarn__RegisterNodeManagerRequestProto *input,
                                                                   Hadoop__Yarn__RegisterNodeManagerResponseProto_Closure closure,
                                                                   void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__yarn__resource_tracker_service__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__yarn__resource_tracker_service__node_heartbeat(ProtobufCService *service,
                                                            const Hadoop__Yarn__NodeHeartbeatRequestProto *input,
                                                            Hadoop__Yarn__NodeHeartbeatResponseProto_Closure closure,
                                                            void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &hadoop__yarn__resource_tracker_service__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hadoop__yarn__resource_tracker_service__init (Hadoop__Yarn__ResourceTrackerService_Service *service,
                                                   Hadoop__Yarn__ResourceTrackerService_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &hadoop__yarn__resource_tracker_service__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
