/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "Security.pb-c.h"
void   hadoop__common__token_proto__init
                     (Hadoop__Common__TokenProto         *message)
{
  static Hadoop__Common__TokenProto init_value = HADOOP__COMMON__TOKEN_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__common__token_proto__get_packed_size
                     (const Hadoop__Common__TokenProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__token_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__common__token_proto__pack
                     (const Hadoop__Common__TokenProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__token_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__common__token_proto__pack_to_buffer
                     (const Hadoop__Common__TokenProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__token_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Common__TokenProto *
       hadoop__common__token_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Common__TokenProto *)
     protobuf_c_message_unpack (&hadoop__common__token_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__common__token_proto__free_unpacked
                     (Hadoop__Common__TokenProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__token_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__common__get_delegation_token_request_proto__init
                     (Hadoop__Common__GetDelegationTokenRequestProto         *message)
{
  static Hadoop__Common__GetDelegationTokenRequestProto init_value = HADOOP__COMMON__GET_DELEGATION_TOKEN_REQUEST_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__common__get_delegation_token_request_proto__get_packed_size
                     (const Hadoop__Common__GetDelegationTokenRequestProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__get_delegation_token_request_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__common__get_delegation_token_request_proto__pack
                     (const Hadoop__Common__GetDelegationTokenRequestProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__get_delegation_token_request_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__common__get_delegation_token_request_proto__pack_to_buffer
                     (const Hadoop__Common__GetDelegationTokenRequestProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__get_delegation_token_request_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Common__GetDelegationTokenRequestProto *
       hadoop__common__get_delegation_token_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Common__GetDelegationTokenRequestProto *)
     protobuf_c_message_unpack (&hadoop__common__get_delegation_token_request_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__common__get_delegation_token_request_proto__free_unpacked
                     (Hadoop__Common__GetDelegationTokenRequestProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__get_delegation_token_request_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__common__get_delegation_token_response_proto__init
                     (Hadoop__Common__GetDelegationTokenResponseProto         *message)
{
  static Hadoop__Common__GetDelegationTokenResponseProto init_value = HADOOP__COMMON__GET_DELEGATION_TOKEN_RESPONSE_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__common__get_delegation_token_response_proto__get_packed_size
                     (const Hadoop__Common__GetDelegationTokenResponseProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__get_delegation_token_response_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__common__get_delegation_token_response_proto__pack
                     (const Hadoop__Common__GetDelegationTokenResponseProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__get_delegation_token_response_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__common__get_delegation_token_response_proto__pack_to_buffer
                     (const Hadoop__Common__GetDelegationTokenResponseProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__get_delegation_token_response_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Common__GetDelegationTokenResponseProto *
       hadoop__common__get_delegation_token_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Common__GetDelegationTokenResponseProto *)
     protobuf_c_message_unpack (&hadoop__common__get_delegation_token_response_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__common__get_delegation_token_response_proto__free_unpacked
                     (Hadoop__Common__GetDelegationTokenResponseProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__get_delegation_token_response_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__common__renew_delegation_token_request_proto__init
                     (Hadoop__Common__RenewDelegationTokenRequestProto         *message)
{
  static Hadoop__Common__RenewDelegationTokenRequestProto init_value = HADOOP__COMMON__RENEW_DELEGATION_TOKEN_REQUEST_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__common__renew_delegation_token_request_proto__get_packed_size
                     (const Hadoop__Common__RenewDelegationTokenRequestProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__renew_delegation_token_request_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__common__renew_delegation_token_request_proto__pack
                     (const Hadoop__Common__RenewDelegationTokenRequestProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__renew_delegation_token_request_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__common__renew_delegation_token_request_proto__pack_to_buffer
                     (const Hadoop__Common__RenewDelegationTokenRequestProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__renew_delegation_token_request_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Common__RenewDelegationTokenRequestProto *
       hadoop__common__renew_delegation_token_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Common__RenewDelegationTokenRequestProto *)
     protobuf_c_message_unpack (&hadoop__common__renew_delegation_token_request_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__common__renew_delegation_token_request_proto__free_unpacked
                     (Hadoop__Common__RenewDelegationTokenRequestProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__renew_delegation_token_request_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__common__renew_delegation_token_response_proto__init
                     (Hadoop__Common__RenewDelegationTokenResponseProto         *message)
{
  static Hadoop__Common__RenewDelegationTokenResponseProto init_value = HADOOP__COMMON__RENEW_DELEGATION_TOKEN_RESPONSE_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__common__renew_delegation_token_response_proto__get_packed_size
                     (const Hadoop__Common__RenewDelegationTokenResponseProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__renew_delegation_token_response_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__common__renew_delegation_token_response_proto__pack
                     (const Hadoop__Common__RenewDelegationTokenResponseProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__renew_delegation_token_response_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__common__renew_delegation_token_response_proto__pack_to_buffer
                     (const Hadoop__Common__RenewDelegationTokenResponseProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__renew_delegation_token_response_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Common__RenewDelegationTokenResponseProto *
       hadoop__common__renew_delegation_token_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Common__RenewDelegationTokenResponseProto *)
     protobuf_c_message_unpack (&hadoop__common__renew_delegation_token_response_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__common__renew_delegation_token_response_proto__free_unpacked
                     (Hadoop__Common__RenewDelegationTokenResponseProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__renew_delegation_token_response_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__common__cancel_delegation_token_request_proto__init
                     (Hadoop__Common__CancelDelegationTokenRequestProto         *message)
{
  static Hadoop__Common__CancelDelegationTokenRequestProto init_value = HADOOP__COMMON__CANCEL_DELEGATION_TOKEN_REQUEST_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__common__cancel_delegation_token_request_proto__get_packed_size
                     (const Hadoop__Common__CancelDelegationTokenRequestProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__cancel_delegation_token_request_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__common__cancel_delegation_token_request_proto__pack
                     (const Hadoop__Common__CancelDelegationTokenRequestProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__cancel_delegation_token_request_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__common__cancel_delegation_token_request_proto__pack_to_buffer
                     (const Hadoop__Common__CancelDelegationTokenRequestProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__cancel_delegation_token_request_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Common__CancelDelegationTokenRequestProto *
       hadoop__common__cancel_delegation_token_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Common__CancelDelegationTokenRequestProto *)
     protobuf_c_message_unpack (&hadoop__common__cancel_delegation_token_request_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__common__cancel_delegation_token_request_proto__free_unpacked
                     (Hadoop__Common__CancelDelegationTokenRequestProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__cancel_delegation_token_request_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__common__cancel_delegation_token_response_proto__init
                     (Hadoop__Common__CancelDelegationTokenResponseProto         *message)
{
  static Hadoop__Common__CancelDelegationTokenResponseProto init_value = HADOOP__COMMON__CANCEL_DELEGATION_TOKEN_RESPONSE_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__common__cancel_delegation_token_response_proto__get_packed_size
                     (const Hadoop__Common__CancelDelegationTokenResponseProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__cancel_delegation_token_response_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__common__cancel_delegation_token_response_proto__pack
                     (const Hadoop__Common__CancelDelegationTokenResponseProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__cancel_delegation_token_response_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__common__cancel_delegation_token_response_proto__pack_to_buffer
                     (const Hadoop__Common__CancelDelegationTokenResponseProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__cancel_delegation_token_response_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Common__CancelDelegationTokenResponseProto *
       hadoop__common__cancel_delegation_token_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Common__CancelDelegationTokenResponseProto *)
     protobuf_c_message_unpack (&hadoop__common__cancel_delegation_token_response_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__common__cancel_delegation_token_response_proto__free_unpacked
                     (Hadoop__Common__CancelDelegationTokenResponseProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__common__cancel_delegation_token_response_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor hadoop__common__token_proto__field_descriptors[4] =
{
  {
    "identifier",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Common__TokenProto, identifier),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "password",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Common__TokenProto, password),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kind",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Common__TokenProto, kind),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "service",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Common__TokenProto, service),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__common__token_proto__field_indices_by_name[] = {
  0,   /* field[0] = identifier */
  2,   /* field[2] = kind */
  1,   /* field[1] = password */
  3,   /* field[3] = service */
};
static const ProtobufCIntRange hadoop__common__token_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor hadoop__common__token_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.common.TokenProto",
  "TokenProto",
  "Hadoop__Common__TokenProto",
  "hadoop.common",
  sizeof(Hadoop__Common__TokenProto),
  4,
  hadoop__common__token_proto__field_descriptors,
  hadoop__common__token_proto__field_indices_by_name,
  1,  hadoop__common__token_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__common__token_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hadoop__common__get_delegation_token_request_proto__field_descriptors[1] =
{
  {
    "renewer",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Common__GetDelegationTokenRequestProto, renewer),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__common__get_delegation_token_request_proto__field_indices_by_name[] = {
  0,   /* field[0] = renewer */
};
static const ProtobufCIntRange hadoop__common__get_delegation_token_request_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor hadoop__common__get_delegation_token_request_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.common.GetDelegationTokenRequestProto",
  "GetDelegationTokenRequestProto",
  "Hadoop__Common__GetDelegationTokenRequestProto",
  "hadoop.common",
  sizeof(Hadoop__Common__GetDelegationTokenRequestProto),
  1,
  hadoop__common__get_delegation_token_request_proto__field_descriptors,
  hadoop__common__get_delegation_token_request_proto__field_indices_by_name,
  1,  hadoop__common__get_delegation_token_request_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__common__get_delegation_token_request_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hadoop__common__get_delegation_token_response_proto__field_descriptors[1] =
{
  {
    "token",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Common__GetDelegationTokenResponseProto, token),
    &hadoop__common__token_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__common__get_delegation_token_response_proto__field_indices_by_name[] = {
  0,   /* field[0] = token */
};
static const ProtobufCIntRange hadoop__common__get_delegation_token_response_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor hadoop__common__get_delegation_token_response_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.common.GetDelegationTokenResponseProto",
  "GetDelegationTokenResponseProto",
  "Hadoop__Common__GetDelegationTokenResponseProto",
  "hadoop.common",
  sizeof(Hadoop__Common__GetDelegationTokenResponseProto),
  1,
  hadoop__common__get_delegation_token_response_proto__field_descriptors,
  hadoop__common__get_delegation_token_response_proto__field_indices_by_name,
  1,  hadoop__common__get_delegation_token_response_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__common__get_delegation_token_response_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hadoop__common__renew_delegation_token_request_proto__field_descriptors[1] =
{
  {
    "token",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Common__RenewDelegationTokenRequestProto, token),
    &hadoop__common__token_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__common__renew_delegation_token_request_proto__field_indices_by_name[] = {
  0,   /* field[0] = token */
};
static const ProtobufCIntRange hadoop__common__renew_delegation_token_request_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor hadoop__common__renew_delegation_token_request_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.common.RenewDelegationTokenRequestProto",
  "RenewDelegationTokenRequestProto",
  "Hadoop__Common__RenewDelegationTokenRequestProto",
  "hadoop.common",
  sizeof(Hadoop__Common__RenewDelegationTokenRequestProto),
  1,
  hadoop__common__renew_delegation_token_request_proto__field_descriptors,
  hadoop__common__renew_delegation_token_request_proto__field_indices_by_name,
  1,  hadoop__common__renew_delegation_token_request_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__common__renew_delegation_token_request_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hadoop__common__renew_delegation_token_response_proto__field_descriptors[1] =
{
  {
    "newExpiryTime",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Common__RenewDelegationTokenResponseProto, newexpirytime),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__common__renew_delegation_token_response_proto__field_indices_by_name[] = {
  0,   /* field[0] = newExpiryTime */
};
static const ProtobufCIntRange hadoop__common__renew_delegation_token_response_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor hadoop__common__renew_delegation_token_response_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.common.RenewDelegationTokenResponseProto",
  "RenewDelegationTokenResponseProto",
  "Hadoop__Common__RenewDelegationTokenResponseProto",
  "hadoop.common",
  sizeof(Hadoop__Common__RenewDelegationTokenResponseProto),
  1,
  hadoop__common__renew_delegation_token_response_proto__field_descriptors,
  hadoop__common__renew_delegation_token_response_proto__field_indices_by_name,
  1,  hadoop__common__renew_delegation_token_response_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__common__renew_delegation_token_response_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hadoop__common__cancel_delegation_token_request_proto__field_descriptors[1] =
{
  {
    "token",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Common__CancelDelegationTokenRequestProto, token),
    &hadoop__common__token_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__common__cancel_delegation_token_request_proto__field_indices_by_name[] = {
  0,   /* field[0] = token */
};
static const ProtobufCIntRange hadoop__common__cancel_delegation_token_request_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor hadoop__common__cancel_delegation_token_request_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.common.CancelDelegationTokenRequestProto",
  "CancelDelegationTokenRequestProto",
  "Hadoop__Common__CancelDelegationTokenRequestProto",
  "hadoop.common",
  sizeof(Hadoop__Common__CancelDelegationTokenRequestProto),
  1,
  hadoop__common__cancel_delegation_token_request_proto__field_descriptors,
  hadoop__common__cancel_delegation_token_request_proto__field_indices_by_name,
  1,  hadoop__common__cancel_delegation_token_request_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__common__cancel_delegation_token_request_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define hadoop__common__cancel_delegation_token_response_proto__field_descriptors NULL
#define hadoop__common__cancel_delegation_token_response_proto__field_indices_by_name NULL
#define hadoop__common__cancel_delegation_token_response_proto__number_ranges NULL
const ProtobufCMessageDescriptor hadoop__common__cancel_delegation_token_response_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.common.CancelDelegationTokenResponseProto",
  "CancelDelegationTokenResponseProto",
  "Hadoop__Common__CancelDelegationTokenResponseProto",
  "hadoop.common",
  sizeof(Hadoop__Common__CancelDelegationTokenResponseProto),
  0,
  hadoop__common__cancel_delegation_token_response_proto__field_descriptors,
  hadoop__common__cancel_delegation_token_response_proto__field_indices_by_name,
  0,  hadoop__common__cancel_delegation_token_response_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__common__cancel_delegation_token_response_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
