/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_test_2eproto__INCLUDED
#define PROTOBUF_C_test_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _Hadoop__Common__EmptyRequestProto Hadoop__Common__EmptyRequestProto;
typedef struct _Hadoop__Common__EmptyResponseProto Hadoop__Common__EmptyResponseProto;
typedef struct _Hadoop__Common__EchoRequestProto Hadoop__Common__EchoRequestProto;
typedef struct _Hadoop__Common__EchoResponseProto Hadoop__Common__EchoResponseProto;


/* --- enums --- */


/* --- messages --- */

struct  _Hadoop__Common__EmptyRequestProto
{
  ProtobufCMessage base;
};
#define HADOOP__COMMON__EMPTY_REQUEST_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__common__empty_request_proto__descriptor) \
     }


struct  _Hadoop__Common__EmptyResponseProto
{
  ProtobufCMessage base;
};
#define HADOOP__COMMON__EMPTY_RESPONSE_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__common__empty_response_proto__descriptor) \
     }


struct  _Hadoop__Common__EchoRequestProto
{
  ProtobufCMessage base;
  char *message;
};
#define HADOOP__COMMON__ECHO_REQUEST_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__common__echo_request_proto__descriptor) \
    , NULL }


struct  _Hadoop__Common__EchoResponseProto
{
  ProtobufCMessage base;
  char *message;
};
#define HADOOP__COMMON__ECHO_RESPONSE_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__common__echo_response_proto__descriptor) \
    , NULL }


/* Hadoop__Common__EmptyRequestProto methods */
void   hadoop__common__empty_request_proto__init
                     (Hadoop__Common__EmptyRequestProto         *message);
size_t hadoop__common__empty_request_proto__get_packed_size
                     (const Hadoop__Common__EmptyRequestProto   *message);
size_t hadoop__common__empty_request_proto__pack
                     (const Hadoop__Common__EmptyRequestProto   *message,
                      uint8_t             *out);
size_t hadoop__common__empty_request_proto__pack_to_buffer
                     (const Hadoop__Common__EmptyRequestProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Common__EmptyRequestProto *
       hadoop__common__empty_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__common__empty_request_proto__free_unpacked
                     (Hadoop__Common__EmptyRequestProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Common__EmptyResponseProto methods */
void   hadoop__common__empty_response_proto__init
                     (Hadoop__Common__EmptyResponseProto         *message);
size_t hadoop__common__empty_response_proto__get_packed_size
                     (const Hadoop__Common__EmptyResponseProto   *message);
size_t hadoop__common__empty_response_proto__pack
                     (const Hadoop__Common__EmptyResponseProto   *message,
                      uint8_t             *out);
size_t hadoop__common__empty_response_proto__pack_to_buffer
                     (const Hadoop__Common__EmptyResponseProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Common__EmptyResponseProto *
       hadoop__common__empty_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__common__empty_response_proto__free_unpacked
                     (Hadoop__Common__EmptyResponseProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Common__EchoRequestProto methods */
void   hadoop__common__echo_request_proto__init
                     (Hadoop__Common__EchoRequestProto         *message);
size_t hadoop__common__echo_request_proto__get_packed_size
                     (const Hadoop__Common__EchoRequestProto   *message);
size_t hadoop__common__echo_request_proto__pack
                     (const Hadoop__Common__EchoRequestProto   *message,
                      uint8_t             *out);
size_t hadoop__common__echo_request_proto__pack_to_buffer
                     (const Hadoop__Common__EchoRequestProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Common__EchoRequestProto *
       hadoop__common__echo_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__common__echo_request_proto__free_unpacked
                     (Hadoop__Common__EchoRequestProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Common__EchoResponseProto methods */
void   hadoop__common__echo_response_proto__init
                     (Hadoop__Common__EchoResponseProto         *message);
size_t hadoop__common__echo_response_proto__get_packed_size
                     (const Hadoop__Common__EchoResponseProto   *message);
size_t hadoop__common__echo_response_proto__pack
                     (const Hadoop__Common__EchoResponseProto   *message,
                      uint8_t             *out);
size_t hadoop__common__echo_response_proto__pack_to_buffer
                     (const Hadoop__Common__EchoResponseProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Common__EchoResponseProto *
       hadoop__common__echo_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__common__echo_response_proto__free_unpacked
                     (Hadoop__Common__EchoResponseProto *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Hadoop__Common__EmptyRequestProto_Closure)
                 (const Hadoop__Common__EmptyRequestProto *message,
                  void *closure_data);
typedef void (*Hadoop__Common__EmptyResponseProto_Closure)
                 (const Hadoop__Common__EmptyResponseProto *message,
                  void *closure_data);
typedef void (*Hadoop__Common__EchoRequestProto_Closure)
                 (const Hadoop__Common__EchoRequestProto *message,
                  void *closure_data);
typedef void (*Hadoop__Common__EchoResponseProto_Closure)
                 (const Hadoop__Common__EchoResponseProto *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor hadoop__common__empty_request_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__common__empty_response_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__common__echo_request_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__common__echo_response_proto__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_test_2eproto__INCLUDED */
