/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_yarn_5fserver_5fnodemanager_5fservice_5fprotos_2eproto__INCLUDED
#define PROTOBUF_C_yarn_5fserver_5fnodemanager_5fservice_5fprotos_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS

#include "yarn_protos.pb-c.h"

typedef struct _LocalResourceStatusProto LocalResourceStatusProto;
typedef struct _LocalizerStatusProto LocalizerStatusProto;
typedef struct _ResourceLocalizationSpecProto ResourceLocalizationSpecProto;
typedef struct _LocalizerHeartbeatResponseProto LocalizerHeartbeatResponseProto;


/* --- enums --- */

typedef enum _ResourceStatusTypeProto {
  RESOURCE_STATUS_TYPE_PROTO__FETCH_PENDING = 1,
  RESOURCE_STATUS_TYPE_PROTO__FETCH_SUCCESS = 2,
  RESOURCE_STATUS_TYPE_PROTO__FETCH_FAILURE = 3
} ResourceStatusTypeProto;
typedef enum _LocalizerActionProto {
  LOCALIZER_ACTION_PROTO__LIVE = 1,
  LOCALIZER_ACTION_PROTO__DIE = 2
} LocalizerActionProto;

/* --- messages --- */

struct  _LocalResourceStatusProto
{
  ProtobufCMessage base;
  LocalResourceProto *resource;
  protobuf_c_boolean has_status;
  ResourceStatusTypeProto status;
  URLProto *localpath;
  protobuf_c_boolean has_localsize;
  int64_t localsize;
  SerializedExceptionProto *exception;
};
#define LOCAL_RESOURCE_STATUS_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&local_resource_status_proto__descriptor) \
    , NULL, 0,0, NULL, 0,0, NULL }


struct  _LocalizerStatusProto
{
  ProtobufCMessage base;
  char *localizer_id;
  size_t n_resources;
  LocalResourceStatusProto **resources;
};
#define LOCALIZER_STATUS_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&localizer_status_proto__descriptor) \
    , NULL, 0,NULL }


struct  _ResourceLocalizationSpecProto
{
  ProtobufCMessage base;
  LocalResourceProto *resource;
  URLProto *destination_directory;
};
#define RESOURCE_LOCALIZATION_SPEC_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&resource_localization_spec_proto__descriptor) \
    , NULL, NULL }


struct  _LocalizerHeartbeatResponseProto
{
  ProtobufCMessage base;
  protobuf_c_boolean has_action;
  LocalizerActionProto action;
  size_t n_resources;
  ResourceLocalizationSpecProto **resources;
};
#define LOCALIZER_HEARTBEAT_RESPONSE_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&localizer_heartbeat_response_proto__descriptor) \
    , 0,0, 0,NULL }


/* LocalResourceStatusProto methods */
void   local_resource_status_proto__init
                     (LocalResourceStatusProto         *message);
size_t local_resource_status_proto__get_packed_size
                     (const LocalResourceStatusProto   *message);
size_t local_resource_status_proto__pack
                     (const LocalResourceStatusProto   *message,
                      uint8_t             *out);
size_t local_resource_status_proto__pack_to_buffer
                     (const LocalResourceStatusProto   *message,
                      ProtobufCBuffer     *buffer);
LocalResourceStatusProto *
       local_resource_status_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   local_resource_status_proto__free_unpacked
                     (LocalResourceStatusProto *message,
                      ProtobufCAllocator *allocator);
/* LocalizerStatusProto methods */
void   localizer_status_proto__init
                     (LocalizerStatusProto         *message);
size_t localizer_status_proto__get_packed_size
                     (const LocalizerStatusProto   *message);
size_t localizer_status_proto__pack
                     (const LocalizerStatusProto   *message,
                      uint8_t             *out);
size_t localizer_status_proto__pack_to_buffer
                     (const LocalizerStatusProto   *message,
                      ProtobufCBuffer     *buffer);
LocalizerStatusProto *
       localizer_status_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   localizer_status_proto__free_unpacked
                     (LocalizerStatusProto *message,
                      ProtobufCAllocator *allocator);
/* ResourceLocalizationSpecProto methods */
void   resource_localization_spec_proto__init
                     (ResourceLocalizationSpecProto         *message);
size_t resource_localization_spec_proto__get_packed_size
                     (const ResourceLocalizationSpecProto   *message);
size_t resource_localization_spec_proto__pack
                     (const ResourceLocalizationSpecProto   *message,
                      uint8_t             *out);
size_t resource_localization_spec_proto__pack_to_buffer
                     (const ResourceLocalizationSpecProto   *message,
                      ProtobufCBuffer     *buffer);
ResourceLocalizationSpecProto *
       resource_localization_spec_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   resource_localization_spec_proto__free_unpacked
                     (ResourceLocalizationSpecProto *message,
                      ProtobufCAllocator *allocator);
/* LocalizerHeartbeatResponseProto methods */
void   localizer_heartbeat_response_proto__init
                     (LocalizerHeartbeatResponseProto         *message);
size_t localizer_heartbeat_response_proto__get_packed_size
                     (const LocalizerHeartbeatResponseProto   *message);
size_t localizer_heartbeat_response_proto__pack
                     (const LocalizerHeartbeatResponseProto   *message,
                      uint8_t             *out);
size_t localizer_heartbeat_response_proto__pack_to_buffer
                     (const LocalizerHeartbeatResponseProto   *message,
                      ProtobufCBuffer     *buffer);
LocalizerHeartbeatResponseProto *
       localizer_heartbeat_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   localizer_heartbeat_response_proto__free_unpacked
                     (LocalizerHeartbeatResponseProto *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*LocalResourceStatusProto_Closure)
                 (const LocalResourceStatusProto *message,
                  void *closure_data);
typedef void (*LocalizerStatusProto_Closure)
                 (const LocalizerStatusProto *message,
                  void *closure_data);
typedef void (*ResourceLocalizationSpecProto_Closure)
                 (const ResourceLocalizationSpecProto *message,
                  void *closure_data);
typedef void (*LocalizerHeartbeatResponseProto_Closure)
                 (const LocalizerHeartbeatResponseProto *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    resource_status_type_proto__descriptor;
extern const ProtobufCEnumDescriptor    localizer_action_proto__descriptor;
extern const ProtobufCMessageDescriptor local_resource_status_proto__descriptor;
extern const ProtobufCMessageDescriptor localizer_status_proto__descriptor;
extern const ProtobufCMessageDescriptor resource_localization_spec_proto__descriptor;
extern const ProtobufCMessageDescriptor localizer_heartbeat_response_proto__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_yarn_5fserver_5fnodemanager_5fservice_5fprotos_2eproto__INCLUDED */
