/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_yarn_5fserver_5fcommon_5fprotos_2eproto__INCLUDED
#define PROTOBUF_C_yarn_5fserver_5fcommon_5fprotos_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS

#include "yarn_protos.pb-c.h"

typedef struct _NodeStatusProto NodeStatusProto;
typedef struct _MasterKeyProto MasterKeyProto;
typedef struct _NodeHealthStatusProto NodeHealthStatusProto;


/* --- enums --- */

typedef enum _NodeActionProto {
  NODE_ACTION_PROTO__NORMAL = 0,
  NODE_ACTION_PROTO__RESYNC = 1,
  NODE_ACTION_PROTO__SHUTDOWN = 2
} NodeActionProto;

/* --- messages --- */

struct  _NodeStatusProto
{
  ProtobufCMessage base;
  NodeIdProto *node_id;
  protobuf_c_boolean has_response_id;
  int32_t response_id;
  size_t n_containersstatuses;
  ContainerStatusProto **containersstatuses;
  NodeHealthStatusProto *nodehealthstatus;
  size_t n_keep_alive_applications;
  ApplicationIdProto **keep_alive_applications;
};
#define NODE_STATUS_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&node_status_proto__descriptor) \
    , NULL, 0,0, 0,NULL, NULL, 0,NULL }


struct  _MasterKeyProto
{
  ProtobufCMessage base;
  protobuf_c_boolean has_key_id;
  int32_t key_id;
  protobuf_c_boolean has_bytes;
  ProtobufCBinaryData bytes;
};
#define MASTER_KEY_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&master_key_proto__descriptor) \
    , 0,0, 0,{0,NULL} }


struct  _NodeHealthStatusProto
{
  ProtobufCMessage base;
  protobuf_c_boolean has_is_node_healthy;
  protobuf_c_boolean is_node_healthy;
  char *health_report;
  protobuf_c_boolean has_last_health_report_time;
  int64_t last_health_report_time;
};
#define NODE_HEALTH_STATUS_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&node_health_status_proto__descriptor) \
    , 0,0, NULL, 0,0 }


/* NodeStatusProto methods */
void   node_status_proto__init
                     (NodeStatusProto         *message);
size_t node_status_proto__get_packed_size
                     (const NodeStatusProto   *message);
size_t node_status_proto__pack
                     (const NodeStatusProto   *message,
                      uint8_t             *out);
size_t node_status_proto__pack_to_buffer
                     (const NodeStatusProto   *message,
                      ProtobufCBuffer     *buffer);
NodeStatusProto *
       node_status_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   node_status_proto__free_unpacked
                     (NodeStatusProto *message,
                      ProtobufCAllocator *allocator);
/* MasterKeyProto methods */
void   master_key_proto__init
                     (MasterKeyProto         *message);
size_t master_key_proto__get_packed_size
                     (const MasterKeyProto   *message);
size_t master_key_proto__pack
                     (const MasterKeyProto   *message,
                      uint8_t             *out);
size_t master_key_proto__pack_to_buffer
                     (const MasterKeyProto   *message,
                      ProtobufCBuffer     *buffer);
MasterKeyProto *
       master_key_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   master_key_proto__free_unpacked
                     (MasterKeyProto *message,
                      ProtobufCAllocator *allocator);
/* NodeHealthStatusProto methods */
void   node_health_status_proto__init
                     (NodeHealthStatusProto         *message);
size_t node_health_status_proto__get_packed_size
                     (const NodeHealthStatusProto   *message);
size_t node_health_status_proto__pack
                     (const NodeHealthStatusProto   *message,
                      uint8_t             *out);
size_t node_health_status_proto__pack_to_buffer
                     (const NodeHealthStatusProto   *message,
                      ProtobufCBuffer     *buffer);
NodeHealthStatusProto *
       node_health_status_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   node_health_status_proto__free_unpacked
                     (NodeHealthStatusProto *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*NodeStatusProto_Closure)
                 (const NodeStatusProto *message,
                  void *closure_data);
typedef void (*MasterKeyProto_Closure)
                 (const MasterKeyProto *message,
                  void *closure_data);
typedef void (*NodeHealthStatusProto_Closure)
                 (const NodeHealthStatusProto *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    node_action_proto__descriptor;
extern const ProtobufCMessageDescriptor node_status_proto__descriptor;
extern const ProtobufCMessageDescriptor master_key_proto__descriptor;
extern const ProtobufCMessageDescriptor node_health_status_proto__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_yarn_5fserver_5fcommon_5fprotos_2eproto__INCLUDED */
