/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "yarn_server_common_protos.pb-c.h"
void   node_status_proto__init
                     (NodeStatusProto         *message)
{
  static NodeStatusProto init_value = NODE_STATUS_PROTO__INIT;
  *message = init_value;
}
size_t node_status_proto__get_packed_size
                     (const NodeStatusProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &node_status_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t node_status_proto__pack
                     (const NodeStatusProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &node_status_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t node_status_proto__pack_to_buffer
                     (const NodeStatusProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &node_status_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NodeStatusProto *
       node_status_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NodeStatusProto *)
     protobuf_c_message_unpack (&node_status_proto__descriptor,
                                allocator, len, data);
}
void   node_status_proto__free_unpacked
                     (NodeStatusProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &node_status_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   master_key_proto__init
                     (MasterKeyProto         *message)
{
  static MasterKeyProto init_value = MASTER_KEY_PROTO__INIT;
  *message = init_value;
}
size_t master_key_proto__get_packed_size
                     (const MasterKeyProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &master_key_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t master_key_proto__pack
                     (const MasterKeyProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &master_key_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t master_key_proto__pack_to_buffer
                     (const MasterKeyProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &master_key_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MasterKeyProto *
       master_key_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MasterKeyProto *)
     protobuf_c_message_unpack (&master_key_proto__descriptor,
                                allocator, len, data);
}
void   master_key_proto__free_unpacked
                     (MasterKeyProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &master_key_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   node_health_status_proto__init
                     (NodeHealthStatusProto         *message)
{
  static NodeHealthStatusProto init_value = NODE_HEALTH_STATUS_PROTO__INIT;
  *message = init_value;
}
size_t node_health_status_proto__get_packed_size
                     (const NodeHealthStatusProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &node_health_status_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t node_health_status_proto__pack
                     (const NodeHealthStatusProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &node_health_status_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t node_health_status_proto__pack_to_buffer
                     (const NodeHealthStatusProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &node_health_status_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NodeHealthStatusProto *
       node_health_status_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NodeHealthStatusProto *)
     protobuf_c_message_unpack (&node_health_status_proto__descriptor,
                                allocator, len, data);
}
void   node_health_status_proto__free_unpacked
                     (NodeHealthStatusProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &node_health_status_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor node_status_proto__field_descriptors[5] =
{
  {
    "node_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NodeStatusProto, node_id),
    &node_id_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "response_id",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(NodeStatusProto, has_response_id),
    PROTOBUF_C_OFFSETOF(NodeStatusProto, response_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "containersStatuses",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(NodeStatusProto, n_containersstatuses),
    PROTOBUF_C_OFFSETOF(NodeStatusProto, containersstatuses),
    &container_status_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nodeHealthStatus",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NodeStatusProto, nodehealthstatus),
    &node_health_status_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "keep_alive_applications",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(NodeStatusProto, n_keep_alive_applications),
    PROTOBUF_C_OFFSETOF(NodeStatusProto, keep_alive_applications),
    &application_id_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned node_status_proto__field_indices_by_name[] = {
  2,   /* field[2] = containersStatuses */
  4,   /* field[4] = keep_alive_applications */
  3,   /* field[3] = nodeHealthStatus */
  0,   /* field[0] = node_id */
  1,   /* field[1] = response_id */
};
static const ProtobufCIntRange node_status_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor node_status_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "NodeStatusProto",
  "NodeStatusProto",
  "NodeStatusProto",
  "",
  sizeof(NodeStatusProto),
  5,
  node_status_proto__field_descriptors,
  node_status_proto__field_indices_by_name,
  1,  node_status_proto__number_ranges,
  (ProtobufCMessageInit) node_status_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor master_key_proto__field_descriptors[2] =
{
  {
    "key_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(MasterKeyProto, has_key_id),
    PROTOBUF_C_OFFSETOF(MasterKeyProto, key_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bytes",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(MasterKeyProto, has_bytes),
    PROTOBUF_C_OFFSETOF(MasterKeyProto, bytes),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned master_key_proto__field_indices_by_name[] = {
  1,   /* field[1] = bytes */
  0,   /* field[0] = key_id */
};
static const ProtobufCIntRange master_key_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor master_key_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "MasterKeyProto",
  "MasterKeyProto",
  "MasterKeyProto",
  "",
  sizeof(MasterKeyProto),
  2,
  master_key_proto__field_descriptors,
  master_key_proto__field_indices_by_name,
  1,  master_key_proto__number_ranges,
  (ProtobufCMessageInit) master_key_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor node_health_status_proto__field_descriptors[3] =
{
  {
    "is_node_healthy",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(NodeHealthStatusProto, has_is_node_healthy),
    PROTOBUF_C_OFFSETOF(NodeHealthStatusProto, is_node_healthy),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "health_report",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NodeHealthStatusProto, health_report),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last_health_report_time",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    PROTOBUF_C_OFFSETOF(NodeHealthStatusProto, has_last_health_report_time),
    PROTOBUF_C_OFFSETOF(NodeHealthStatusProto, last_health_report_time),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned node_health_status_proto__field_indices_by_name[] = {
  1,   /* field[1] = health_report */
  0,   /* field[0] = is_node_healthy */
  2,   /* field[2] = last_health_report_time */
};
static const ProtobufCIntRange node_health_status_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor node_health_status_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "NodeHealthStatusProto",
  "NodeHealthStatusProto",
  "NodeHealthStatusProto",
  "",
  sizeof(NodeHealthStatusProto),
  3,
  node_health_status_proto__field_descriptors,
  node_health_status_proto__field_indices_by_name,
  1,  node_health_status_proto__number_ranges,
  (ProtobufCMessageInit) node_health_status_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue node_action_proto__enum_values_by_number[3] =
{
  { "NORMAL", "NODE_ACTION_PROTO__NORMAL", 0 },
  { "RESYNC", "NODE_ACTION_PROTO__RESYNC", 1 },
  { "SHUTDOWN", "NODE_ACTION_PROTO__SHUTDOWN", 2 },
};
static const ProtobufCIntRange node_action_proto__value_ranges[] = {
{0, 0},{0, 3}
};
const ProtobufCEnumValueIndex node_action_proto__enum_values_by_name[3] =
{
  { "NORMAL", 0 },
  { "RESYNC", 1 },
  { "SHUTDOWN", 2 },
};
const ProtobufCEnumDescriptor node_action_proto__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "NodeActionProto",
  "NodeActionProto",
  "NodeActionProto",
  "",
  3,
  node_action_proto__enum_values_by_number,
  3,
  node_action_proto__enum_values_by_name,
  1,
  node_action_proto__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
