/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "yarn_server_common_service_protos.pb-c.h"
void   hadoop__yarn__register_node_manager_request_proto__init
                     (Hadoop__Yarn__RegisterNodeManagerRequestProto         *message)
{
  static Hadoop__Yarn__RegisterNodeManagerRequestProto init_value = HADOOP__YARN__REGISTER_NODE_MANAGER_REQUEST_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__yarn__register_node_manager_request_proto__get_packed_size
                     (const Hadoop__Yarn__RegisterNodeManagerRequestProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__register_node_manager_request_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__yarn__register_node_manager_request_proto__pack
                     (const Hadoop__Yarn__RegisterNodeManagerRequestProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__register_node_manager_request_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__yarn__register_node_manager_request_proto__pack_to_buffer
                     (const Hadoop__Yarn__RegisterNodeManagerRequestProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__register_node_manager_request_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Yarn__RegisterNodeManagerRequestProto *
       hadoop__yarn__register_node_manager_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Yarn__RegisterNodeManagerRequestProto *)
     protobuf_c_message_unpack (&hadoop__yarn__register_node_manager_request_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__yarn__register_node_manager_request_proto__free_unpacked
                     (Hadoop__Yarn__RegisterNodeManagerRequestProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__register_node_manager_request_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__yarn__register_node_manager_response_proto__init
                     (Hadoop__Yarn__RegisterNodeManagerResponseProto         *message)
{
  static Hadoop__Yarn__RegisterNodeManagerResponseProto init_value = HADOOP__YARN__REGISTER_NODE_MANAGER_RESPONSE_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__yarn__register_node_manager_response_proto__get_packed_size
                     (const Hadoop__Yarn__RegisterNodeManagerResponseProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__register_node_manager_response_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__yarn__register_node_manager_response_proto__pack
                     (const Hadoop__Yarn__RegisterNodeManagerResponseProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__register_node_manager_response_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__yarn__register_node_manager_response_proto__pack_to_buffer
                     (const Hadoop__Yarn__RegisterNodeManagerResponseProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__register_node_manager_response_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Yarn__RegisterNodeManagerResponseProto *
       hadoop__yarn__register_node_manager_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Yarn__RegisterNodeManagerResponseProto *)
     protobuf_c_message_unpack (&hadoop__yarn__register_node_manager_response_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__yarn__register_node_manager_response_proto__free_unpacked
                     (Hadoop__Yarn__RegisterNodeManagerResponseProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__register_node_manager_response_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__yarn__node_heartbeat_request_proto__init
                     (Hadoop__Yarn__NodeHeartbeatRequestProto         *message)
{
  static Hadoop__Yarn__NodeHeartbeatRequestProto init_value = HADOOP__YARN__NODE_HEARTBEAT_REQUEST_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__yarn__node_heartbeat_request_proto__get_packed_size
                     (const Hadoop__Yarn__NodeHeartbeatRequestProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__node_heartbeat_request_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__yarn__node_heartbeat_request_proto__pack
                     (const Hadoop__Yarn__NodeHeartbeatRequestProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__node_heartbeat_request_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__yarn__node_heartbeat_request_proto__pack_to_buffer
                     (const Hadoop__Yarn__NodeHeartbeatRequestProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__node_heartbeat_request_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Yarn__NodeHeartbeatRequestProto *
       hadoop__yarn__node_heartbeat_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Yarn__NodeHeartbeatRequestProto *)
     protobuf_c_message_unpack (&hadoop__yarn__node_heartbeat_request_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__yarn__node_heartbeat_request_proto__free_unpacked
                     (Hadoop__Yarn__NodeHeartbeatRequestProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__node_heartbeat_request_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hadoop__yarn__node_heartbeat_response_proto__init
                     (Hadoop__Yarn__NodeHeartbeatResponseProto         *message)
{
  static Hadoop__Yarn__NodeHeartbeatResponseProto init_value = HADOOP__YARN__NODE_HEARTBEAT_RESPONSE_PROTO__INIT;
  *message = init_value;
}
size_t hadoop__yarn__node_heartbeat_response_proto__get_packed_size
                     (const Hadoop__Yarn__NodeHeartbeatResponseProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__node_heartbeat_response_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hadoop__yarn__node_heartbeat_response_proto__pack
                     (const Hadoop__Yarn__NodeHeartbeatResponseProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__node_heartbeat_response_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hadoop__yarn__node_heartbeat_response_proto__pack_to_buffer
                     (const Hadoop__Yarn__NodeHeartbeatResponseProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__node_heartbeat_response_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hadoop__Yarn__NodeHeartbeatResponseProto *
       hadoop__yarn__node_heartbeat_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hadoop__Yarn__NodeHeartbeatResponseProto *)
     protobuf_c_message_unpack (&hadoop__yarn__node_heartbeat_response_proto__descriptor,
                                allocator, len, data);
}
void   hadoop__yarn__node_heartbeat_response_proto__free_unpacked
                     (Hadoop__Yarn__NodeHeartbeatResponseProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &hadoop__yarn__node_heartbeat_response_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor hadoop__yarn__register_node_manager_request_proto__field_descriptors[3] =
{
  {
    "node_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Yarn__RegisterNodeManagerRequestProto, node_id),
    &hadoop__yarn__node_id_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "http_port",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(Hadoop__Yarn__RegisterNodeManagerRequestProto, has_http_port),
    PROTOBUF_C_OFFSETOF(Hadoop__Yarn__RegisterNodeManagerRequestProto, http_port),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resource",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Yarn__RegisterNodeManagerRequestProto, resource),
    &hadoop__yarn__resource_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__yarn__register_node_manager_request_proto__field_indices_by_name[] = {
  1,   /* field[1] = http_port */
  0,   /* field[0] = node_id */
  2,   /* field[2] = resource */
};
static const ProtobufCIntRange hadoop__yarn__register_node_manager_request_proto__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 3, 1 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor hadoop__yarn__register_node_manager_request_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.yarn.RegisterNodeManagerRequestProto",
  "RegisterNodeManagerRequestProto",
  "Hadoop__Yarn__RegisterNodeManagerRequestProto",
  "hadoop.yarn",
  sizeof(Hadoop__Yarn__RegisterNodeManagerRequestProto),
  3,
  hadoop__yarn__register_node_manager_request_proto__field_descriptors,
  hadoop__yarn__register_node_manager_request_proto__field_indices_by_name,
  2,  hadoop__yarn__register_node_manager_request_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__yarn__register_node_manager_request_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hadoop__yarn__register_node_manager_response_proto__field_descriptors[5] =
{
  {
    "container_token_master_key",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Yarn__RegisterNodeManagerResponseProto, container_token_master_key),
    &hadoop__yarn__master_key_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nm_token_master_key",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Yarn__RegisterNodeManagerResponseProto, nm_token_master_key),
    &hadoop__yarn__master_key_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nodeAction",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(Hadoop__Yarn__RegisterNodeManagerResponseProto, has_nodeaction),
    PROTOBUF_C_OFFSETOF(Hadoop__Yarn__RegisterNodeManagerResponseProto, nodeaction),
    &hadoop__yarn__node_action_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rm_identifier",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    PROTOBUF_C_OFFSETOF(Hadoop__Yarn__RegisterNodeManagerResponseProto, has_rm_identifier),
    PROTOBUF_C_OFFSETOF(Hadoop__Yarn__RegisterNodeManagerResponseProto, rm_identifier),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "diagnostics_message",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Yarn__RegisterNodeManagerResponseProto, diagnostics_message),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__yarn__register_node_manager_response_proto__field_indices_by_name[] = {
  0,   /* field[0] = container_token_master_key */
  4,   /* field[4] = diagnostics_message */
  1,   /* field[1] = nm_token_master_key */
  2,   /* field[2] = nodeAction */
  3,   /* field[3] = rm_identifier */
};
static const ProtobufCIntRange hadoop__yarn__register_node_manager_response_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor hadoop__yarn__register_node_manager_response_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.yarn.RegisterNodeManagerResponseProto",
  "RegisterNodeManagerResponseProto",
  "Hadoop__Yarn__RegisterNodeManagerResponseProto",
  "hadoop.yarn",
  sizeof(Hadoop__Yarn__RegisterNodeManagerResponseProto),
  5,
  hadoop__yarn__register_node_manager_response_proto__field_descriptors,
  hadoop__yarn__register_node_manager_response_proto__field_indices_by_name,
  1,  hadoop__yarn__register_node_manager_response_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__yarn__register_node_manager_response_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hadoop__yarn__node_heartbeat_request_proto__field_descriptors[3] =
{
  {
    "node_status",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Yarn__NodeHeartbeatRequestProto, node_status),
    &hadoop__yarn__node_status_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last_known_container_token_master_key",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Yarn__NodeHeartbeatRequestProto, last_known_container_token_master_key),
    &hadoop__yarn__master_key_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last_known_nm_token_master_key",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Yarn__NodeHeartbeatRequestProto, last_known_nm_token_master_key),
    &hadoop__yarn__master_key_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__yarn__node_heartbeat_request_proto__field_indices_by_name[] = {
  1,   /* field[1] = last_known_container_token_master_key */
  2,   /* field[2] = last_known_nm_token_master_key */
  0,   /* field[0] = node_status */
};
static const ProtobufCIntRange hadoop__yarn__node_heartbeat_request_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor hadoop__yarn__node_heartbeat_request_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.yarn.NodeHeartbeatRequestProto",
  "NodeHeartbeatRequestProto",
  "Hadoop__Yarn__NodeHeartbeatRequestProto",
  "hadoop.yarn",
  sizeof(Hadoop__Yarn__NodeHeartbeatRequestProto),
  3,
  hadoop__yarn__node_heartbeat_request_proto__field_descriptors,
  hadoop__yarn__node_heartbeat_request_proto__field_indices_by_name,
  1,  hadoop__yarn__node_heartbeat_request_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__yarn__node_heartbeat_request_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hadoop__yarn__node_heartbeat_response_proto__field_descriptors[8] =
{
  {
    "response_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(Hadoop__Yarn__NodeHeartbeatResponseProto, has_response_id),
    PROTOBUF_C_OFFSETOF(Hadoop__Yarn__NodeHeartbeatResponseProto, response_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "container_token_master_key",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Yarn__NodeHeartbeatResponseProto, container_token_master_key),
    &hadoop__yarn__master_key_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nm_token_master_key",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Yarn__NodeHeartbeatResponseProto, nm_token_master_key),
    &hadoop__yarn__master_key_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nodeAction",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(Hadoop__Yarn__NodeHeartbeatResponseProto, has_nodeaction),
    PROTOBUF_C_OFFSETOF(Hadoop__Yarn__NodeHeartbeatResponseProto, nodeaction),
    &hadoop__yarn__node_action_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "containers_to_cleanup",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Hadoop__Yarn__NodeHeartbeatResponseProto, n_containers_to_cleanup),
    PROTOBUF_C_OFFSETOF(Hadoop__Yarn__NodeHeartbeatResponseProto, containers_to_cleanup),
    &hadoop__yarn__container_id_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "applications_to_cleanup",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Hadoop__Yarn__NodeHeartbeatResponseProto, n_applications_to_cleanup),
    PROTOBUF_C_OFFSETOF(Hadoop__Yarn__NodeHeartbeatResponseProto, applications_to_cleanup),
    &hadoop__yarn__application_id_proto__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nextHeartBeatInterval",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    PROTOBUF_C_OFFSETOF(Hadoop__Yarn__NodeHeartbeatResponseProto, has_nextheartbeatinterval),
    PROTOBUF_C_OFFSETOF(Hadoop__Yarn__NodeHeartbeatResponseProto, nextheartbeatinterval),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "diagnostics_message",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Hadoop__Yarn__NodeHeartbeatResponseProto, diagnostics_message),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hadoop__yarn__node_heartbeat_response_proto__field_indices_by_name[] = {
  5,   /* field[5] = applications_to_cleanup */
  1,   /* field[1] = container_token_master_key */
  4,   /* field[4] = containers_to_cleanup */
  7,   /* field[7] = diagnostics_message */
  6,   /* field[6] = nextHeartBeatInterval */
  2,   /* field[2] = nm_token_master_key */
  3,   /* field[3] = nodeAction */
  0,   /* field[0] = response_id */
};
static const ProtobufCIntRange hadoop__yarn__node_heartbeat_response_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor hadoop__yarn__node_heartbeat_response_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "hadoop.yarn.NodeHeartbeatResponseProto",
  "NodeHeartbeatResponseProto",
  "Hadoop__Yarn__NodeHeartbeatResponseProto",
  "hadoop.yarn",
  sizeof(Hadoop__Yarn__NodeHeartbeatResponseProto),
  8,
  hadoop__yarn__node_heartbeat_response_proto__field_descriptors,
  hadoop__yarn__node_heartbeat_response_proto__field_indices_by_name,
  1,  hadoop__yarn__node_heartbeat_response_proto__number_ranges,
  (ProtobufCMessageInit) hadoop__yarn__node_heartbeat_response_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
